import { th } from '@xstyled/system';

type ThemeGetters = ReturnType<typeof th>;

export type Theme = {
  colors: Colors;
  radii: Radii;
  space: Space;
  sizes: Sizes;
  borderWidths: BorderWidths;
  borderStyles: BorderStyles;
  fonts: Fonts;
  fontSizes: FontSizes;
  fontWeights: FontWeights;
  letterSpacings: LetterSpacings;
  lineHeights: LineHeights;
  texts: Texts;
  shadows: Shadows;
  opacity: Opacity;
  screens: Screens;
  states: States;
  ringWidths: BorderWidths;
};

export type Colors = {
  '$color-coolGrey--4': string;
  '$color-coolGrey--3': string;
  '$color-coolGrey--2': string;
  '$color-coolGrey--1': string;
  '$color-coolGrey-0': string;
  '$color-coolGrey-+1': string;
  '$color-coolGrey-+2': string;
  '$color-coolGrey-+3': string;
  '$color-coolGrey-+4': string;
  '$color-coolGrey-+5': string;
  '$color-coolGrey-+6': string;
  '$color-coolGrey-+7': string;
  '$color-coolGrey-+8': string;
  '$color-coolGreyA--4': string;
  '$color-coolGreyA--3': string;
  '$color-coolGreyA--2': string;
  '$color-coolGreyA--1': string;
  '$color-coolGreyA-0': string;
  '$color-coolGreyA-+1': string;
  '$color-coolGreyA-+2': string;
  '$color-coolGreyA-+3': string;
  '$color-coolGreyA-+4': string;
  '$color-coolGreyA-+5': string;
  '$color-coolGreyA-+6': string;
  '$color-coolGreyA-+7': string;
  '$color-coolGreyA-+8': string;
  '$color-neutralGrey--4': string;
  '$color-neutralGrey--3': string;
  '$color-neutralGrey--2': string;
  '$color-neutralGrey--1': string;
  '$color-neutralGrey-0': string;
  '$color-neutralGrey-+1': string;
  '$color-neutralGrey-+2': string;
  '$color-neutralGrey-+3': string;
  '$color-neutralGrey-+4': string;
  '$color-neutralGrey-+5': string;
  '$color-neutralGrey-+6': string;
  '$color-neutralGrey-+7': string;
  '$color-neutralGrey-+8': string;
  '$color-neutralGreyA--4': string;
  '$color-neutralGreyA--3': string;
  '$color-neutralGreyA--2': string;
  '$color-neutralGreyA--1': string;
  '$color-neutralGreyA-0': string;
  '$color-neutralGreyA-+1': string;
  '$color-neutralGreyA-+2': string;
  '$color-neutralGreyA-+3': string;
  '$color-neutralGreyA-+4': string;
  '$color-neutralGreyA-+5': string;
  '$color-neutralGreyA-+6': string;
  '$color-neutralGreyA-+7': string;
  '$color-neutralGreyA-+8': string;
  '$color-warmGrey--4': string;
  '$color-warmGrey--3': string;
  '$color-warmGrey--2': string;
  '$color-warmGrey--1': string;
  '$color-warmGrey-0': string;
  '$color-warmGrey-+1': string;
  '$color-warmGrey-+2': string;
  '$color-warmGrey-+3': string;
  '$color-warmGrey-+4': string;
  '$color-warmGrey-+5': string;
  '$color-warmGrey-+6': string;
  '$color-warmGrey-+7': string;
  '$color-warmGrey-+8': string;
  '$color-warmGreyA--4': string;
  '$color-warmGreyA--3': string;
  '$color-warmGreyA--2': string;
  '$color-warmGreyA--1': string;
  '$color-warmGreyA-0': string;
  '$color-warmGreyA-+1': string;
  '$color-warmGreyA-+2': string;
  '$color-warmGreyA-+3': string;
  '$color-warmGreyA-+4': string;
  '$color-warmGreyA-+5': string;
  '$color-warmGreyA-+6': string;
  '$color-warmGreyA-+7': string;
  '$color-warmGreyA-+8': string;
  '$color-whiteA--12': string;
  '$color-whiteA--11': string;
  '$color-whiteA--10': string;
  '$color-whiteA--9': string;
  '$color-whiteA--8': string;
  '$color-whiteA--7': string;
  '$color-whiteA--6': string;
  '$color-whiteA--5': string;
  '$color-whiteA--4': string;
  '$color-whiteA--3': string;
  '$color-whiteA--2': string;
  '$color-whiteA--1': string;
  '$color-whiteA-0': string;
  '$color-transparent': string;
  '$color-red--4': string;
  '$color-red--3': string;
  '$color-red--2': string;
  '$color-red--1': string;
  '$color-red-0': string;
  '$color-red-+1': string;
  '$color-red-+2': string;
  '$color-red-+3': string;
  '$color-red-+4': string;
  '$color-red-+5': string;
  '$color-red-+6': string;
  '$color-red-+7': string;
  '$color-red-+8': string;
  '$color-raspberry--4': string;
  '$color-raspberry--3': string;
  '$color-raspberry--2': string;
  '$color-raspberry--1': string;
  '$color-raspberry-0': string;
  '$color-raspberry-+1': string;
  '$color-raspberry-+2': string;
  '$color-raspberry-+3': string;
  '$color-raspberry-+4': string;
  '$color-raspberry-+5': string;
  '$color-raspberry-+6': string;
  '$color-raspberry-+7': string;
  '$color-raspberry-+8': string;
  '$color-magenta--4': string;
  '$color-magenta--3': string;
  '$color-magenta--2': string;
  '$color-magenta--1': string;
  '$color-magenta-0': string;
  '$color-magenta-+1': string;
  '$color-magenta-+2': string;
  '$color-magenta-+3': string;
  '$color-magenta-+4': string;
  '$color-magenta-+5': string;
  '$color-magenta-+6': string;
  '$color-magenta-+7': string;
  '$color-magenta-+8': string;
  '$color-purple--4': string;
  '$color-purple--3': string;
  '$color-purple--2': string;
  '$color-purple--1': string;
  '$color-purple-0': string;
  '$color-purple-+1': string;
  '$color-purple-+2': string;
  '$color-purple-+3': string;
  '$color-purple-+4': string;
  '$color-purple-+5': string;
  '$color-purple-+6': string;
  '$color-purple-+7': string;
  '$color-purple-+8': string;
  '$color-grape--4': string;
  '$color-grape--3': string;
  '$color-grape--2': string;
  '$color-grape--1': string;
  '$color-grape-0': string;
  '$color-grape-+1': string;
  '$color-grape-+2': string;
  '$color-grape-+3': string;
  '$color-grape-+4': string;
  '$color-grape-+5': string;
  '$color-grape-+6': string;
  '$color-grape-+7': string;
  '$color-grape-+8': string;
  '$color-violet--4': string;
  '$color-violet--3': string;
  '$color-violet--2': string;
  '$color-violet--1': string;
  '$color-violet-0': string;
  '$color-violet-+1': string;
  '$color-violet-+2': string;
  '$color-violet-+3': string;
  '$color-violet-+4': string;
  '$color-violet-+5': string;
  '$color-violet-+6': string;
  '$color-violet-+7': string;
  '$color-violet-+8': string;
  '$color-blue--4': string;
  '$color-blue--3': string;
  '$color-blue--2': string;
  '$color-blue--1': string;
  '$color-blue-0': string;
  '$color-blue-+1': string;
  '$color-blue-+2': string;
  '$color-blue-+3': string;
  '$color-blue-+4': string;
  '$color-blue-+5': string;
  '$color-blue-+6': string;
  '$color-blue-+7': string;
  '$color-blue-+8': string;
  '$color-cyan--4': string;
  '$color-cyan--3': string;
  '$color-cyan--2': string;
  '$color-cyan--1': string;
  '$color-cyan-0': string;
  '$color-cyan-+1': string;
  '$color-cyan-+2': string;
  '$color-cyan-+3': string;
  '$color-cyan-+4': string;
  '$color-cyan-+5': string;
  '$color-cyan-+6': string;
  '$color-cyan-+7': string;
  '$color-cyan-+8': string;
  '$color-teal--4': string;
  '$color-teal--3': string;
  '$color-teal--2': string;
  '$color-teal--1': string;
  '$color-teal-0': string;
  '$color-teal-+1': string;
  '$color-teal-+2': string;
  '$color-teal-+3': string;
  '$color-teal-+4': string;
  '$color-teal-+5': string;
  '$color-teal-+6': string;
  '$color-teal-+7': string;
  '$color-teal-+8': string;
  '$color-aquamarine--4': string;
  '$color-aquamarine--3': string;
  '$color-aquamarine--2': string;
  '$color-aquamarine--1': string;
  '$color-aquamarine-0': string;
  '$color-aquamarine-+1': string;
  '$color-aquamarine-+2': string;
  '$color-aquamarine-+3': string;
  '$color-aquamarine-+4': string;
  '$color-aquamarine-+5': string;
  '$color-aquamarine-+6': string;
  '$color-aquamarine-+7': string;
  '$color-aquamarine-+8': string;
  '$color-green--4': string;
  '$color-green--3': string;
  '$color-green--2': string;
  '$color-green--1': string;
  '$color-green-0': string;
  '$color-green-+1': string;
  '$color-green-+2': string;
  '$color-green-+3': string;
  '$color-green-+4': string;
  '$color-green-+5': string;
  '$color-green-+6': string;
  '$color-green-+7': string;
  '$color-green-+8': string;
  '$color-emerald--4': string;
  '$color-emerald--3': string;
  '$color-emerald--2': string;
  '$color-emerald--1': string;
  '$color-emerald-0': string;
  '$color-emerald-+1': string;
  '$color-emerald-+2': string;
  '$color-emerald-+3': string;
  '$color-emerald-+4': string;
  '$color-emerald-+5': string;
  '$color-emerald-+6': string;
  '$color-emerald-+7': string;
  '$color-emerald-+8': string;
  '$color-orange--4': string;
  '$color-orange--3': string;
  '$color-orange--2': string;
  '$color-orange--1': string;
  '$color-orange-0': string;
  '$color-orange-+1': string;
  '$color-orange-+2': string;
  '$color-orange-+3': string;
  '$color-orange-+4': string;
  '$color-orange-+5': string;
  '$color-orange-+6': string;
  '$color-orange-+7': string;
  '$color-orange-+8': string;
  '$color-semantic-brand--4': ReturnType<typeof th>;
  '$color-semantic-brand--3': ReturnType<typeof th>;
  '$color-semantic-brand--2': ReturnType<typeof th>;
  '$color-semantic-brand--1': ReturnType<typeof th>;
  '$color-semantic-brand-0': ReturnType<typeof th>;
  '$color-semantic-brand-+1': ReturnType<typeof th>;
  '$color-semantic-brand-+2': ReturnType<typeof th>;
  '$color-semantic-brand-+3': ReturnType<typeof th>;
  '$color-semantic-brand-+4': ReturnType<typeof th>;
  '$color-semantic-brand-+5': ReturnType<typeof th>;
  '$color-semantic-brand-+6': ReturnType<typeof th>;
  '$color-semantic-brand-+7': ReturnType<typeof th>;
  '$color-semantic-brand-+8': ReturnType<typeof th>;
  '$color-semantic-neutral--4': ReturnType<typeof th>;
  '$color-semantic-neutral--3': ReturnType<typeof th>;
  '$color-semantic-neutral--2': ReturnType<typeof th>;
  '$color-semantic-neutral--1': ReturnType<typeof th>;
  '$color-semantic-neutral-0': ReturnType<typeof th>;
  '$color-semantic-neutral-+1': ReturnType<typeof th>;
  '$color-semantic-neutral-+2': ReturnType<typeof th>;
  '$color-semantic-neutral-+3': ReturnType<typeof th>;
  '$color-semantic-neutral-+4': ReturnType<typeof th>;
  '$color-semantic-neutral-+5': ReturnType<typeof th>;
  '$color-semantic-neutral-+6': ReturnType<typeof th>;
  '$color-semantic-neutral-+7': ReturnType<typeof th>;
  '$color-semantic-neutral-+8': ReturnType<typeof th>;
  '$color-semantic-neutralA--4': ReturnType<typeof th>;
  '$color-semantic-neutralA--3': ReturnType<typeof th>;
  '$color-semantic-neutralA--2': ReturnType<typeof th>;
  '$color-semantic-neutralA--1': ReturnType<typeof th>;
  '$color-semantic-neutralA-0': ReturnType<typeof th>;
  '$color-semantic-neutralA-+1': ReturnType<typeof th>;
  '$color-semantic-neutralA-+2': ReturnType<typeof th>;
  '$color-semantic-neutralA-+3': ReturnType<typeof th>;
  '$color-semantic-neutralA-+4': ReturnType<typeof th>;
  '$color-semantic-neutralA-+5': ReturnType<typeof th>;
  '$color-semantic-neutralA-+6': ReturnType<typeof th>;
  '$color-semantic-neutralA-+7': ReturnType<typeof th>;
  '$color-semantic-neutralA-+8': ReturnType<typeof th>;
  '$color-semantic-informative--4': ReturnType<typeof th>;
  '$color-semantic-informative--3': ReturnType<typeof th>;
  '$color-semantic-informative--2': ReturnType<typeof th>;
  '$color-semantic-informative--1': ReturnType<typeof th>;
  '$color-semantic-informative-0': ReturnType<typeof th>;
  '$color-semantic-informative-+1': ReturnType<typeof th>;
  '$color-semantic-informative-+2': ReturnType<typeof th>;
  '$color-semantic-informative-+3': ReturnType<typeof th>;
  '$color-semantic-informative-+4': ReturnType<typeof th>;
  '$color-semantic-informative-+5': ReturnType<typeof th>;
  '$color-semantic-informative-+6': ReturnType<typeof th>;
  '$color-semantic-informative-+7': ReturnType<typeof th>;
  '$color-semantic-informative-+8': ReturnType<typeof th>;
  '$color-semantic-positive--4': ReturnType<typeof th>;
  '$color-semantic-positive--3': ReturnType<typeof th>;
  '$color-semantic-positive--2': ReturnType<typeof th>;
  '$color-semantic-positive--1': ReturnType<typeof th>;
  '$color-semantic-positive-0': ReturnType<typeof th>;
  '$color-semantic-positive-+1': ReturnType<typeof th>;
  '$color-semantic-positive-+2': ReturnType<typeof th>;
  '$color-semantic-positive-+3': ReturnType<typeof th>;
  '$color-semantic-positive-+4': ReturnType<typeof th>;
  '$color-semantic-positive-+5': ReturnType<typeof th>;
  '$color-semantic-positive-+6': ReturnType<typeof th>;
  '$color-semantic-positive-+7': ReturnType<typeof th>;
  '$color-semantic-positive-+8': ReturnType<typeof th>;
  '$color-semantic-warning--4': ReturnType<typeof th>;
  '$color-semantic-warning--3': ReturnType<typeof th>;
  '$color-semantic-warning--2': ReturnType<typeof th>;
  '$color-semantic-warning--1': ReturnType<typeof th>;
  '$color-semantic-warning-0': ReturnType<typeof th>;
  '$color-semantic-warning-+1': ReturnType<typeof th>;
  '$color-semantic-warning-+2': ReturnType<typeof th>;
  '$color-semantic-warning-+3': ReturnType<typeof th>;
  '$color-semantic-warning-+4': ReturnType<typeof th>;
  '$color-semantic-warning-+5': ReturnType<typeof th>;
  '$color-semantic-warning-+6': ReturnType<typeof th>;
  '$color-semantic-warning-+7': ReturnType<typeof th>;
  '$color-semantic-warning-+8': ReturnType<typeof th>;
  '$color-semantic-negative--4': ReturnType<typeof th>;
  '$color-semantic-negative--3': ReturnType<typeof th>;
  '$color-semantic-negative--2': ReturnType<typeof th>;
  '$color-semantic-negative--1': ReturnType<typeof th>;
  '$color-semantic-negative-0': ReturnType<typeof th>;
  '$color-semantic-negative-+1': ReturnType<typeof th>;
  '$color-semantic-negative-+2': ReturnType<typeof th>;
  '$color-semantic-negative-+3': ReturnType<typeof th>;
  '$color-semantic-negative-+4': ReturnType<typeof th>;
  '$color-semantic-negative-+5': ReturnType<typeof th>;
  '$color-semantic-negative-+6': ReturnType<typeof th>;
  '$color-semantic-negative-+7': ReturnType<typeof th>;
  '$color-semantic-negative-+8': ReturnType<typeof th>;
  '$color-content-primary': ReturnType<typeof th>;
  '$color-content-secondary': ReturnType<typeof th>;
  '$color-content-tertiary': ReturnType<typeof th>;
  '$color-content-disabled': ReturnType<typeof th>;
  '$color-content-primary-inverted': ReturnType<typeof th>;
  '$color-content-secondary-inverted': ReturnType<typeof th>;
  '$color-content-tertiary-inverted': ReturnType<typeof th>;
  '$color-content-disabled-inverted': ReturnType<typeof th>;
  '$color-content-informative-primary': ReturnType<typeof th>;
  '$color-content-informative-secondary': ReturnType<typeof th>;
  '$color-content-positive-primary': ReturnType<typeof th>;
  '$color-content-positive-secondary': ReturnType<typeof th>;
  '$color-content-warning-primary': ReturnType<typeof th>;
  '$color-content-warning-secondary': ReturnType<typeof th>;
  '$color-content-negative-primary': ReturnType<typeof th>;
  '$color-content-negative-secondary': ReturnType<typeof th>;
  '$color-content-brand-primary': ReturnType<typeof th>;
  '$color-content-brand-secondary': ReturnType<typeof th>;
  '$color-border-default': ReturnType<typeof th>;
  '$color-border-defaultA': ReturnType<typeof th>;
  '$color-border-inverted': ReturnType<typeof th>;
  '$color-border-neutral-strong': ReturnType<typeof th>;
  '$color-border-neutral-subtle': ReturnType<typeof th>;
  '$color-border-informative-strong': ReturnType<typeof th>;
  '$color-border-informative-subtle': ReturnType<typeof th>;
  '$color-border-positive-strong': ReturnType<typeof th>;
  '$color-border-positive-subtle': ReturnType<typeof th>;
  '$color-border-warning-strong': ReturnType<typeof th>;
  '$color-border-warning-subtle': ReturnType<typeof th>;
  '$color-border-negative-strong': ReturnType<typeof th>;
  '$color-border-negative-subtle': ReturnType<typeof th>;
  '$color-border-brand-strong': ReturnType<typeof th>;
  '$color-border-brand-subtle': ReturnType<typeof th>;
  '$color-background-default': ReturnType<typeof th>;
  '$color-background-inverted': ReturnType<typeof th>;
  '$color-background-neutral-strong': ReturnType<typeof th>;
  '$color-background-neutral-muted': ReturnType<typeof th>;
  '$color-background-neutral-onSubtle': ReturnType<typeof th>;
  '$color-background-neutral-subtle': ReturnType<typeof th>;
  '$color-background-neutral-surface': ReturnType<typeof th>;
  '$color-background-informative-strong': ReturnType<typeof th>;
  '$color-background-informative-muted': ReturnType<typeof th>;
  '$color-background-informative-onSubtle': ReturnType<typeof th>;
  '$color-background-informative-subtle': ReturnType<typeof th>;
  '$color-background-informative-surface': ReturnType<typeof th>;
  '$color-background-positive-strong': ReturnType<typeof th>;
  '$color-background-positive-muted': ReturnType<typeof th>;
  '$color-background-positive-onSubtle': ReturnType<typeof th>;
  '$color-background-positive-subtle': ReturnType<typeof th>;
  '$color-background-positive-surface': ReturnType<typeof th>;
  '$color-background-warning-strong': ReturnType<typeof th>;
  '$color-background-warning-muted': ReturnType<typeof th>;
  '$color-background-warning-onSubtle': ReturnType<typeof th>;
  '$color-background-warning-subtle': ReturnType<typeof th>;
  '$color-background-warning-surface': ReturnType<typeof th>;
  '$color-background-negative-strong': ReturnType<typeof th>;
  '$color-background-negative-muted': ReturnType<typeof th>;
  '$color-background-negative-onSubtle': ReturnType<typeof th>;
  '$color-background-negative-subtle': ReturnType<typeof th>;
  '$color-background-negative-surface': ReturnType<typeof th>;
  '$color-background-brand-strong': ReturnType<typeof th>;
  '$color-background-brand-muted': ReturnType<typeof th>;
  '$color-background-brand-onSubtle': ReturnType<typeof th>;
  '$color-background-brand-subtle': ReturnType<typeof th>;
  '$color-background-brand-surface': ReturnType<typeof th>;
  '$color-action-primary-normal': ReturnType<typeof th>;
  '$color-action-primary-hover': ReturnType<typeof th>;
  '$color-action-primary-active': ReturnType<typeof th>;
  '$color-action-primary-selected': ReturnType<typeof th>;
  '$color-action-primary-subtle-normal': ReturnType<typeof th>;
  '$color-action-primary-subtle-hover': ReturnType<typeof th>;
  '$color-action-primary-subtle-active': ReturnType<typeof th>;
  '$color-action-primary-subtle-selected': ReturnType<typeof th>;
  '$color-action-neutral-normal': ReturnType<typeof th>;
  '$color-action-neutral-hover': ReturnType<typeof th>;
  '$color-action-neutral-active': ReturnType<typeof th>;
  '$color-action-neutral-selected': ReturnType<typeof th>;
  '$color-action-neutral-subtle-normal': ReturnType<typeof th>;
  '$color-action-neutral-subtle-hover': ReturnType<typeof th>;
  '$color-action-neutral-subtle-active': ReturnType<typeof th>;
  '$color-action-neutral-subtle-selected': ReturnType<typeof th>;
  '$color-action-success-normal': ReturnType<typeof th>;
  '$color-action-success-hover': ReturnType<typeof th>;
  '$color-action-success-active': ReturnType<typeof th>;
  '$color-action-success-selected': ReturnType<typeof th>;
  '$color-action-success-subtle-normal': ReturnType<typeof th>;
  '$color-action-success-subtle-hover': ReturnType<typeof th>;
  '$color-action-success-subtle-active': ReturnType<typeof th>;
  '$color-action-success-subtle-selected': ReturnType<typeof th>;
  '$color-action-destructive-normal': ReturnType<typeof th>;
  '$color-action-destructive-hover': ReturnType<typeof th>;
  '$color-action-destructive-active': ReturnType<typeof th>;
  '$color-action-destructive-selected': ReturnType<typeof th>;
  '$color-action-destructive-subtle-normal': ReturnType<typeof th>;
  '$color-action-destructive-subtle-hover': ReturnType<typeof th>;
  '$color-action-destructive-subtle-active': ReturnType<typeof th>;
  '$color-action-destructive-subtle-selected': ReturnType<typeof th>;
  '$color-action-ghost-normal': ReturnType<typeof th>;
  '$color-action-ghost-hover': ReturnType<typeof th>;
  '$color-action-ghost-active': ReturnType<typeof th>;
  '$color-action-ghost-selected': ReturnType<typeof th>;
  '$color-action-ghost-inverted-hover': ReturnType<typeof th>;
  '$color-action-ghost-inverted-active': ReturnType<typeof th>;
  '$color-action-ghost-inverted-selected': ReturnType<typeof th>;
  '$color-action-ghost-destructive-hover': ReturnType<typeof th>;
  '$color-action-ghost-destructive-active': ReturnType<typeof th>;
  '$color-action-ghost-destructive-selected': ReturnType<typeof th>;
  '$color-action-outline-normal': ReturnType<typeof th>;
  '$color-action-outline-hover': ReturnType<typeof th>;
  '$color-action-outline-active': ReturnType<typeof th>;
  '$color-action-outline-selected': ReturnType<typeof th>;
  '$color-action-inverted-normal': ReturnType<typeof th>;
  '$color-action-inverted-hover': ReturnType<typeof th>;
  '$color-action-inverted-active': ReturnType<typeof th>;
  '$color-action-inverted-selected': ReturnType<typeof th>;
  '$color-action-reverseInverted-normal': ReturnType<typeof th>;
  '$color-action-reverseInverted-hover': ReturnType<typeof th>;
  '$color-action-reverseInverted-active': ReturnType<typeof th>;
  '$color-action-reverseInverted-selected': ReturnType<typeof th>;
  '$color-interaction-default-normal': ReturnType<typeof th>;
  '$color-interaction-default-hover': ReturnType<typeof th>;
  '$color-interaction-default-active': ReturnType<typeof th>;
  '$color-interaction-default-selected': ReturnType<typeof th>;
  '$color-interaction-default-subtle-normal': ReturnType<typeof th>;
  '$color-interaction-default-subtle-hover': ReturnType<typeof th>;
  '$color-interaction-default-subtle-active': ReturnType<typeof th>;
  '$color-interaction-default-subtle-selected': ReturnType<typeof th>;
  '$color-interaction-neutral-normal': ReturnType<typeof th>;
  '$color-interaction-neutral-hover': ReturnType<typeof th>;
  '$color-interaction-neutral-active': ReturnType<typeof th>;
  '$color-interaction-neutral-selected': ReturnType<typeof th>;
  '$color-interaction-neutral-subtle-normal': ReturnType<typeof th>;
  '$color-interaction-neutral-subtle-hover': ReturnType<typeof th>;
  '$color-interaction-neutral-subtle-active': ReturnType<typeof th>;
  '$color-interaction-neutral-subtle-selected': ReturnType<typeof th>;
  '$color-interaction-alert-normal': ReturnType<typeof th>;
  '$color-interaction-alert-hover': ReturnType<typeof th>;
  '$color-interaction-alert-active': ReturnType<typeof th>;
  '$color-interaction-alert-selected': ReturnType<typeof th>;
  '$color-interaction-alert-subtle-normal': ReturnType<typeof th>;
  '$color-interaction-alert-subtle-hover': ReturnType<typeof th>;
  '$color-interaction-alert-subtle-active': ReturnType<typeof th>;
  '$color-interaction-alert-subtle-selected': ReturnType<typeof th>;
  '$color-interaction-ghost-normal': ReturnType<typeof th>;
  '$color-interaction-ghost-hover': ReturnType<typeof th>;
  '$color-interaction-ghost-active': ReturnType<typeof th>;
  '$color-interaction-ghost-selected': ReturnType<typeof th>;
  '$color-interaction-ghost-inverted-hover': ReturnType<typeof th>;
  '$color-interaction-ghost-inverted-normal': ReturnType<typeof th>;
  '$color-interaction-ghost-inverted-selected': ReturnType<typeof th>;
  '$color-interaction-ghost-destructive-selected': ReturnType<typeof th>;
  '$color-interaction-ghost-destructive-normal': ReturnType<typeof th>;
  '$color-interaction-ghost-destructive-hover': ReturnType<typeof th>;
  '$color-interaction-disabled-normal': ReturnType<typeof th>;
  '$color-interaction-disabled-hover': ReturnType<typeof th>;
  '$color-interaction-disabled-active': ReturnType<typeof th>;
  '$color-interaction-disabled-subtle-normal': ReturnType<typeof th>;
  '$color-interaction-disabled-subtle-hover': ReturnType<typeof th>;
  '$color-interaction-disabled-subtle-active': ReturnType<typeof th>;
  '$color-interaction-border-normal': ReturnType<typeof th>;
  '$color-interaction-border-hover': ReturnType<typeof th>;
  '$color-interaction-border-active': ReturnType<typeof th>;
  '$color-interaction-border-selected': ReturnType<typeof th>;
  '$color-interaction-border-neutral-normal': ReturnType<typeof th>;
  '$color-interaction-border-neutral-hover': ReturnType<typeof th>;
  '$color-interaction-border-neutral-active': ReturnType<typeof th>;
  '$color-interaction-border-neutral-selected': ReturnType<typeof th>;
  '$color-interaction-border-alert': ReturnType<typeof th>;
  '$color-interaction-background-modal': ReturnType<typeof th>;
  '$color-interaction-background-modeless': ReturnType<typeof th>;
  '$color-interaction-background-modeless-inverted': ReturnType<typeof th>;
  '$color-interaction-background-sidepanel': ReturnType<typeof th>;
  '$color-interaction-background-formField': ReturnType<typeof th>;
  '$color-interaction-background-dimmer': ReturnType<typeof th>;
  '$color-interaction-inverted-normal': ReturnType<typeof th>;
  '$color-interaction-inverted-hover': ReturnType<typeof th>;
  '$color-interaction-inverted-active': ReturnType<typeof th>;
  '$color-interaction-inverted-selected': ReturnType<typeof th>;
  '$color-interaction-focus-default': ReturnType<typeof th>;
  '$color-nonSemantic-grey-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-grey-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-grey-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-grey-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-grey-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-grey-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-grey-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-grey-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-grey-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-grey-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-white-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-white-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-white-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-white-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-white-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-white-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-white-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-white-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-white-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-white-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-red-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-red-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-red-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-red-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-red-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-red-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-red-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-red-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-red-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-red-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-raspberry-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-magenta-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-purple-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-purple-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-purple-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-purple-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-purple-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-purple-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-purple-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-purple-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-purple-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-purple-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-grape-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-grape-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-grape-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-grape-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-grape-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-grape-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-grape-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-grape-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-grape-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-grape-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-violet-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-violet-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-violet-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-violet-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-violet-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-violet-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-violet-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-violet-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-violet-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-violet-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-blue-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-blue-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-blue-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-blue-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-blue-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-blue-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-blue-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-blue-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-blue-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-blue-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-cyan-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-teal-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-teal-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-teal-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-teal-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-teal-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-teal-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-teal-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-teal-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-teal-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-teal-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-aquamarine-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-green-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-green-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-green-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-green-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-green-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-green-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-green-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-green-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-green-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-green-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-emerald-background-surface': ReturnType<typeof th>;
  '$color-nonSemantic-orange-content-primary': ReturnType<typeof th>;
  '$color-nonSemantic-orange-content-secondary': ReturnType<typeof th>;
  '$color-nonSemantic-orange-border-default': ReturnType<typeof th>;
  '$color-nonSemantic-orange-border-strong': ReturnType<typeof th>;
  '$color-nonSemantic-orange-border-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-orange-background-strong': ReturnType<typeof th>;
  '$color-nonSemantic-orange-background-muted': ReturnType<typeof th>;
  '$color-nonSemantic-orange-background-onSubtle': ReturnType<typeof th>;
  '$color-nonSemantic-orange-background-subtle': ReturnType<typeof th>;
  '$color-nonSemantic-orange-background-surface': ReturnType<typeof th>;
};

export type Radii = {
  '$border-radius-25': number;
  '$border-radius-50': number;
  '$border-radius-100': number;
  '$border-radius-999': number;
  '$border-radius-small': ReturnType<typeof th>;
  '$border-radius-medium': ReturnType<typeof th>;
  '$border-radius-large': ReturnType<typeof th>;
  '$border-radius-full': ReturnType<typeof th>;
  '$border-radius-150': number;
  '$border-radius-xLarge': ReturnType<typeof th>;
};

export type Sizes = {
  '$size-2xLarge': ReturnType<typeof th>;
  '$size-large': ReturnType<typeof th>;
  '$size-medium': ReturnType<typeof th>;
  '$size-small': ReturnType<typeof th>;
  '$size-xSmall': ReturnType<typeof th>;
  '$size-2xSmall': ReturnType<typeof th>;
  '$size-3xSmall': ReturnType<typeof th>;
  '$size-xLarge': ReturnType<typeof th>;
  '$size-3xLarge': ReturnType<typeof th>;
};

export type Space = {
  '$space-component-padding-null': ReturnType<typeof th>;
  '$space-component-padding-xSmall': ReturnType<typeof th>;
  '$space-component-padding-small': ReturnType<typeof th>;
  '$space-component-padding-medium': ReturnType<typeof th>;
  '$space-component-padding-large': ReturnType<typeof th>;
  '$space-component-padding-2xLarge': ReturnType<typeof th>;
  '$space-component-gap-null': ReturnType<typeof th>;
  '$space-component-gap-2xSmall': ReturnType<typeof th>;
  '$space-component-gap-xSmall': ReturnType<typeof th>;
  '$space-component-gap-small': ReturnType<typeof th>;
  '$space-component-gap-medium': ReturnType<typeof th>;
  '$space-component-gap-large': ReturnType<typeof th>;
  '$space-component-gap-2xLarge': ReturnType<typeof th>;
  '$space-component-gap-xLarge': ReturnType<typeof th>;
  '$space-component-padding-3xLarge': ReturnType<typeof th>;
  '$space-component-padding-4xLarge': ReturnType<typeof th>;
  '$space-component-padding-6xLarge': ReturnType<typeof th>;
  '$space-component-padding-2xSmall': ReturnType<typeof th>;
  '$space-component-padding-xLarge': ReturnType<typeof th>;
  '$dimension-0': number;
  '$dimension-25': number;
  '$dimension-50': number;
  '$dimension-100': number;
  '$dimension-150': number;
  '$dimension-200': number;
  '$dimension-250': number;
  '$dimension-300': number;
  '$dimension-400': number;
  '$dimension-500': number;
  '$dimension-600': number;
  '$dimension-700': number;
  '$dimension-800': number;
  '$dimension-1000': number;
  '$dimension-1200': number;
  '$dimension-1500': number;
  '$dimension-1600': number;
  '$dimension-550': number;
  '$space-component-padding-5xLarge': ReturnType<typeof th>;
  '$space-component-gap-3xLarge': ReturnType<typeof th>;
  '$dimension-900': number;
};

export type BorderWidths = {
  '$border-width-0': string | ThemeGetters;
  '$border-width-100': string | ThemeGetters;
  '$border-width-200': string | ThemeGetters;
  '$border-width-small': string | ThemeGetters;
  '$border-width-focus': string | ThemeGetters;
  '$border-width-medium': string | ThemeGetters;
};

export type BorderStyles = {
  '$border-style-none': string | ThemeGetters;
  '$border-style-solid': string | ThemeGetters;
  '$border-style-dashed': string | ThemeGetters;
};

export type Fonts = {
  '$font-family-primary': string | ThemeGetters;
};

export type FontSizes = {
  '$font-size-125': string | ThemeGetters;
  '$font-size-150': string | ThemeGetters;
  '$font-size-175': string | ThemeGetters;
  '$font-size-200': string | ThemeGetters;
  '$font-size-225': string | ThemeGetters;
  '$font-size-300': string | ThemeGetters;
  '$font-size-400': string | ThemeGetters;
  '$font-size-500': string | ThemeGetters;
  '$font-size-600': string | ThemeGetters;
};

export type FontWeights = {
  '$font-weight-400': string | ThemeGetters;
  '$font-weight-450': string | ThemeGetters;
  '$font-weight-600': string | ThemeGetters;
};

export type LetterSpacings = {
  '$font-letterSpacing-0': string | ThemeGetters;
  '$font-letterSpacing-100': string | ThemeGetters;
  '$font-letterSpacing-200': string | ThemeGetters;
};

export type LineHeights = {
  '$font-lineHeight-scale-100': string | ThemeGetters;
  '$font-lineHeight-scale-150': string | ThemeGetters;
  '$font-lineHeight-scale-166': string | ThemeGetters;
  '$font-lineHeight-scale-200': string | ThemeGetters;
  '$font-lineHeight-value-200': string | ThemeGetters;
  '$font-lineHeight-value-250': string | ThemeGetters;
  '$font-lineHeight-value-300': string | ThemeGetters;
  '$font-lineHeight-value-350': string | ThemeGetters;
  '$font-lineHeight-value-400': string | ThemeGetters;
  '$font-lineHeight-value-450': string | ThemeGetters;
  '$font-lineHeight-value-550': string | ThemeGetters;
  '$font-lineHeight-value-700': string | ThemeGetters;
  '$font-lineHeight-value-800': string | ThemeGetters;
};

export type Texts = {
  '$typo-normal-125': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-150': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-175': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-200': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-225': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-300': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-400': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-500': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-normal-600': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-125': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-150': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-175': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-200': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-225': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-300': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-400': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-500': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-medium-600': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-125': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-150': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-175': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-200': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-225': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-300': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-400': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-500': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-strong-600': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-large': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-medium': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-small': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-xSmall': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-strong-large': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-strong-medium': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-strong-small': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-body-strong-xSmall': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-hero-large': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-hero-medium': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-4xLarge': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-3xLarge': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-xLarge': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-large': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-medium': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
  '$typo-header-small': {
    fontFamily: string | ThemeGetters;
    fontSize: string | ThemeGetters;
    lineHeight: string | ThemeGetters;
    fontWeight: string | ThemeGetters;
    letterSpacing: string | ThemeGetters;
  };
};

export type Shadows = {
  '$elevation-bottom-100': string | ThemeGetters;
  '$elevation-bottom-200': string | ThemeGetters;
  '$elevation-bottom-300': string | ThemeGetters;
  '$elevation-bottom-400': string | ThemeGetters;
  '$elevation-top-100': string | ThemeGetters;
  '$elevation-top-200': string | ThemeGetters;
  '$elevation-top-300': string | ThemeGetters;
  '$elevation-top-400': string | ThemeGetters;
};

export type Opacity = {
  '$opacity-0': string | ThemeGetters;
  '$opacity-50': string | ThemeGetters;
  '$opacity-100': string | ThemeGetters;
  '$opacity-disabled': string | ThemeGetters;
};

export type Screens = {
  _: number;
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  '2xl': number;
};

export type States = {
  _: null;
  motionSafe: string;
  motionReduce: string;
  first: string;
  last: string;
  odd: string;
  even: string;
  visited: string;
  checked: string;
  focusWithin: string;
  hover: string;
  focus: string;
  focusVisible: string;
  active: string;
  placeholder: string;
  disabled: string;
  selected: string;
  loading: string;
  alert: string;
  hoverWithoutButton: string;
  indeterminate: string;
};
