import { th } from "@xstyled/system";
type RefferenceType = ReturnType<typeof th>;
export type Theme = {
    colors: Colors;
    radii: Radii;
    borderWidths: BorderWidths;
    borderStyles: BorderStyles;
    sizes: Sizes;
    space: Space;
    fonts: Fonts;
    fontSizes: FontSizes;
    fontWeights: FontWeights;
    letterSpacings: LetterSpacings;
    lineHeights: LineHeights;
    texts: Texts;
    shadows: Shadows;
    opacity: Opacity;
};
export type CustomTheme = Record<keyof Theme, Record<string, string | ReturnType<typeof th>>>;
export type Colors = {
    "$g-color-coolGrey--4": string | RefferenceType;
    "$g-color-coolGrey--3": string | RefferenceType;
    "$g-color-coolGrey--2": string | RefferenceType;
    "$g-color-coolGrey--1": string | RefferenceType;
    "$g-color-coolGrey-0": string | RefferenceType;
    "$g-color-coolGrey-+1": string | RefferenceType;
    "$g-color-coolGrey-+2": string | RefferenceType;
    "$g-color-coolGrey-+3": string | RefferenceType;
    "$g-color-coolGrey-+4": string | RefferenceType;
    "$g-color-coolGrey-+5": string | RefferenceType;
    "$g-color-coolGrey-+6": string | RefferenceType;
    "$g-color-coolGrey-+7": string | RefferenceType;
    "$g-color-coolGrey-+8": string | RefferenceType;
    "$g-color-coolGreyA--4": string | RefferenceType;
    "$g-color-coolGreyA--3": string | RefferenceType;
    "$g-color-coolGreyA--2": string | RefferenceType;
    "$g-color-coolGreyA--1": string | RefferenceType;
    "$g-color-coolGreyA-0": string | RefferenceType;
    "$g-color-coolGreyA-+1": string | RefferenceType;
    "$g-color-coolGreyA-+2": string | RefferenceType;
    "$g-color-coolGreyA-+3": string | RefferenceType;
    "$g-color-coolGreyA-+4": string | RefferenceType;
    "$g-color-coolGreyA-+5": string | RefferenceType;
    "$g-color-coolGreyA-+6": string | RefferenceType;
    "$g-color-coolGreyA-+7": string | RefferenceType;
    "$g-color-coolGreyA-+8": string | RefferenceType;
    "$g-color-neutralGrey--4": string | RefferenceType;
    "$g-color-neutralGrey--3": string | RefferenceType;
    "$g-color-neutralGrey--2": string | RefferenceType;
    "$g-color-neutralGrey--1": string | RefferenceType;
    "$g-color-neutralGrey-0": string | RefferenceType;
    "$g-color-neutralGrey-+1": string | RefferenceType;
    "$g-color-neutralGrey-+2": string | RefferenceType;
    "$g-color-neutralGrey-+3": string | RefferenceType;
    "$g-color-neutralGrey-+4": string | RefferenceType;
    "$g-color-neutralGrey-+5": string | RefferenceType;
    "$g-color-neutralGrey-+6": string | RefferenceType;
    "$g-color-neutralGrey-+7": string | RefferenceType;
    "$g-color-neutralGrey-+8": string | RefferenceType;
    "$g-color-neutralGreyA--4": string | RefferenceType;
    "$g-color-neutralGreyA--3": string | RefferenceType;
    "$g-color-neutralGreyA--2": string | RefferenceType;
    "$g-color-neutralGreyA--1": string | RefferenceType;
    "$g-color-neutralGreyA-0": string | RefferenceType;
    "$g-color-neutralGreyA-+1": string | RefferenceType;
    "$g-color-neutralGreyA-+2": string | RefferenceType;
    "$g-color-neutralGreyA-+3": string | RefferenceType;
    "$g-color-neutralGreyA-+4": string | RefferenceType;
    "$g-color-neutralGreyA-+5": string | RefferenceType;
    "$g-color-neutralGreyA-+6": string | RefferenceType;
    "$g-color-neutralGreyA-+7": string | RefferenceType;
    "$g-color-neutralGreyA-+8": string | RefferenceType;
    "$g-color-warmGrey--4": string | RefferenceType;
    "$g-color-warmGrey--3": string | RefferenceType;
    "$g-color-warmGrey--2": string | RefferenceType;
    "$g-color-warmGrey--1": string | RefferenceType;
    "$g-color-warmGrey-0": string | RefferenceType;
    "$g-color-warmGrey-+1": string | RefferenceType;
    "$g-color-warmGrey-+2": string | RefferenceType;
    "$g-color-warmGrey-+3": string | RefferenceType;
    "$g-color-warmGrey-+4": string | RefferenceType;
    "$g-color-warmGrey-+5": string | RefferenceType;
    "$g-color-warmGrey-+6": string | RefferenceType;
    "$g-color-warmGrey-+7": string | RefferenceType;
    "$g-color-warmGrey-+8": string | RefferenceType;
    "$g-color-warmGreyA--4": string | RefferenceType;
    "$g-color-warmGreyA--3": string | RefferenceType;
    "$g-color-warmGreyA--2": string | RefferenceType;
    "$g-color-warmGreyA--1": string | RefferenceType;
    "$g-color-warmGreyA-0": string | RefferenceType;
    "$g-color-warmGreyA-+1": string | RefferenceType;
    "$g-color-warmGreyA-+2": string | RefferenceType;
    "$g-color-warmGreyA-+3": string | RefferenceType;
    "$g-color-warmGreyA-+4": string | RefferenceType;
    "$g-color-warmGreyA-+5": string | RefferenceType;
    "$g-color-warmGreyA-+6": string | RefferenceType;
    "$g-color-warmGreyA-+7": string | RefferenceType;
    "$g-color-warmGreyA-+8": string | RefferenceType;
    "$g-color-whiteA--12": string | RefferenceType;
    "$g-color-whiteA--11": string | RefferenceType;
    "$g-color-whiteA--10": string | RefferenceType;
    "$g-color-whiteA--9": string | RefferenceType;
    "$g-color-whiteA--8": string | RefferenceType;
    "$g-color-whiteA--7": string | RefferenceType;
    "$g-color-whiteA--6": string | RefferenceType;
    "$g-color-whiteA--5": string | RefferenceType;
    "$g-color-whiteA--4": string | RefferenceType;
    "$g-color-whiteA--3": string | RefferenceType;
    "$g-color-whiteA--2": string | RefferenceType;
    "$g-color-whiteA--1": string | RefferenceType;
    "$g-color-whiteA-0": string | RefferenceType;
    "$g-color-red--4": string | RefferenceType;
    "$g-color-red--3": string | RefferenceType;
    "$g-color-red--2": string | RefferenceType;
    "$g-color-red--1": string | RefferenceType;
    "$g-color-red-0": string | RefferenceType;
    "$g-color-red-+1": string | RefferenceType;
    "$g-color-red-+2": string | RefferenceType;
    "$g-color-red-+3": string | RefferenceType;
    "$g-color-red-+4": string | RefferenceType;
    "$g-color-red-+5": string | RefferenceType;
    "$g-color-red-+6": string | RefferenceType;
    "$g-color-red-+7": string | RefferenceType;
    "$g-color-red-+8": string | RefferenceType;
    "$g-color-raspberry--4": string | RefferenceType;
    "$g-color-raspberry--3": string | RefferenceType;
    "$g-color-raspberry--2": string | RefferenceType;
    "$g-color-raspberry--1": string | RefferenceType;
    "$g-color-raspberry-0": string | RefferenceType;
    "$g-color-raspberry-+1": string | RefferenceType;
    "$g-color-raspberry-+2": string | RefferenceType;
    "$g-color-raspberry-+3": string | RefferenceType;
    "$g-color-raspberry-+4": string | RefferenceType;
    "$g-color-raspberry-+5": string | RefferenceType;
    "$g-color-raspberry-+6": string | RefferenceType;
    "$g-color-raspberry-+7": string | RefferenceType;
    "$g-color-raspberry-+8": string | RefferenceType;
    "$g-color-magenta--4": string | RefferenceType;
    "$g-color-magenta--3": string | RefferenceType;
    "$g-color-magenta--2": string | RefferenceType;
    "$g-color-magenta--1": string | RefferenceType;
    "$g-color-magenta-0": string | RefferenceType;
    "$g-color-magenta-+1": string | RefferenceType;
    "$g-color-magenta-+2": string | RefferenceType;
    "$g-color-magenta-+3": string | RefferenceType;
    "$g-color-magenta-+4": string | RefferenceType;
    "$g-color-magenta-+5": string | RefferenceType;
    "$g-color-magenta-+6": string | RefferenceType;
    "$g-color-magenta-+7": string | RefferenceType;
    "$g-color-magenta-+8": string | RefferenceType;
    "$g-color-purple--4": string | RefferenceType;
    "$g-color-purple--3": string | RefferenceType;
    "$g-color-purple--2": string | RefferenceType;
    "$g-color-purple--1": string | RefferenceType;
    "$g-color-purple-0": string | RefferenceType;
    "$g-color-purple-+1": string | RefferenceType;
    "$g-color-purple-+2": string | RefferenceType;
    "$g-color-purple-+3": string | RefferenceType;
    "$g-color-purple-+4": string | RefferenceType;
    "$g-color-purple-+5": string | RefferenceType;
    "$g-color-purple-+6": string | RefferenceType;
    "$g-color-purple-+7": string | RefferenceType;
    "$g-color-purple-+8": string | RefferenceType;
    "$g-color-grape--4": string | RefferenceType;
    "$g-color-grape--3": string | RefferenceType;
    "$g-color-grape--2": string | RefferenceType;
    "$g-color-grape--1": string | RefferenceType;
    "$g-color-grape-0": string | RefferenceType;
    "$g-color-grape-+1": string | RefferenceType;
    "$g-color-grape-+2": string | RefferenceType;
    "$g-color-grape-+3": string | RefferenceType;
    "$g-color-grape-+4": string | RefferenceType;
    "$g-color-grape-+5": string | RefferenceType;
    "$g-color-grape-+6": string | RefferenceType;
    "$g-color-grape-+7": string | RefferenceType;
    "$g-color-grape-+8": string | RefferenceType;
    "$g-color-violet--4": string | RefferenceType;
    "$g-color-violet--3": string | RefferenceType;
    "$g-color-violet--2": string | RefferenceType;
    "$g-color-violet--1": string | RefferenceType;
    "$g-color-violet-0": string | RefferenceType;
    "$g-color-violet-+1": string | RefferenceType;
    "$g-color-violet-+2": string | RefferenceType;
    "$g-color-violet-+3": string | RefferenceType;
    "$g-color-violet-+4": string | RefferenceType;
    "$g-color-violet-+5": string | RefferenceType;
    "$g-color-violet-+6": string | RefferenceType;
    "$g-color-violet-+7": string | RefferenceType;
    "$g-color-violet-+8": string | RefferenceType;
    "$g-color-blue--4": string | RefferenceType;
    "$g-color-blue--3": string | RefferenceType;
    "$g-color-blue--2": string | RefferenceType;
    "$g-color-blue--1": string | RefferenceType;
    "$g-color-blue-0": string | RefferenceType;
    "$g-color-blue-+1": string | RefferenceType;
    "$g-color-blue-+2": string | RefferenceType;
    "$g-color-blue-+3": string | RefferenceType;
    "$g-color-blue-+4": string | RefferenceType;
    "$g-color-blue-+5": string | RefferenceType;
    "$g-color-blue-+6": string | RefferenceType;
    "$g-color-blue-+7": string | RefferenceType;
    "$g-color-blue-+8": string | RefferenceType;
    "$g-color-cyan--4": string | RefferenceType;
    "$g-color-cyan--3": string | RefferenceType;
    "$g-color-cyan--2": string | RefferenceType;
    "$g-color-cyan--1": string | RefferenceType;
    "$g-color-cyan-0": string | RefferenceType;
    "$g-color-cyan-+1": string | RefferenceType;
    "$g-color-cyan-+2": string | RefferenceType;
    "$g-color-cyan-+3": string | RefferenceType;
    "$g-color-cyan-+4": string | RefferenceType;
    "$g-color-cyan-+5": string | RefferenceType;
    "$g-color-cyan-+6": string | RefferenceType;
    "$g-color-cyan-+7": string | RefferenceType;
    "$g-color-cyan-+8": string | RefferenceType;
    "$g-color-teal--4": string | RefferenceType;
    "$g-color-teal--3": string | RefferenceType;
    "$g-color-teal--2": string | RefferenceType;
    "$g-color-teal--1": string | RefferenceType;
    "$g-color-teal-0": string | RefferenceType;
    "$g-color-teal-+1": string | RefferenceType;
    "$g-color-teal-+2": string | RefferenceType;
    "$g-color-teal-+3": string | RefferenceType;
    "$g-color-teal-+4": string | RefferenceType;
    "$g-color-teal-+5": string | RefferenceType;
    "$g-color-teal-+6": string | RefferenceType;
    "$g-color-teal-+7": string | RefferenceType;
    "$g-color-teal-+8": string | RefferenceType;
    "$g-color-aquamarine--4": string | RefferenceType;
    "$g-color-aquamarine--3": string | RefferenceType;
    "$g-color-aquamarine--2": string | RefferenceType;
    "$g-color-aquamarine--1": string | RefferenceType;
    "$g-color-aquamarine-0": string | RefferenceType;
    "$g-color-aquamarine-+1": string | RefferenceType;
    "$g-color-aquamarine-+2": string | RefferenceType;
    "$g-color-aquamarine-+3": string | RefferenceType;
    "$g-color-aquamarine-+4": string | RefferenceType;
    "$g-color-aquamarine-+5": string | RefferenceType;
    "$g-color-aquamarine-+6": string | RefferenceType;
    "$g-color-aquamarine-+7": string | RefferenceType;
    "$g-color-aquamarine-+8": string | RefferenceType;
    "$g-color-green--4": string | RefferenceType;
    "$g-color-green--3": string | RefferenceType;
    "$g-color-green--2": string | RefferenceType;
    "$g-color-green--1": string | RefferenceType;
    "$g-color-green-0": string | RefferenceType;
    "$g-color-green-+1": string | RefferenceType;
    "$g-color-green-+2": string | RefferenceType;
    "$g-color-green-+3": string | RefferenceType;
    "$g-color-green-+4": string | RefferenceType;
    "$g-color-green-+5": string | RefferenceType;
    "$g-color-green-+6": string | RefferenceType;
    "$g-color-green-+7": string | RefferenceType;
    "$g-color-green-+8": string | RefferenceType;
    "$g-color-emerald--4": string | RefferenceType;
    "$g-color-emerald--3": string | RefferenceType;
    "$g-color-emerald--2": string | RefferenceType;
    "$g-color-emerald--1": string | RefferenceType;
    "$g-color-emerald-0": string | RefferenceType;
    "$g-color-emerald-+1": string | RefferenceType;
    "$g-color-emerald-+2": string | RefferenceType;
    "$g-color-emerald-+3": string | RefferenceType;
    "$g-color-emerald-+4": string | RefferenceType;
    "$g-color-emerald-+5": string | RefferenceType;
    "$g-color-emerald-+6": string | RefferenceType;
    "$g-color-emerald-+7": string | RefferenceType;
    "$g-color-emerald-+8": string | RefferenceType;
    "$g-color-orange--4": string | RefferenceType;
    "$g-color-orange--3": string | RefferenceType;
    "$g-color-orange--2": string | RefferenceType;
    "$g-color-orange--1": string | RefferenceType;
    "$g-color-orange-0": string | RefferenceType;
    "$g-color-orange-+1": string | RefferenceType;
    "$g-color-orange-+2": string | RefferenceType;
    "$g-color-orange-+3": string | RefferenceType;
    "$g-color-orange-+4": string | RefferenceType;
    "$g-color-orange-+5": string | RefferenceType;
    "$g-color-orange-+6": string | RefferenceType;
    "$g-color-orange-+7": string | RefferenceType;
    "$g-color-orange-+8": string | RefferenceType;
    "$g-color-transparent": string | RefferenceType;
    "$a-color-semantic-brand--4": string | RefferenceType;
    "$a-color-semantic-brand--3": string | RefferenceType;
    "$a-color-semantic-brand--2": string | RefferenceType;
    "$a-color-semantic-brand--1": string | RefferenceType;
    "$a-color-semantic-brand-0": string | RefferenceType;
    "$a-color-semantic-brand-+1": string | RefferenceType;
    "$a-color-semantic-brand-+2": string | RefferenceType;
    "$a-color-semantic-brand-+3": string | RefferenceType;
    "$a-color-semantic-brand-+4": string | RefferenceType;
    "$a-color-semantic-brand-+5": string | RefferenceType;
    "$a-color-semantic-brand-+6": string | RefferenceType;
    "$a-color-semantic-brand-+7": string | RefferenceType;
    "$a-color-semantic-brand-+8": string | RefferenceType;
    "$a-color-semantic-informative--4": string | RefferenceType;
    "$a-color-semantic-informative--3": string | RefferenceType;
    "$a-color-semantic-informative--2": string | RefferenceType;
    "$a-color-semantic-informative--1": string | RefferenceType;
    "$a-color-semantic-informative-0": string | RefferenceType;
    "$a-color-semantic-informative-+1": string | RefferenceType;
    "$a-color-semantic-informative-+2": string | RefferenceType;
    "$a-color-semantic-informative-+3": string | RefferenceType;
    "$a-color-semantic-informative-+4": string | RefferenceType;
    "$a-color-semantic-informative-+5": string | RefferenceType;
    "$a-color-semantic-informative-+6": string | RefferenceType;
    "$a-color-semantic-informative-+7": string | RefferenceType;
    "$a-color-semantic-informative-+8": string | RefferenceType;
    "$a-color-semantic-neutral--4": string | RefferenceType;
    "$a-color-semantic-neutral--3": string | RefferenceType;
    "$a-color-semantic-neutral--2": string | RefferenceType;
    "$a-color-semantic-neutral--1": string | RefferenceType;
    "$a-color-semantic-neutral-0": string | RefferenceType;
    "$a-color-semantic-neutral-+1": string | RefferenceType;
    "$a-color-semantic-neutral-+2": string | RefferenceType;
    "$a-color-semantic-neutral-+3": string | RefferenceType;
    "$a-color-semantic-neutral-+4": string | RefferenceType;
    "$a-color-semantic-neutral-+5": string | RefferenceType;
    "$a-color-semantic-neutral-+6": string | RefferenceType;
    "$a-color-semantic-neutral-+7": string | RefferenceType;
    "$a-color-semantic-neutral-+8": string | RefferenceType;
    "$a-color-semantic-neutralA--4": string | RefferenceType;
    "$a-color-semantic-neutralA--3": string | RefferenceType;
    "$a-color-semantic-neutralA--2": string | RefferenceType;
    "$a-color-semantic-neutralA--1": string | RefferenceType;
    "$a-color-semantic-neutralA-0": string | RefferenceType;
    "$a-color-semantic-neutralA-+1": string | RefferenceType;
    "$a-color-semantic-neutralA-+2": string | RefferenceType;
    "$a-color-semantic-neutralA-+3": string | RefferenceType;
    "$a-color-semantic-neutralA-+4": string | RefferenceType;
    "$a-color-semantic-neutralA-+5": string | RefferenceType;
    "$a-color-semantic-neutralA-+6": string | RefferenceType;
    "$a-color-semantic-neutralA-+7": string | RefferenceType;
    "$a-color-semantic-neutralA-+8": string | RefferenceType;
    "$a-color-semantic-positive--4": string | RefferenceType;
    "$a-color-semantic-positive--3": string | RefferenceType;
    "$a-color-semantic-positive--2": string | RefferenceType;
    "$a-color-semantic-positive--1": string | RefferenceType;
    "$a-color-semantic-positive-0": string | RefferenceType;
    "$a-color-semantic-positive-+1": string | RefferenceType;
    "$a-color-semantic-positive-+2": string | RefferenceType;
    "$a-color-semantic-positive-+3": string | RefferenceType;
    "$a-color-semantic-positive-+4": string | RefferenceType;
    "$a-color-semantic-positive-+5": string | RefferenceType;
    "$a-color-semantic-positive-+6": string | RefferenceType;
    "$a-color-semantic-positive-+7": string | RefferenceType;
    "$a-color-semantic-positive-+8": string | RefferenceType;
    "$a-color-semantic-warning--4": string | RefferenceType;
    "$a-color-semantic-warning--3": string | RefferenceType;
    "$a-color-semantic-warning--2": string | RefferenceType;
    "$a-color-semantic-warning--1": string | RefferenceType;
    "$a-color-semantic-warning-0": string | RefferenceType;
    "$a-color-semantic-warning-+1": string | RefferenceType;
    "$a-color-semantic-warning-+2": string | RefferenceType;
    "$a-color-semantic-warning-+3": string | RefferenceType;
    "$a-color-semantic-warning-+4": string | RefferenceType;
    "$a-color-semantic-warning-+5": string | RefferenceType;
    "$a-color-semantic-warning-+6": string | RefferenceType;
    "$a-color-semantic-warning-+7": string | RefferenceType;
    "$a-color-semantic-warning-+8": string | RefferenceType;
    "$a-color-semantic-negative--4": string | RefferenceType;
    "$a-color-semantic-negative--3": string | RefferenceType;
    "$a-color-semantic-negative--2": string | RefferenceType;
    "$a-color-semantic-negative--1": string | RefferenceType;
    "$a-color-semantic-negative-0": string | RefferenceType;
    "$a-color-semantic-negative-+1": string | RefferenceType;
    "$a-color-semantic-negative-+2": string | RefferenceType;
    "$a-color-semantic-negative-+3": string | RefferenceType;
    "$a-color-semantic-negative-+4": string | RefferenceType;
    "$a-color-semantic-negative-+5": string | RefferenceType;
    "$a-color-semantic-negative-+6": string | RefferenceType;
    "$a-color-semantic-negative-+7": string | RefferenceType;
    "$a-color-semantic-negative-+8": string | RefferenceType;
    "$a-color-content-primary": string | RefferenceType;
    "$a-color-content-secondary": string | RefferenceType;
    "$a-color-content-tertiary": string | RefferenceType;
    "$a-color-content-disabled": string | RefferenceType;
    "$a-color-content-primary-inverted": string | RefferenceType;
    "$a-color-content-secondary-inverted": string | RefferenceType;
    "$a-color-content-tertiary-inverted": string | RefferenceType;
    "$a-color-content-disabled-inverted": string | RefferenceType;
    "$a-color-content-informative": string | RefferenceType;
    "$a-color-content-positive": string | RefferenceType;
    "$a-color-content-warning": string | RefferenceType;
    "$a-color-content-negative": string | RefferenceType;
    "$a-color-content-brand": string | RefferenceType;
    "$a-color-border-neutral": string | RefferenceType;
    "$a-color-border-informative": string | RefferenceType;
    "$a-color-border-positive": string | RefferenceType;
    "$a-color-border-warning": string | RefferenceType;
    "$a-color-border-negative": string | RefferenceType;
    "$a-color-border-brand": string | RefferenceType;
    "$a-color-border-neutral-subtle": string | RefferenceType;
    "$a-color-border-informative-subtle": string | RefferenceType;
    "$a-color-border-positive-subtle": string | RefferenceType;
    "$a-color-border-warning-subtle": string | RefferenceType;
    "$a-color-border-negative-subtle": string | RefferenceType;
    "$a-color-border-brand-subtle": string | RefferenceType;
    "$a-color-border-inverted": string | RefferenceType;
    "$a-color-border-default": string | RefferenceType;
    "$a-color-background-default": string | RefferenceType;
    "$a-color-background-inverted": string | RefferenceType;
    "$a-color-background-neutral": string | RefferenceType;
    "$a-color-background-informative": string | RefferenceType;
    "$a-color-background-positive": string | RefferenceType;
    "$a-color-background-warning": string | RefferenceType;
    "$a-color-background-negative": string | RefferenceType;
    "$a-color-background-brand": string | RefferenceType;
    "$a-color-background-neutral-subtle": string | RefferenceType;
    "$a-color-background-informative-subtle": string | RefferenceType;
    "$a-color-background-positive-subtle": string | RefferenceType;
    "$a-color-background-warning-subtle": string | RefferenceType;
    "$a-color-background-negative-subtle": string | RefferenceType;
    "$a-color-background-brand-subtle": string | RefferenceType;
    "$a-color-background-neutral-surface": string | RefferenceType;
    "$a-color-background-informative-surface": string | RefferenceType;
    "$a-color-background-positive-surface": string | RefferenceType;
    "$a-color-background-warning-surface": string | RefferenceType;
    "$a-color-background-negative-surface": string | RefferenceType;
    "$a-color-background-brand-surface": string | RefferenceType;
    "$a-color-background-dimmer": string | RefferenceType;
    "$a-color-action-primary-normal": string | RefferenceType;
    "$a-color-action-primary-hover": string | RefferenceType;
    "$a-color-action-primary-active": string | RefferenceType;
    "$a-color-action-primary-selected": string | RefferenceType;
    "$a-color-action-primary-subtle-normal": string | RefferenceType;
    "$a-color-action-primary-subtle-hover": string | RefferenceType;
    "$a-color-action-primary-subtle-active": string | RefferenceType;
    "$a-color-action-primary-subtle-selected": string | RefferenceType;
    "$a-color-action-neutral-normal": string | RefferenceType;
    "$a-color-action-neutral-hover": string | RefferenceType;
    "$a-color-action-neutral-active": string | RefferenceType;
    "$a-color-action-neutral-selected": string | RefferenceType;
    "$a-color-action-neutral-subtle-normal": string | RefferenceType;
    "$a-color-action-neutral-subtle-hover": string | RefferenceType;
    "$a-color-action-neutral-subtle-active": string | RefferenceType;
    "$a-color-action-neutral-subtle-selected": string | RefferenceType;
    "$a-color-action-success-normal": string | RefferenceType;
    "$a-color-action-success-hover": string | RefferenceType;
    "$a-color-action-success-active": string | RefferenceType;
    "$a-color-action-success-selected": string | RefferenceType;
    "$a-color-action-success-subtle-normal": string | RefferenceType;
    "$a-color-action-success-subtle-hover": string | RefferenceType;
    "$a-color-action-success-subtle-active": string | RefferenceType;
    "$a-color-action-success-subtle-selected": string | RefferenceType;
    "$a-color-action-destructive-normal": string | RefferenceType;
    "$a-color-action-destructive-hover": string | RefferenceType;
    "$a-color-action-destructive-active": string | RefferenceType;
    "$a-color-action-destructive-selected": string | RefferenceType;
    "$a-color-action-destructive-subtle-normal": string | RefferenceType;
    "$a-color-action-destructive-subtle-hover": string | RefferenceType;
    "$a-color-action-destructive-subtle-active": string | RefferenceType;
    "$a-color-action-destructive-subtle-selected": string | RefferenceType;
    "$a-color-action-ghost-normal": string | RefferenceType;
    "$a-color-action-ghost-hover": string | RefferenceType;
    "$a-color-action-ghost-active": string | RefferenceType;
    "$a-color-action-ghost-selected": string | RefferenceType;
    "$a-color-action-ghost-inverted-hover": string | RefferenceType;
    "$a-color-action-ghost-inverted-active": string | RefferenceType;
    "$a-color-action-ghost-inverted-selected": string | RefferenceType;
    "$a-color-action-ghost-destructive-hover": string | RefferenceType;
    "$a-color-action-ghost-destructive-active": string | RefferenceType;
    "$a-color-action-ghost-destructive-selected": string | RefferenceType;
    "$a-color-action-outline-normal": string | RefferenceType;
    "$a-color-action-outline-hover": string | RefferenceType;
    "$a-color-action-outline-active": string | RefferenceType;
    "$a-color-action-outline-selected": string | RefferenceType;
    "$a-color-action-inverted-normal": string | RefferenceType;
    "$a-color-action-inverted-hover": string | RefferenceType;
    "$a-color-action-inverted-active": string | RefferenceType;
    "$a-color-action-inverted-selected": string | RefferenceType;
    "$a-color-action-reverseInverted-normal": string | RefferenceType;
    "$a-color-action-reverseInverted-hover": string | RefferenceType;
    "$a-color-action-reverseInverted-active": string | RefferenceType;
    "$a-color-action-reverseInverted-selected": string | RefferenceType;
    "$a-color-interaction-default-normal": string | RefferenceType;
    "$a-color-interaction-default-hover": string | RefferenceType;
    "$a-color-interaction-default-active": string | RefferenceType;
    "$a-color-interaction-default-selected": string | RefferenceType;
    "$a-color-interaction-default-subtle-normal": string | RefferenceType;
    "$a-color-interaction-default-subtle-hover": string | RefferenceType;
    "$a-color-interaction-default-subtle-active": string | RefferenceType;
    "$a-color-interaction-default-subtle-selected": string | RefferenceType;
    "$a-color-interaction-neutral-normal": string | RefferenceType;
    "$a-color-interaction-neutral-hover": string | RefferenceType;
    "$a-color-interaction-neutral-active": string | RefferenceType;
    "$a-color-interaction-neutral-selected": string | RefferenceType;
    "$a-color-interaction-neutral-subtle-normal": string | RefferenceType;
    "$a-color-interaction-neutral-subtle-hover": string | RefferenceType;
    "$a-color-interaction-neutral-subtle-active": string | RefferenceType;
    "$a-color-interaction-neutral-subtle-selected": string | RefferenceType;
    "$a-color-interaction-alert-normal": string | RefferenceType;
    "$a-color-interaction-alert-hover": string | RefferenceType;
    "$a-color-interaction-alert-active": string | RefferenceType;
    "$a-color-interaction-alert-selected": string | RefferenceType;
    "$a-color-interaction-alert-subtle-normal": string | RefferenceType;
    "$a-color-interaction-alert-subtle-hover": string | RefferenceType;
    "$a-color-interaction-alert-subtle-active": string | RefferenceType;
    "$a-color-interaction-alert-subtle-selected": string | RefferenceType;
    "$a-color-interaction-ghost-normal": string | RefferenceType;
    "$a-color-interaction-ghost-hover": string | RefferenceType;
    "$a-color-interaction-ghost-active": string | RefferenceType;
    "$a-color-interaction-ghost-selected": string | RefferenceType;
    "$a-color-interaction-ghost-inverted-hover": string | RefferenceType;
    "$a-color-interaction-ghost-inverted-normal": string | RefferenceType;
    "$a-color-interaction-ghost-inverted-selected": string | RefferenceType;
    "$a-color-interaction-ghost-destructive-hover": string | RefferenceType;
    "$a-color-interaction-ghost-destructive-normal": string | RefferenceType;
    "$a-color-interaction-ghost-destructive-selected": string | RefferenceType;
    "$a-color-interaction-disabled-normal": string | RefferenceType;
    "$a-color-interaction-disabled-hover": string | RefferenceType;
    "$a-color-interaction-disabled-active": string | RefferenceType;
    "$a-color-interaction-disabled-subtle-normal": string | RefferenceType;
    "$a-color-interaction-disabled-subtle-hover": string | RefferenceType;
    "$a-color-interaction-disabled-subtle-active": string | RefferenceType;
    "$a-color-interaction-border-normal": string | RefferenceType;
    "$a-color-interaction-border-hover": string | RefferenceType;
    "$a-color-interaction-border-active": string | RefferenceType;
    "$a-color-interaction-border-selected": string | RefferenceType;
    "$a-color-interaction-border-neutral-normal": string | RefferenceType;
    "$a-color-interaction-border-neutral-hover": string | RefferenceType;
    "$a-color-interaction-border-neutral-active": string | RefferenceType;
    "$a-color-interaction-border-neutral-selected": string | RefferenceType;
    "$a-color-interaction-border-alert": string | RefferenceType;
    "$a-color-interaction-background-modal": string | RefferenceType;
    "$a-color-interaction-background-modeless": string | RefferenceType;
    "$a-color-interaction-background-modeless-inverted": string | RefferenceType;
    "$a-color-interaction-background-sidepanel": string | RefferenceType;
    "$a-color-interaction-background-formField": string | RefferenceType;
    "$a-color-interaction-inverted-normal": string | RefferenceType;
    "$a-color-interaction-inverted-hover": string | RefferenceType;
    "$a-color-interaction-inverted-active": string | RefferenceType;
    "$a-color-interaction-inverted-selected": string | RefferenceType;
    "$a-color-interaction-focus-default": string | RefferenceType;
    "$a-color-nonContextual-grey-onMuted": string | RefferenceType;
    "$a-color-nonContextual-grey-default": string | RefferenceType;
    "$a-color-nonContextual-grey-muted": string | RefferenceType;
    "$a-color-nonContextual-grey-subtle": string | RefferenceType;
    "$a-color-nonContextual-grey-surface": string | RefferenceType;
    "$a-color-nonContextual-red-onMuted": string | RefferenceType;
    "$a-color-nonContextual-red-default": string | RefferenceType;
    "$a-color-nonContextual-red-muted": string | RefferenceType;
    "$a-color-nonContextual-red-subtle": string | RefferenceType;
    "$a-color-nonContextual-red-surface": string | RefferenceType;
    "$a-color-nonContextual-raspberry-onMuted": string | RefferenceType;
    "$a-color-nonContextual-raspberry-default": string | RefferenceType;
    "$a-color-nonContextual-raspberry-muted": string | RefferenceType;
    "$a-color-nonContextual-raspberry-subtle": string | RefferenceType;
    "$a-color-nonContextual-raspberry-surface": string | RefferenceType;
    "$a-color-nonContextual-magenta-onMuted": string | RefferenceType;
    "$a-color-nonContextual-magenta-default": string | RefferenceType;
    "$a-color-nonContextual-magenta-muted": string | RefferenceType;
    "$a-color-nonContextual-magenta-subtle": string | RefferenceType;
    "$a-color-nonContextual-magenta-surface": string | RefferenceType;
    "$a-color-nonContextual-purple-onMuted": string | RefferenceType;
    "$a-color-nonContextual-purple-default": string | RefferenceType;
    "$a-color-nonContextual-purple-muted": string | RefferenceType;
    "$a-color-nonContextual-purple-subtle": string | RefferenceType;
    "$a-color-nonContextual-purple-surface": string | RefferenceType;
    "$a-color-nonContextual-grape-onMuted": string | RefferenceType;
    "$a-color-nonContextual-grape-default": string | RefferenceType;
    "$a-color-nonContextual-grape-muted": string | RefferenceType;
    "$a-color-nonContextual-grape-subtle": string | RefferenceType;
    "$a-color-nonContextual-grape-surface": string | RefferenceType;
    "$a-color-nonContextual-violet-onMuted": string | RefferenceType;
    "$a-color-nonContextual-violet-default": string | RefferenceType;
    "$a-color-nonContextual-violet-muted": string | RefferenceType;
    "$a-color-nonContextual-violet-subtle": string | RefferenceType;
    "$a-color-nonContextual-violet-surface": string | RefferenceType;
    "$a-color-nonContextual-blue-onMuted": string | RefferenceType;
    "$a-color-nonContextual-blue-default": string | RefferenceType;
    "$a-color-nonContextual-blue-muted": string | RefferenceType;
    "$a-color-nonContextual-blue-subtle": string | RefferenceType;
    "$a-color-nonContextual-blue-surface": string | RefferenceType;
    "$a-color-nonContextual-cyan-onMuted": string | RefferenceType;
    "$a-color-nonContextual-cyan-default": string | RefferenceType;
    "$a-color-nonContextual-cyan-muted": string | RefferenceType;
    "$a-color-nonContextual-cyan-subtle": string | RefferenceType;
    "$a-color-nonContextual-cyan-surface": string | RefferenceType;
    "$a-color-nonContextual-teal-onMuted": string | RefferenceType;
    "$a-color-nonContextual-teal-default": string | RefferenceType;
    "$a-color-nonContextual-teal-muted": string | RefferenceType;
    "$a-color-nonContextual-teal-subtle": string | RefferenceType;
    "$a-color-nonContextual-teal-surface": string | RefferenceType;
    "$a-color-nonContextual-aquamarine-onMuted": string | RefferenceType;
    "$a-color-nonContextual-aquamarine-default": string | RefferenceType;
    "$a-color-nonContextual-aquamarine-muted": string | RefferenceType;
    "$a-color-nonContextual-aquamarine-subtle": string | RefferenceType;
    "$a-color-nonContextual-aquamarine-surface": string | RefferenceType;
    "$a-color-nonContextual-green-onMuted": string | RefferenceType;
    "$a-color-nonContextual-green-default": string | RefferenceType;
    "$a-color-nonContextual-green-muted": string | RefferenceType;
    "$a-color-nonContextual-green-subtle": string | RefferenceType;
    "$a-color-nonContextual-green-surface": string | RefferenceType;
    "$a-color-nonContextual-emerald-onMuted": string | RefferenceType;
    "$a-color-nonContextual-emerald-default": string | RefferenceType;
    "$a-color-nonContextual-emerald-muted": string | RefferenceType;
    "$a-color-nonContextual-emerald-subtle": string | RefferenceType;
    "$a-color-nonContextual-emerald-surface": string | RefferenceType;
    "$a-color-border-defaultA": string | RefferenceType;
    "$a-color-nonContextual-orange-onMuted": string | RefferenceType;
    "$a-color-nonContextual-orange-default": string | RefferenceType;
    "$a-color-nonContextual-orange-muted": string | RefferenceType;
    "$a-color-nonContextual-orange-subtle": string | RefferenceType;
    "$a-color-nonContextual-orange-surface": string | RefferenceType;
};
export type Radii = {
    "$g-border-radius-0": string | RefferenceType;
    "$g-border-radius-100": string | RefferenceType;
    "$g-border-radius-200": string | RefferenceType;
    "$g-border-radius-300": string | RefferenceType;
    "$g-border-radius-full": string | RefferenceType;
    "$a-border-radius-small": string | RefferenceType;
    "$a-border-radius-medium": string | RefferenceType;
    "$a-border-radius-large": string | RefferenceType;
};
export type BorderWidths = {
    "$g-border-width-0": string | RefferenceType;
    "$g-border-width-100": string | RefferenceType;
    "$g-border-width-200": string | RefferenceType;
    "$a-border-width-small": string | RefferenceType;
    "$a-border-width-focus": string | RefferenceType;
    "$a-border-width-medium": string | RefferenceType;
};
export type BorderStyles = {
    "$g-border-style-none": string | RefferenceType;
    "$g-border-style-solid": string | RefferenceType;
    "$g-border-style-dashed": string | RefferenceType;
};
export type Sizes = {
    "$g-size-0": string | RefferenceType;
    "$g-size-25": string | RefferenceType;
    "$g-size-50": string | RefferenceType;
    "$g-size-100": string | RefferenceType;
    "$g-size-150": string | RefferenceType;
    "$g-size-200": string | RefferenceType;
    "$g-size-250": string | RefferenceType;
    "$g-size-300": string | RefferenceType;
    "$g-size-350": string | RefferenceType;
};
export type Space = {
    "$g-space-0": string | RefferenceType;
    "$g-space-25": string | RefferenceType;
    "$g-space-50": string | RefferenceType;
    "$g-space-75": string | RefferenceType;
    "$g-space-100": string | RefferenceType;
    "$g-space-150": string | RefferenceType;
    "$g-space-200": string | RefferenceType;
    "$g-space-300": string | RefferenceType;
    "$g-space-400": string | RefferenceType;
    "$g-space-500": string | RefferenceType;
    "$g-space-125": string | RefferenceType;
    "$g-space-175": string | RefferenceType;
    "$a-space-component-gap-xSmall": string | RefferenceType;
    "$a-space-component-gap-small": string | RefferenceType;
    "$a-space-component-gap-medium": string | RefferenceType;
    "$a-space-component-gap-large": string | RefferenceType;
    "$a-space-component-gap-xLarge": string | RefferenceType;
    "$a-space-component-gap-2xLarge": string | RefferenceType;
    "$a-space-component-gap-3xLarge": string | RefferenceType;
    "$a-space-component-padding-xSmall": string | RefferenceType;
    "$a-space-component-padding-small": string | RefferenceType;
    "$a-space-component-padding-medium": string | RefferenceType;
    "$a-space-component-padding-large": string | RefferenceType;
    "$a-space-component-padding-xLarge": string | RefferenceType;
    "$a-space-component-padding-2xLarge": string | RefferenceType;
    "$a-space-component-padding-3xLarge": string | RefferenceType;
    "$a-space-component-padding-4xLarge": string | RefferenceType;
};
export type Fonts = {
    "$g-font-family-primary": string | RefferenceType;
};
export type FontSizes = {
    "$g-font-size-25": string | RefferenceType;
    "$g-font-size-50": string | RefferenceType;
    "$g-font-size-75": string | RefferenceType;
    "$g-font-size-100": string | RefferenceType;
    "$g-font-size-200": string | RefferenceType;
    "$g-font-size-300": string | RefferenceType;
    "$g-font-size-400": string | RefferenceType;
    "$g-font-size-500": string | RefferenceType;
    "$g-font-size-600": string | RefferenceType;
};
export type FontWeights = {
    "$g-font-weight-400": string | RefferenceType;
    "$g-font-weight-450": string | RefferenceType;
    "$g-font-weight-600": string | RefferenceType;
};
export type LetterSpacings = {
    "$g-font-letterSpacing-0": string | RefferenceType;
    "$g-font-letterSpacing-100": string | RefferenceType;
    "$g-font-letterSpacing-200": string | RefferenceType;
};
export type LineHeights = {
    "$g-font-lineHeight-scale-100": string | RefferenceType;
    "$g-font-lineHeight-scale-150": string | RefferenceType;
    "$g-font-lineHeight-scale-166": string | RefferenceType;
    "$g-font-lineHeight-scale-200": string | RefferenceType;
    "$g-font-lineHeight-value-100": string | RefferenceType;
    "$g-font-lineHeight-value-150": string | RefferenceType;
    "$g-font-lineHeight-value-200": string | RefferenceType;
    "$g-font-lineHeight-value-250": string | RefferenceType;
    "$g-font-lineHeight-value-300": string | RefferenceType;
    "$g-font-lineHeight-value-350": string | RefferenceType;
    "$g-font-lineHeight-value-450": string | RefferenceType;
    "$g-font-lineHeight-value-600": string | RefferenceType;
    "$g-font-lineHeight-value-700": string | RefferenceType;
};
export type Texts = {
    "$g-typo-normal-25": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-50": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-75": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-100": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-200": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-300": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-400": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-500": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-normal-600": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-25": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-50": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-75": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-100": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-200": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-300": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-400": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-500": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-medium-600": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-25": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-50": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-75": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-100": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-200": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-300": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-400": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-500": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$g-typo-strong-600": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-large": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-medium": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-small": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-xSmall": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-strong-large": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-strong-medium": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-strong-small": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-body-strong-xSmall": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-hero-large": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-hero-medium": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-4xLarge": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-3xLarge": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-xLarge": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-large": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-medium": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
    "$a-typo-header-small": {
        fontFamily: string | RefferenceType;
        fontSize: string | RefferenceType;
        lineHeight: string | RefferenceType;
        fontWeight: string | RefferenceType;
        letterSpacing: string | RefferenceType;
    };
};
export type Shadows = {
    "$g-elevation-bottom-100": string | RefferenceType;
    "$g-elevation-bottom-200": string | RefferenceType;
    "$g-elevation-bottom-300": string | RefferenceType;
    "$g-elevation-bottom-400": string | RefferenceType;
    "$g-elevation-top-100": string | RefferenceType;
    "$g-elevation-top-200": string | RefferenceType;
    "$g-elevation-top-300": string | RefferenceType;
    "$g-elevation-top-400": string | RefferenceType;
};
export type Opacity = {
    "$g-opacity-0": string | RefferenceType;
    "$g-opacity-50": string | RefferenceType;
    "$g-opacity-100": string | RefferenceType;
    "$a-opacity-disabled": string | RefferenceType;
};
export {};
