import { th } from '@xstyled/styled-components';

import { Theme } from './Theme.interface';

export const theme: Theme = {
  colors: {
    'coolGrey--4': 'hsla(208, 24%, 14%, 1)',
    'coolGrey--3': 'hsla(208, 15%, 18%, 1)',
    'coolGrey--2': 'hsla(210, 12%, 26%, 1)',
    'coolGrey--1': 'hsla(210, 12%, 33%, 1)',
    'coolGrey-0': 'hsla(215, 12%, 38%, 1)',
    'coolGrey-+1': 'hsla(211, 12%, 55%, 1)',
    'coolGrey-+2': 'hsla(211, 12%, 66%, 1)',
    'coolGrey-+3': 'hsla(210, 17%, 84%, 1)',
    'coolGrey-+4': 'hsla(207, 16%, 89%, 1)',
    'coolGrey-+5': 'hsla(210, 16%, 93%, 1)',
    'coolGrey-+6': 'hsla(204, 20%, 95%, 1)',
    'coolGrey-+7': 'hsla(210, 25%, 97%, 1)',
    'coolGrey-+8': 'hsla(210, 33%, 99%, 1)',
    'coolGreyA--4': 'hsla(207, 47%, 7%, 0.93)',
    'coolGreyA--3': 'hsla(208, 43%, 7%, 0.88)',
    'coolGreyA--2': 'hsla(212, 27%, 14%, 0.86)',
    'coolGreyA--1': 'hsla(211, 30%, 16%, 0.8)',
    'coolGreyA-0': 'hsla(215, 40%, 16%, 0.74)',
    'coolGreyA-+1': 'hsla(210, 50%, 19%, 0.56)',
    'coolGreyA-+2': 'hsla(211, 66%, 15%, 0.4)',
    'coolGreyA-+3': 'hsla(212, 68%, 20%, 0.2)',
    'coolGreyA-+4': 'hsla(205, 89%, 14%, 0.13)',
    'coolGreyA-+5': 'hsla(214, 64%, 17%, 0.09)',
    'coolGreyA-+6': 'hsla(206, 95%, 16%, 0.06)',
    'coolGreyA-+7': 'hsla(213, 100%, 18%, 0.04)',
    'coolGreyA-+8': 'hsla(216, 67%, 37%, 0.02)',
    'neutralGrey--4': 'hsla(0, 0%, 13%, 1)',
    'neutralGrey--3': 'hsla(0, 0%, 18%, 1)',
    'neutralGrey--2': 'hsla(0, 0%, 25%, 1)',
    'neutralGrey--1': 'hsla(0, 0%, 32%, 1)',
    'neutralGrey-0': 'hsla(0, 0%, 37%, 1)',
    'neutralGrey-+1': 'hsla(0, 0%, 54%, 1)',
    'neutralGrey-+2': 'hsla(0, 0%, 65%, 1)',
    'neutralGrey-+3': 'hsla(0, 0%, 84%, 1)',
    'neutralGrey-+4': 'hsla(0, 0%, 89%, 1)',
    'neutralGrey-+5': 'hsla(0, 0%, 92%, 1)',
    'neutralGrey-+6': 'hsla(0, 0%, 95%, 1)',
    'neutralGrey-+7': 'hsla(0, 0%, 97%, 1)',
    'neutralGrey-+8': 'hsla(0, 0%, 99%, 1)',
    'neutralGreyA--4': 'hsla(0, 0%, 7%, 0.93)',
    'neutralGreyA--3': 'hsla(0, 0%, 6%, 0.88)',
    'neutralGreyA--2': 'hsla(0, 0%, 13%, 0.86)',
    'neutralGreyA--1': 'hsla(0, 0%, 15%, 0.8)',
    'neutralGreyA-0': 'hsla(240, 1%, 15%, 0.74)',
    'neutralGreyA-+1': 'hsla(0, 0%, 17%, 0.56)',
    'neutralGreyA-+2': 'hsla(0, 0%, 13%, 0.4)',
    'neutralGreyA-+3': 'hsla(0, 0%, 18%, 0.2)',
    'neutralGreyA-+4': 'hsla(0, 0%, 12%, 0.13)',
    'neutralGreyA-+5': 'hsla(0, 0%, 11%, 0.09)',
    'neutralGreyA-+6': 'hsla(0, 0%, 13%, 0.06)',
    'neutralGreyA-+7': 'hsla(0, 0%, 18%, 0.04)',
    'neutralGreyA-+8': 'hsla(0, 0%, 32%, 0.02)',
    'warmGrey--4': 'hsla(60, 4%, 13%, 1)',
    'warmGrey--3': 'hsla(60, 4%, 18%, 1)',
    'warmGrey--2': 'hsla(60, 5%, 24%, 1)',
    'warmGrey--1': 'hsla(60, 4%, 31%, 1)',
    'warmGrey-0': 'hsla(60, 4%, 36%, 1)',
    'warmGrey-+1': 'hsla(60, 3%, 53%, 1)',
    'warmGrey-+2': 'hsla(60, 5%, 64%, 1)',
    'warmGrey-+3': 'hsla(60, 8%, 84%, 1)',
    'warmGrey-+4': 'hsla(60, 8%, 89%, 1)',
    'warmGrey-+5': 'hsla(60, 9%, 91%, 1)',
    'warmGrey-+6': 'hsla(60, 6%, 95%, 1)',
    'warmGrey-+7': 'hsla(60, 6%, 97%, 1)',
    'warmGrey-+8': 'hsla(60, 4%, 99%, 1)',
    'warmGreyA--4': 'hsla(60, 6%, 7%, 0.93)',
    'warmGreyA--3': 'hsla(60, 15%, 6%, 0.88)',
    'warmGreyA--2': 'hsla(60, 12%, 12%, 0.86)',
    'warmGreyA--1': 'hsla(60, 10%, 14%, 0.8)',
    'warmGreyA-0': 'hsla(60, 15%, 13%, 0.74)',
    'warmGreyA-+1': 'hsla(60, 15%, 16%, 0.56)',
    'warmGreyA-+2': 'hsla(60, 41%, 11%, 0.4)',
    'warmGreyA-+3': 'hsla(60, 36%, 18%, 0.2)',
    'warmGreyA-+4': 'hsla(60, 43%, 14%, 0.13)',
    'warmGreyA-+5': 'hsla(60, 89%, 7%, 0.09)',
    'warmGreyA-+6': 'hsla(60, 54%, 12%, 0.06)',
    'warmGreyA-+7': 'hsla(60, 3%, 18%, 0.04)',
    'warmGreyA-+8': 'hsla(0, 0%, 32%, 0.02)',
    'whiteA--12': 'hsla(0, 0%, 100%, 0.02)',
    'whiteA--11': 'hsla(0, 0%, 100%, 0.03)',
    'whiteA--10': 'hsla(0, 0%, 100%, 0.05)',
    'whiteA--9': 'hsla(0, 0%, 100%, 0.08)',
    'whiteA--8': 'hsla(0, 0%, 100%, 0.1)',
    'whiteA--7': 'hsla(0, 0%, 100%, 0.12)',
    'whiteA--6': 'hsla(0, 0%, 100%, 0.24)',
    'whiteA--5': 'hsla(0, 0%, 100%, 0.4)',
    'whiteA--4': 'hsla(0, 0%, 100%, 0.64)',
    'whiteA--3': 'hsla(0, 0%, 100%, 0.68)',
    'whiteA--2': 'hsla(0, 0%, 100%, 0.72)',
    'whiteA--1': 'hsla(0, 0%, 100%, 0.82)',
    'whiteA-0': 'hsla(0, 0%, 100%, 1)',
    'red--4': 'hsla(0, 70%, 17%, 1)',
    'red--3': 'hsla(0, 55%, 28%, 1)',
    'red--2': 'hsla(0, 54%, 38%, 1)',
    'red--1': 'hsla(0, 50%, 42%, 1)',
    'red-0': 'hsla(0, 58%, 49%, 1)',
    'red-+1': 'hsla(0, 85%, 67%, 1)',
    'red-+2': 'hsla(0, 82%, 76%, 1)',
    'red-+3': 'hsla(0, 88%, 90%, 1)',
    'red-+4': 'hsla(0, 85%, 92%, 1)',
    'red-+5': 'hsla(0, 92%, 95%, 1)',
    'red-+6': 'hsla(0, 100%, 96%, 1)',
    'red-+7': 'hsla(0, 88%, 98%, 1)',
    'red-+8': 'hsla(0, 100%, 99%, 1)',
    'raspberry--4': 'hsla(340, 70%, 16%, 1)',
    'raspberry--3': 'hsla(340, 55%, 26%, 1)',
    'raspberry--2': 'hsla(340, 54%, 37%, 1)',
    'raspberry--1': 'hsla(340, 50%, 41%, 1)',
    'raspberry-0': 'hsla(340, 60%, 47%, 1)',
    'raspberry-+1': 'hsla(340, 71%, 64%, 1)',
    'raspberry-+2': 'hsla(340, 71%, 74%, 1)',
    'raspberry-+3': 'hsla(340, 75%, 89%, 1)',
    'raspberry-+4': 'hsla(339, 83%, 91%, 1)',
    'raspberry-+5': 'hsla(342, 87%, 94%, 1)',
    'raspberry-+6': 'hsla(341, 80%, 96%, 1)',
    'raspberry-+7': 'hsla(340, 82%, 98%, 1)',
    'raspberry-+8': 'hsla(336, 100%, 99%, 1)',
    'magenta--4': 'hsla(320, 71%, 15%, 1)',
    'magenta--3': 'hsla(321, 55%, 26%, 1)',
    'magenta--2': 'hsla(320, 54%, 35%, 1)',
    'magenta--1': 'hsla(320, 50%, 39%, 1)',
    'magenta-0': 'hsla(320, 58%, 44%, 1)',
    'magenta-+1': 'hsla(320, 66%, 62%, 1)',
    'magenta-+2': 'hsla(320, 72%, 73%, 1)',
    'magenta-+3': 'hsla(320, 74%, 88%, 1)',
    'magenta-+4': 'hsla(321, 83%, 91%, 1)',
    'magenta-+5': 'hsla(321, 87%, 94%, 1)',
    'magenta-+6': 'hsla(319, 80%, 96%, 1)',
    'magenta-+7': 'hsla(320, 82%, 98%, 1)',
    'magenta-+8': 'hsla(324, 100%, 99%, 1)',
    'purple--4': 'hsla(320, 71%, 15%, 1)',
    'purple--3': 'hsla(290, 55%, 26%, 1)',
    'purple--2': 'hsla(290, 54%, 35%, 1)',
    'purple--1': 'hsla(290, 50%, 39%, 1)',
    'purple-0': 'hsla(290, 50%, 45%, 1)',
    'purple-+1': 'hsla(288, 62%, 63%, 1)',
    'purple-+2': 'hsla(288, 71%, 74%, 1)',
    'purple-+3': 'hsla(296, 74%, 88%, 1)',
    'purple-+4': 'hsla(291, 83%, 91%, 1)',
    'purple-+5': 'hsla(288, 87%, 94%, 1)',
    'purple-+6': 'hsla(289, 80%, 96%, 1)',
    'purple-+7': 'hsla(288, 100%, 98%, 1)',
    'purple-+8': 'hsla(288, 100%, 99%, 1)',
    'grape--4': 'hsla(270, 70%, 18%, 1)',
    'grape--3': 'hsla(270, 56%, 30%, 1)',
    'grape--2': 'hsla(270, 54%, 40%, 1)',
    'grape--1': 'hsla(270, 50%, 45%, 1)',
    'grape-0': 'hsla(270, 50%, 50%, 1)',
    'grape-+1': 'hsla(270, 74%, 68%, 1)',
    'grape-+2': 'hsla(270, 81%, 77%, 1)',
    'grape-+3': 'hsla(269, 84%, 90%, 1)',
    'grape-+4': 'hsla(270, 100%, 93%, 1)',
    'grape-+5': 'hsla(270, 100%, 95%, 1)',
    'grape-+6': 'hsla(264, 100%, 97%, 1)',
    'grape-+7': 'hsla(270, 100%, 98%, 1)',
    'grape-+8': 'hsla(264, 100%, 99%, 1)',
    'violet--4': 'hsla(250, 69%, 23%, 1)',
    'violet--3': 'hsla(250, 55%, 35%, 1)',
    'violet--2': 'hsla(250, 54%, 48%, 1)',
    'violet--1': 'hsla(250, 60%, 53%, 1)',
    'violet-0': 'hsla(250, 54%, 55%, 1)',
    'violet-+1': 'hsla(250, 80%, 72%, 1)',
    'violet-+2': 'hsla(246, 92%, 81%, 1)',
    'violet-+3': 'hsla(249, 100%, 92%, 1)',
    'violet-+4': 'hsla(246, 100%, 94%, 1)',
    'violet-+5': 'hsla(249, 100%, 96%, 1)',
    'violet-+6': 'hsla(252, 100%, 97%, 1)',
    'violet-+7': 'hsla(252, 100%, 98%, 1)',
    'violet-+8': 'hsla(252, 100%, 99%, 1)',
    'blue--4': 'hsla(222, 91%, 19%, 1)',
    'blue--3': 'hsla(222, 80%, 33%, 1)',
    'blue--2': 'hsla(222, 73%, 44%, 1)',
    'blue--1': 'hsla(222, 68%, 48%, 1)',
    'blue-0': 'hsla(222, 66%, 51%, 1)',
    'blue-+1': 'hsla(222, 87%, 68%, 1)',
    'blue-+2': 'hsla(221, 93%, 77%, 1)',
    'blue-+3': 'hsla(221, 100%, 90%, 1)',
    'blue-+4': 'hsla(221, 100%, 92%, 1)',
    'blue-+5': 'hsla(220, 100%, 95%, 1)',
    'blue-+6': 'hsla(223, 100%, 96%, 1)',
    'blue-+7': 'hsla(223, 100%, 98%, 1)',
    'blue-+8': 'hsla(227, 100%, 99%, 1)',
    'cyan--4': 'hsla(205, 100%, 13%, 1)',
    'cyan--3': 'hsla(205, 80%, 24%, 1)',
    'cyan--2': 'hsla(205, 73%, 32%, 1)',
    'cyan--1': 'hsla(205, 71%, 36%, 1)',
    'cyan-0': 'hsla(205, 92%, 38%, 1)',
    'cyan-+1': 'hsla(210, 66%, 60%, 1)',
    'cyan-+2': 'hsla(208, 87%, 72%, 1)',
    'cyan-+3': 'hsla(208, 100%, 88%, 1)',
    'cyan-+4': 'hsla(208, 100%, 90%, 1)',
    'cyan-+5': 'hsla(207, 100%, 94%, 1)',
    'cyan-+6': 'hsla(210, 100%, 96%, 1)',
    'cyan-+7': 'hsla(204, 100%, 97%, 1)',
    'cyan-+8': 'hsla(204, 100%, 99%, 1)',
    'teal--4': 'hsla(194, 96%, 11%, 1)',
    'teal--3': 'hsla(194, 80%, 20%, 1)',
    'teal--2': 'hsla(194, 65%, 28%, 1)',
    'teal--1': 'hsla(194, 68%, 31%, 1)',
    'teal-0': 'hsla(194, 91%, 31%, 1)',
    'teal-+1': 'hsla(196, 44%, 52%, 1)',
    'teal-+2': 'hsla(197, 58%, 67%, 1)',
    'teal-+3': 'hsla(193, 75%, 84%, 1)',
    'teal-+4': 'hsla(193, 76%, 87%, 1)',
    'teal-+5': 'hsla(196, 72%, 93%, 1)',
    'teal-+6': 'hsla(195, 77%, 95%, 1)',
    'teal-+7': 'hsla(196, 100%, 97%, 1)',
    'teal-+8': 'hsla(192, 100%, 99%, 1)',
    'aquamarine--4': 'hsla(170, 96%, 9%, 1)',
    'aquamarine--3': 'hsla(172, 70%, 17%, 1)',
    'aquamarine--2': 'hsla(172, 66%, 24%, 1)',
    'aquamarine--1': 'hsla(170, 62%, 27%, 1)',
    'aquamarine-0': 'hsla(170, 86%, 26%, 1)',
    'aquamarine-+1': 'hsla(172, 46%, 44%, 1)',
    'aquamarine-+2': 'hsla(173, 46%, 61%, 1)',
    'aquamarine-+3': 'hsla(173, 49%, 83%, 1)',
    'aquamarine-+4': 'hsla(172, 63%, 86%, 1)',
    'aquamarine-+5': 'hsla(174, 61%, 91%, 1)',
    'aquamarine-+6': 'hsla(172, 61%, 93%, 1)',
    'aquamarine-+7': 'hsla(174, 50%, 96%, 1)',
    'aquamarine-+8': 'hsla(180, 60%, 99%, 1)',
    'green--4': 'hsla(152, 76%, 10%, 1)',
    'green--3': 'hsla(152, 70%, 18%, 1)',
    'green--2': 'hsla(152, 61%, 25%, 1)',
    'green--1': 'hsla(152, 58%, 28%, 1)',
    'green-0': 'hsla(150, 62%, 30%, 1)',
    'green-+1': 'hsla(150, 38%, 47%, 1)',
    'green-+2': 'hsla(148, 46%, 63%, 1)',
    'green-+3': 'hsla(148, 51%, 84%, 1)',
    'green-+4': 'hsla(148, 61%, 86%, 1)',
    'green-+5': 'hsla(148, 70%, 91%, 1)',
    'green-+6': 'hsla(148, 61%, 94%, 1)',
    'green-+7': 'hsla(146, 47%, 97%, 1)',
    'green-+8': 'hsla(140, 60%, 99%, 1)',
    'emerald--4': 'hsla(122, 64%, 11%, 1)',
    'emerald--3': 'hsla(122, 63%, 20%, 1)',
    'emerald--2': 'hsla(122, 48%, 27%, 1)',
    'emerald--1': 'hsla(120, 41%, 31%, 1)',
    'emerald-0': 'hsla(120, 38%, 33%, 1)',
    'emerald-+1': 'hsla(120, 32%, 49%, 1)',
    'emerald-+2': 'hsla(120, 38%, 66%, 1)',
    'emerald-+3': 'hsla(120, 50%, 85%, 1)',
    'emerald-+4': 'hsla(120, 57%, 88%, 1)',
    'emerald-+5': 'hsla(120, 56%, 92%, 1)',
    'emerald-+6': 'hsla(120, 61%, 94%, 1)',
    'emerald-+7': 'hsla(120, 47%, 97%, 1)',
    'emerald-+8': 'hsla(120, 60%, 99%, 1)',
    'orange--4': 'hsla(30, 78%, 16%, 1)',
    'orange--3': 'hsla(30, 77%, 27%, 1)',
    'orange--2': 'hsla(29, 70%, 37%, 1)',
    'orange--1': 'hsla(30, 86%, 38%, 1)',
    'orange-0': 'hsla(30, 90%, 59%, 1)',
    'orange-+1': 'hsla(30, 90%, 64%, 1)',
    'orange-+2': 'hsla(30, 99%, 72%, 1)',
    'orange-+3': 'hsla(30, 100%, 83%, 1)',
    'orange-+4': 'hsla(30, 91%, 87%, 1)',
    'orange-+5': 'hsla(30, 100%, 91%, 1)',
    'orange-+6': 'hsla(31, 100%, 94%, 1)',
    'orange-+7': 'hsla(30, 100%, 96%, 1)',
    'orange-+8': 'hsla(24, 100%, 99%, 1)',
    transparent: 'hsla(0, 0%, 100%, 0)',
    'semantic-brand--4': th.color('blue--4'),
    'semantic-brand--3': th.color('blue--3'),
    'semantic-brand--2': th.color('blue--2'),
    'semantic-brand--1': th.color('blue--1'),
    'semantic-brand-0': th.color('blue-0'),
    'semantic-brand-+1': th.color('blue-+1'),
    'semantic-brand-+2': th.color('blue-+2'),
    'semantic-brand-+3': th.color('blue-+3'),
    'semantic-brand-+4': th.color('blue-+4'),
    'semantic-brand-+5': th.color('blue-+5'),
    'semantic-brand-+6': th.color('blue-+6'),
    'semantic-brand-+7': th.color('blue-+7'),
    'semantic-brand-+8': th.color('blue-+8'),
    'semantic-informative--4': th.color('blue--4'),
    'semantic-informative--3': th.color('blue--3'),
    'semantic-informative--2': th.color('blue--2'),
    'semantic-informative--1': th.color('blue--1'),
    'semantic-informative-0': th.color('blue-0'),
    'semantic-informative-+1': th.color('blue-+1'),
    'semantic-informative-+2': th.color('blue-+2'),
    'semantic-informative-+3': th.color('blue-+3'),
    'semantic-informative-+4': th.color('blue-+4'),
    'semantic-informative-+5': th.color('blue-+5'),
    'semantic-informative-+6': th.color('blue-+6'),
    'semantic-informative-+7': th.color('blue-+7'),
    'semantic-informative-+8': th.color('blue-+8'),
    'semantic-neutral--4': th.color('coolGrey--4'),
    'semantic-neutral--3': th.color('coolGrey--3'),
    'semantic-neutral--2': th.color('coolGrey--2'),
    'semantic-neutral--1': th.color('coolGrey--1'),
    'semantic-neutral-0': th.color('coolGrey-0'),
    'semantic-neutral-+1': th.color('coolGrey-+1'),
    'semantic-neutral-+2': th.color('coolGrey-+2'),
    'semantic-neutral-+3': th.color('coolGrey-+3'),
    'semantic-neutral-+4': th.color('coolGrey-+4'),
    'semantic-neutral-+5': th.color('coolGrey-+5'),
    'semantic-neutral-+6': th.color('coolGrey-+6'),
    'semantic-neutral-+7': th.color('coolGrey-+7'),
    'semantic-neutral-+8': th.color('coolGrey-+8'),
    'semantic-neutralA--4': th.color('coolGreyA--4'),
    'semantic-neutralA--3': th.color('coolGreyA--3'),
    'semantic-neutralA--2': th.color('coolGreyA--2'),
    'semantic-neutralA--1': th.color('coolGreyA--1'),
    'semantic-neutralA-0': th.color('coolGreyA-0'),
    'semantic-neutralA-+1': th.color('coolGreyA-+1'),
    'semantic-neutralA-+2': th.color('coolGreyA-+2'),
    'semantic-neutralA-+3': th.color('coolGreyA-+3'),
    'semantic-neutralA-+4': th.color('coolGreyA-+4'),
    'semantic-neutralA-+5': th.color('coolGreyA-+5'),
    'semantic-neutralA-+6': th.color('coolGreyA-+6'),
    'semantic-neutralA-+7': th.color('coolGreyA-+7'),
    'semantic-neutralA-+8': th.color('coolGreyA-+8'),
    'semantic-positive--4': th.color('green--4'),
    'semantic-positive--3': th.color('green--3'),
    'semantic-positive--2': th.color('green--2'),
    'semantic-positive--1': th.color('green--1'),
    'semantic-positive-0': th.color('green-0'),
    'semantic-positive-+1': th.color('green-+1'),
    'semantic-positive-+2': th.color('green-+2'),
    'semantic-positive-+3': th.color('green-+3'),
    'semantic-positive-+4': th.color('green-+4'),
    'semantic-positive-+5': th.color('green-+5'),
    'semantic-positive-+6': th.color('green-+6'),
    'semantic-positive-+7': th.color('green-+7'),
    'semantic-positive-+8': th.color('green-+8'),
    'semantic-warning--4': th.color('orange--4'),
    'semantic-warning--3': th.color('orange--3'),
    'semantic-warning--2': th.color('orange--2'),
    'semantic-warning--1': th.color('orange--1'),
    'semantic-warning-0': th.color('orange-0'),
    'semantic-warning-+1': th.color('orange-+1'),
    'semantic-warning-+2': th.color('orange-+2'),
    'semantic-warning-+3': th.color('orange-+3'),
    'semantic-warning-+4': th.color('orange-+4'),
    'semantic-warning-+5': th.color('orange-+5'),
    'semantic-warning-+6': th.color('orange-+6'),
    'semantic-warning-+7': th.color('orange-+7'),
    'semantic-warning-+8': th.color('orange-+8'),
    'semantic-negative--4': th.color('red--4'),
    'semantic-negative--3': th.color('red--3'),
    'semantic-negative--2': th.color('red--2'),
    'semantic-negative--1': th.color('red--1'),
    'semantic-negative-0': th.color('red-0'),
    'semantic-negative-+1': th.color('red-+1'),
    'semantic-negative-+2': th.color('red-+2'),
    'semantic-negative-+3': th.color('red-+3'),
    'semantic-negative-+4': th.color('red-+4'),
    'semantic-negative-+5': th.color('red-+5'),
    'semantic-negative-+6': th.color('red-+6'),
    'semantic-negative-+7': th.color('red-+7'),
    'semantic-negative-+8': th.color('red-+8'),
    'content-primary': th.color('semantic-neutral--3'),
    'content-secondary': th.color('semantic-neutral-0'),
    'content-tertiary': th.color('semantic-neutral-+1'),
    'content-disabled': th.color('semantic-neutral-+2'),
    'content-primary-inverted': th.color('whiteA-0'),
    'content-secondary-inverted': th.color('whiteA--4'),
    'content-tertiary-inverted': th.color('whiteA--5'),
    'content-disabled-inverted': th.color('whiteA--6'),
    'content-informative': th.color('semantic-informative-0'),
    'content-positive': th.color('semantic-positive-0'),
    'content-warning': th.color('semantic-warning-0'),
    'content-negative': th.color('semantic-negative-0'),
    'content-brand': th.color('semantic-brand-0'),
    'border-neutral': th.color('semantic-neutral-0'),
    'border-informative': th.color('semantic-informative-0'),
    'border-positive': th.color('semantic-positive-0'),
    'border-warning': th.color('semantic-warning-0'),
    'border-negative': th.color('semantic-negative-0'),
    'border-brand': th.color('semantic-brand-0'),
    'border-neutral-subtle': th.color('semantic-neutral-+3'),
    'border-informative-subtle': th.color('semantic-informative-+3'),
    'border-positive-subtle': th.color('semantic-positive-+3'),
    'border-warning-subtle': th.color('semantic-warning-+3'),
    'border-negative-subtle': th.color('semantic-negative-+3'),
    'border-brand-subtle': th.color('semantic-brand-+3'),
    'border-inverted': th.color('whiteA-0'),
    'border-default': th.color('semantic-neutral-+5'),
    'background-default': th.color('whiteA-0'),
    'background-inverted': th.color('semantic-neutral--3'),
    'background-neutral': th.color('semantic-neutral-0'),
    'background-informative': th.color('semantic-informative-0'),
    'background-positive': th.color('semantic-positive-0'),
    'background-warning': th.color('semantic-warning-0'),
    'background-negative': th.color('semantic-negative-0'),
    'background-brand': th.color('semantic-brand-0'),
    'background-neutral-subtle': th.color('semantic-neutral-+7'),
    'background-informative-subtle': th.color('semantic-informative-+7'),
    'background-positive-subtle': th.color('semantic-positive-+7'),
    'background-warning-subtle': th.color('semantic-warning-+7'),
    'background-negative-subtle': th.color('semantic-negative-+7'),
    'background-brand-subtle': th.color('semantic-brand-+7'),
    'background-neutral-surface': th.color('semantic-neutral-+8'),
    'background-informative-surface': th.color('semantic-informative-+8'),
    'background-positive-surface': th.color('semantic-positive-+8'),
    'background-warning-surface': th.color('semantic-warning-+8'),
    'background-negative-surface': th.color('semantic-negative-+8'),
    'background-brand-surface': th.color('semantic-brand-+8'),
    'background-dimmer': th.color('semantic-neutralA-0'),
    'action-primary-normal': th.color('semantic-brand-0'),
    'action-primary-hover': th.color('semantic-brand--2'),
    'action-primary-active': th.color('semantic-brand--3'),
    'action-primary-selected': th.color('semantic-brand--2'),
    'action-primary-subtle-normal': th.color('semantic-brand-+6'),
    'action-primary-subtle-hover': th.color('semantic-brand-+5'),
    'action-primary-subtle-active': th.color('semantic-brand-+3'),
    'action-primary-subtle-selected': th.color('semantic-brand-+5'),
    'action-neutral-normal': th.color('semantic-neutral--1'),
    'action-neutral-hover': th.color('semantic-neutral--2'),
    'action-neutral-active': th.color('semantic-neutral--3'),
    'action-neutral-selected': th.color('semantic-neutral--2'),
    'action-neutral-subtle-normal': th.color('semantic-neutral-+6'),
    'action-neutral-subtle-hover': th.color('semantic-neutral-+5'),
    'action-neutral-subtle-active': th.color('semantic-neutral-+3'),
    'action-neutral-subtle-selected': th.color('semantic-neutral-+5'),
    'action-success-normal': th.color('semantic-positive-0'),
    'action-success-hover': th.color('semantic-positive--2'),
    'action-success-active': th.color('semantic-positive--3'),
    'action-success-selected': th.color('semantic-positive--2'),
    'action-success-subtle-normal': th.color('semantic-positive-+6'),
    'action-success-subtle-hover': th.color('semantic-positive-+5'),
    'action-success-subtle-active': th.color('semantic-positive-+3'),
    'action-success-subtle-selected': th.color('semantic-positive-+5'),
    'action-destructive-normal': th.color('semantic-negative-0'),
    'action-destructive-hover': th.color('semantic-negative--2'),
    'action-destructive-active': th.color('semantic-negative--3'),
    'action-destructive-selected': th.color('semantic-negative--2'),
    'action-destructive-subtle-normal': th.color('semantic-negative-+6'),
    'action-destructive-subtle-hover': th.color('semantic-negative-+5'),
    'action-destructive-subtle-active': th.color('semantic-negative-+3'),
    'action-destructive-subtle-selected': th.color('semantic-negative-+5'),
    'action-ghost-normal': th.color('transparent'),
    'action-ghost-hover': th.color('semantic-neutralA-+6'),
    'action-ghost-active': th.color('semantic-neutralA-+5'),
    'action-ghost-selected': th.color('semantic-neutralA-+6'),
    'action-ghost-inverted-hover': th.color('whiteA--8'),
    'action-ghost-inverted-active': th.color('whiteA--7'),
    'action-ghost-inverted-selected': th.color('whiteA--8'),
    'action-ghost-destructive-hover': th.color('semantic-negative-+6'),
    'action-ghost-destructive-active': th.color('semantic-negative-+5'),
    'action-ghost-destructive-selected': th.color('semantic-negative-+6'),
    'action-outline-normal': th.color('semantic-neutral-+3'),
    'action-outline-hover': th.color('semantic-neutral-+2'),
    'action-outline-active': th.color('semantic-neutral-+1'),
    'action-outline-selected': th.color('semantic-neutral-+2'),
    'action-inverted-normal': th.color('whiteA-0'),
    'action-inverted-hover': th.color('whiteA--1'),
    'action-inverted-active': th.color('whiteA--2'),
    'action-inverted-selected': th.color('whiteA--1'),
    'action-reverseInverted-normal': th.color('semantic-neutralA--3'),
    'action-reverseInverted-hover': th.color('semantic-neutralA--1'),
    'action-reverseInverted-active': th.color('semantic-neutralA-0'),
    'action-reverseInverted-selected': th.color('semantic-neutralA--1'),
    'interaction-default-normal': th.color('blue-0'),
    'interaction-default-hover': th.color('blue--2'),
    'interaction-default-active': th.color('blue--3'),
    'interaction-default-selected': th.color('blue--2'),
    'interaction-default-subtle-normal': th.color('blue-+6'),
    'interaction-default-subtle-hover': th.color('blue-+5'),
    'interaction-default-subtle-active': th.color('blue-+3'),
    'interaction-default-subtle-selected': th.color('blue-+5'),
    'interaction-neutral-normal': th.color('semantic-neutral--1'),
    'interaction-neutral-hover': th.color('semantic-neutral--2'),
    'interaction-neutral-active': th.color('semantic-neutral--3'),
    'interaction-neutral-selected': th.color('semantic-neutral--2'),
    'interaction-neutral-subtle-normal': th.color('semantic-neutral-+6'),
    'interaction-neutral-subtle-hover': th.color('semantic-neutral-+5'),
    'interaction-neutral-subtle-active': th.color('semantic-neutral-+3'),
    'interaction-neutral-subtle-selected': th.color('semantic-neutral-+5'),
    'interaction-alert-normal': th.color('semantic-negative-0'),
    'interaction-alert-hover': th.color('semantic-negative--2'),
    'interaction-alert-active': th.color('semantic-negative--3'),
    'interaction-alert-selected': th.color('semantic-negative--2'),
    'interaction-alert-subtle-normal': th.color('semantic-negative-+6'),
    'interaction-alert-subtle-hover': th.color('semantic-negative-+5'),
    'interaction-alert-subtle-active': th.color('semantic-negative-+3'),
    'interaction-alert-subtle-selected': th.color('semantic-negative-+5'),
    'interaction-ghost-normal': th.color('transparent'),
    'interaction-ghost-hover': th.color('semantic-neutralA-+6'),
    'interaction-ghost-active': th.color('semantic-neutralA-+5'),
    'interaction-ghost-selected': th.color('semantic-neutralA-+6'),
    'interaction-ghost-inverted-hover': th.color('whiteA--8'),
    'interaction-ghost-inverted-normal': th.color('whiteA--7'),
    'interaction-ghost-inverted-selected': th.color('whiteA--8'),
    'interaction-ghost-destructive-hover': th.color('semantic-negative-+6'),
    'interaction-ghost-destructive-normal': th.color('semantic-negative-+5'),
    'interaction-ghost-destructive-selected': th.color('semantic-negative-+6'),
    'interaction-disabled-normal': th.color('semantic-neutral-+2'),
    'interaction-disabled-hover': th.color('semantic-neutral-+1'),
    'interaction-disabled-active': th.color('semantic-neutral-0'),
    'interaction-disabled-subtle-normal': th.color('semantic-neutral-+5'),
    'interaction-disabled-subtle-hover': th.color('semantic-neutral-+4'),
    'interaction-disabled-subtle-active': th.color('semantic-neutral-+3'),
    'interaction-border-normal': th.color('blue-+2'),
    'interaction-border-hover': th.color('blue-+1'),
    'interaction-border-active': th.color('blue--1'),
    'interaction-border-selected': th.color('blue-0'),
    'interaction-border-neutral-normal': th.color('semantic-neutral-+3'),
    'interaction-border-neutral-hover': th.color('semantic-neutral-+2'),
    'interaction-border-neutral-active': th.color('semantic-neutral-+1'),
    'interaction-border-neutral-selected': th.color('semantic-neutral-+2'),
    'interaction-border-alert': th.color('semantic-negative-+1'),
    'interaction-background-modal': th.color('background-default'),
    'interaction-background-modeless': th.color('background-default'),
    'interaction-background-modeless-inverted': th.color('background-inverted'),
    'interaction-background-sidepanel': th.color('background-default'),
    'interaction-background-formField': th.color('background-default'),
    'interaction-inverted-normal': th.color('whiteA-0'),
    'interaction-inverted-hover': th.color('whiteA--1'),
    'interaction-inverted-active': th.color('whiteA--2'),
    'interaction-inverted-selected': th.color('whiteA--1'),
    'interaction-focus-default': th.color('blue-+1'),
    'nonContextual-grey-onMuted': th.color('semantic-neutral--4'),
    'nonContextual-grey-default': th.color('semantic-neutral-0'),
    'nonContextual-grey-muted': th.color('semantic-neutral-+4'),
    'nonContextual-grey-subtle': th.color('semantic-neutral-+5'),
    'nonContextual-grey-surface': th.color('semantic-neutral-+8'),
    'nonContextual-red-onMuted': th.color('red--4'),
    'nonContextual-red-default': th.color('red-0'),
    'nonContextual-red-muted': th.color('red-+4'),
    'nonContextual-red-subtle': th.color('red-+5'),
    'nonContextual-red-surface': th.color('red-+8'),
    'nonContextual-raspberry-onMuted': th.color('raspberry--4'),
    'nonContextual-raspberry-default': th.color('raspberry-0'),
    'nonContextual-raspberry-muted': th.color('raspberry-+4'),
    'nonContextual-raspberry-subtle': th.color('raspberry-+5'),
    'nonContextual-raspberry-surface': th.color('raspberry-+8'),
    'nonContextual-magenta-onMuted': th.color('magenta--4'),
    'nonContextual-magenta-default': th.color('magenta-0'),
    'nonContextual-magenta-muted': th.color('magenta-+4'),
    'nonContextual-magenta-subtle': th.color('magenta-+5'),
    'nonContextual-magenta-surface': th.color('magenta-+8'),
    'nonContextual-purple-onMuted': th.color('purple--4'),
    'nonContextual-purple-default': th.color('purple-0'),
    'nonContextual-purple-muted': th.color('purple-+4'),
    'nonContextual-purple-subtle': th.color('purple-+5'),
    'nonContextual-purple-surface': th.color('purple-+8'),
    'nonContextual-grape-onMuted': th.color('grape--4'),
    'nonContextual-grape-default': th.color('grape-0'),
    'nonContextual-grape-muted': th.color('grape-+4'),
    'nonContextual-grape-subtle': th.color('grape-+5'),
    'nonContextual-grape-surface': th.color('grape-+8'),
    'nonContextual-violet-onMuted': th.color('violet--4'),
    'nonContextual-violet-default': th.color('violet-0'),
    'nonContextual-violet-muted': th.color('violet-+4'),
    'nonContextual-violet-subtle': th.color('violet-+5'),
    'nonContextual-violet-surface': th.color('violet-+8'),
    'nonContextual-blue-onMuted': th.color('blue--4'),
    'nonContextual-blue-default': th.color('blue-0'),
    'nonContextual-blue-muted': th.color('blue-+4'),
    'nonContextual-blue-subtle': th.color('blue-+5'),
    'nonContextual-blue-surface': th.color('blue-+8'),
    'nonContextual-cyan-onMuted': th.color('cyan--4'),
    'nonContextual-cyan-default': th.color('cyan-0'),
    'nonContextual-cyan-muted': th.color('cyan-+4'),
    'nonContextual-cyan-subtle': th.color('cyan-+5'),
    'nonContextual-cyan-surface': th.color('cyan-+8'),
    'nonContextual-teal-onMuted': th.color('teal--4'),
    'nonContextual-teal-default': th.color('teal-0'),
    'nonContextual-teal-muted': th.color('teal-+4'),
    'nonContextual-teal-subtle': th.color('teal-+5'),
    'nonContextual-teal-surface': th.color('teal-+8'),
    'nonContextual-aquamarine-onMuted': th.color('aquamarine--4'),
    'nonContextual-aquamarine-default': th.color('aquamarine-0'),
    'nonContextual-aquamarine-muted': th.color('aquamarine-+4'),
    'nonContextual-aquamarine-subtle': th.color('aquamarine-+5'),
    'nonContextual-aquamarine-surface': th.color('aquamarine-+8'),
    'nonContextual-green-onMuted': th.color('green--4'),
    'nonContextual-green-default': th.color('green-0'),
    'nonContextual-green-muted': th.color('green-+4'),
    'nonContextual-green-subtle': th.color('green-+5'),
    'nonContextual-green-surface': th.color('green-+8'),
    'nonContextual-emerald-onMuted': th.color('emerald--4'),
    'nonContextual-emerald-default': th.color('emerald-0'),
    'nonContextual-emerald-muted': th.color('emerald-+4'),
    'nonContextual-emerald-subtle': th.color('emerald-+5'),
    'nonContextual-emerald-surface': th.color('emerald-+8'),
    'border-defaultA': th.color('semantic-neutralA-+5'),
    'nonContextual-orange-onMuted': th.color('orange--4'),
    'nonContextual-orange-default': th.color('orange-0'),
    'nonContextual-orange-muted': th.color('orange-+4'),
    'nonContextual-orange-subtle': th.color('orange-+5'),
    'nonContextual-orange-surface': th.color('orange-+8'),
  },
  radii: {
    '0': '0px',
    '100': '2px',
    '200': '4px',
    '300': '6px',
    full: '50%',
    small: th.radius('100'),
    medium: th.radius('200'),
    large: th.radius('300'),
  },
  borderWidths: {
    '0': '0px',
    '100': '1px',
    '200': '2px',
    small: th.borderWidth('100'),
    focus: th.borderWidth('200'),
    medium: th.borderWidth('200'),
  },
  borderStyles: {
    none: 'none',
    solid: 'solid',
    dashed: 'dashed solid',
  },
  sizes: {
    '0': '0px',
    '25': '4px',
    '50': '8px',
    '100': '16px',
    '150': '20px',
    '200': '24px',
    '250': '32px',
    '300': '40px',
    '350': '48px',
  },
  space: {
    '0': '0px',
    '25': '2px',
    '50': '4px',
    '75': '6px',
    '100': '8px',
    '150': '12px',
    '200': '16px',
    '300': '24px',
    '400': '32px',
    '500': '64px',
    '125': '10px',
    '175': '14px',
    'component-gap-xSmall': th.space('25'),
    'component-gap-small': th.space('50'),
    'component-gap-medium': th.space('75'),
    'component-gap-large': th.space('100'),
    'component-gap-xLarge': th.space('125'),
    'component-gap-2xLarge': th.space('200'),
    'component-gap-3xLarge': th.space('400'),
    'component-padding-xSmall': th.space('50'),
    'component-padding-small': th.space('75'),
    'component-padding-medium': th.space('100'),
    'component-padding-large': th.space('125'),
    'component-padding-xLarge': th.space('150'),
    'component-padding-2xLarge': th.space('175'),
    'component-padding-3xLarge': th.space('200'),
    'component-padding-4xLarge': th.space('300'),
  },
  fonts: { primary: 'Inter' },
  fontSizes: {
    '25': '10px',
    '50': '12px',
    '75': '14px',
    '100': '16px',
    '200': '18px',
    '300': '24px',
    '400': '32px',
    '500': '40px',
    '600': '48px',
  },
  fontWeights: { '400': '400', '450': '450', '600': '600' },
  letterSpacings: {
    '0': '0px',
    '100': '0.1px',
    '200': '0.2px',
  },
  lineHeights: {
    'scale-100': '1',
    'scale-150': '1.5',
    'scale-166': '1.66',
    'scale-200': '2',
    'value-100': '16px',
    'value-150': '20px',
    'value-200': '24px',
    'value-250': '28px',
    'value-300': '32px',
    'value-350': '36px',
    'value-450': '44px',
    'value-600': '56px',
    'value-700': '64px',
  },
  texts: {
    'normal-25': {
      fontFamily: 'primary',
      fontSize: '25',
      lineHeight: 'value-100',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-50': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-75': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-100': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-200': {
      fontFamily: 'primary',
      fontSize: '200',
      lineHeight: 'value-300',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-300': {
      fontFamily: 'primary',
      fontSize: '300',
      lineHeight: 'value-350',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-400': {
      fontFamily: 'primary',
      fontSize: '400',
      lineHeight: 'value-450',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-500': {
      fontFamily: 'primary',
      fontSize: '500',
      lineHeight: 'value-600',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'normal-600': {
      fontFamily: 'primary',
      fontSize: '600',
      lineHeight: 'value-700',
      fontWeight: '400',
      letterSpacing: '200',
    },
    'medium-25': {
      fontFamily: 'primary',
      fontSize: '25',
      lineHeight: 'value-100',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-50': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-75': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-100': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-200': {
      fontFamily: 'primary',
      fontSize: '200',
      lineHeight: 'value-300',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-300': {
      fontFamily: 'primary',
      fontSize: '300',
      lineHeight: 'value-350',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-400': {
      fontFamily: 'primary',
      fontSize: '400',
      lineHeight: 'value-450',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-500': {
      fontFamily: 'primary',
      fontSize: '500',
      lineHeight: 'value-600',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'medium-600': {
      fontFamily: 'primary',
      fontSize: '600',
      lineHeight: 'value-700',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'strong-25': {
      fontFamily: 'primary',
      fontSize: '25',
      lineHeight: 'value-100',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-50': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-75': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-100': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-200': {
      fontFamily: 'primary',
      fontSize: '200',
      lineHeight: 'value-300',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-300': {
      fontFamily: 'primary',
      fontSize: '300',
      lineHeight: 'value-350',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-400': {
      fontFamily: 'primary',
      fontSize: '400',
      lineHeight: 'value-450',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-500': {
      fontFamily: 'primary',
      fontSize: '500',
      lineHeight: 'value-600',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'strong-600': {
      fontFamily: 'primary',
      fontSize: '600',
      lineHeight: 'value-700',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'body-large': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'body-medium': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'body-small': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'body-xSmall': {
      fontFamily: 'primary',
      fontSize: '25',
      lineHeight: 'value-100',
      fontWeight: '450',
      letterSpacing: '200',
    },
    'body-strong-large': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'body-strong-medium': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'body-strong-small': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'body-strong-xSmall': {
      fontFamily: 'primary',
      fontSize: '25',
      lineHeight: 'value-100',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'hero-large': {
      fontFamily: 'primary',
      fontSize: '500',
      lineHeight: 'value-600',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'hero-medium': {
      fontFamily: 'primary',
      fontSize: '600',
      lineHeight: 'value-700',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-4xLarge': {
      fontFamily: 'primary',
      fontSize: '400',
      lineHeight: 'value-450',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-3xLarge': {
      fontFamily: 'primary',
      fontSize: '300',
      lineHeight: 'value-350',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-xLarge': {
      fontFamily: 'primary',
      fontSize: '200',
      lineHeight: 'value-300',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-large': {
      fontFamily: 'primary',
      fontSize: '100',
      lineHeight: 'value-250',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-medium': {
      fontFamily: 'primary',
      fontSize: '75',
      lineHeight: 'value-200',
      fontWeight: '600',
      letterSpacing: '100',
    },
    'header-small': {
      fontFamily: 'primary',
      fontSize: '50',
      lineHeight: 'value-150',
      fontWeight: '600',
      letterSpacing: '100',
    },
  },
  shadows: {
    'bottom-100': '0px 1px 2px 0px rgba(27, 36, 44, 0.12)',
    'bottom-200':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 2px 8px -1px rgba(27, 36, 44, 0.08)',
    'bottom-300':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 8px 16px -2px rgba(27, 36, 44, 0.12)',
    'bottom-400':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 16px 24px -6px rgba(27, 36, 44, 0.16)',
    'top-100': '0px -1px 2px 0px rgba(27, 36, 44, 0.12)',
    'top-200':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -2px 8px -1px rgba(27, 36, 44, 0.08)',
    'top-300':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -8px 16px -2px rgba(27, 36, 44, 0.12)',
    'top-400':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -16px 24px -6px rgba(27, 36, 44, 0.16)',
  },
  opacity: { '0': '0', '50': '0.5', '100': '1', disabled: '0.5' },
};
