import { th } from '@xstyled/system';

type RefferenceType = ReturnType<typeof th>;

export type Theme = {
  colors: Colors;
  radii: Radii;
  borderWidths: BorderWidths;
  borderStyles: BorderStyles;
  sizes: Sizes;
  space: Space;
  fonts: Fonts;
  fontSizes: FontSizes;
  fontWeights: FontWeights;
  letterSpacings: LetterSpacings;
  lineHeights: LineHeights;
  texts: Texts;
  shadows: Shadows;
  opacity: Opacity;
};

export type AbstractTheme = Partial<{
  [key in keyof Theme]: Record<string, string | RefferenceType>;
}>;
export type Colors = {
  'coolGrey--4': string | RefferenceType;
  'coolGrey--3': string | RefferenceType;
  'coolGrey--2': string | RefferenceType;
  'coolGrey--1': string | RefferenceType;
  'coolGrey-0': string | RefferenceType;
  'coolGrey-+1': string | RefferenceType;
  'coolGrey-+2': string | RefferenceType;
  'coolGrey-+3': string | RefferenceType;
  'coolGrey-+4': string | RefferenceType;
  'coolGrey-+5': string | RefferenceType;
  'coolGrey-+6': string | RefferenceType;
  'coolGrey-+7': string | RefferenceType;
  'coolGrey-+8': string | RefferenceType;
  'coolGreyA--4': string | RefferenceType;
  'coolGreyA--3': string | RefferenceType;
  'coolGreyA--2': string | RefferenceType;
  'coolGreyA--1': string | RefferenceType;
  'coolGreyA-0': string | RefferenceType;
  'coolGreyA-+1': string | RefferenceType;
  'coolGreyA-+2': string | RefferenceType;
  'coolGreyA-+3': string | RefferenceType;
  'coolGreyA-+4': string | RefferenceType;
  'coolGreyA-+5': string | RefferenceType;
  'coolGreyA-+6': string | RefferenceType;
  'coolGreyA-+7': string | RefferenceType;
  'coolGreyA-+8': string | RefferenceType;
  'neutralGrey--4': string | RefferenceType;
  'neutralGrey--3': string | RefferenceType;
  'neutralGrey--2': string | RefferenceType;
  'neutralGrey--1': string | RefferenceType;
  'neutralGrey-0': string | RefferenceType;
  'neutralGrey-+1': string | RefferenceType;
  'neutralGrey-+2': string | RefferenceType;
  'neutralGrey-+3': string | RefferenceType;
  'neutralGrey-+4': string | RefferenceType;
  'neutralGrey-+5': string | RefferenceType;
  'neutralGrey-+6': string | RefferenceType;
  'neutralGrey-+7': string | RefferenceType;
  'neutralGrey-+8': string | RefferenceType;
  'neutralGreyA--4': string | RefferenceType;
  'neutralGreyA--3': string | RefferenceType;
  'neutralGreyA--2': string | RefferenceType;
  'neutralGreyA--1': string | RefferenceType;
  'neutralGreyA-0': string | RefferenceType;
  'neutralGreyA-+1': string | RefferenceType;
  'neutralGreyA-+2': string | RefferenceType;
  'neutralGreyA-+3': string | RefferenceType;
  'neutralGreyA-+4': string | RefferenceType;
  'neutralGreyA-+5': string | RefferenceType;
  'neutralGreyA-+6': string | RefferenceType;
  'neutralGreyA-+7': string | RefferenceType;
  'neutralGreyA-+8': string | RefferenceType;
  'warmGrey--4': string | RefferenceType;
  'warmGrey--3': string | RefferenceType;
  'warmGrey--2': string | RefferenceType;
  'warmGrey--1': string | RefferenceType;
  'warmGrey-0': string | RefferenceType;
  'warmGrey-+1': string | RefferenceType;
  'warmGrey-+2': string | RefferenceType;
  'warmGrey-+3': string | RefferenceType;
  'warmGrey-+4': string | RefferenceType;
  'warmGrey-+5': string | RefferenceType;
  'warmGrey-+6': string | RefferenceType;
  'warmGrey-+7': string | RefferenceType;
  'warmGrey-+8': string | RefferenceType;
  'warmGreyA--4': string | RefferenceType;
  'warmGreyA--3': string | RefferenceType;
  'warmGreyA--2': string | RefferenceType;
  'warmGreyA--1': string | RefferenceType;
  'warmGreyA-0': string | RefferenceType;
  'warmGreyA-+1': string | RefferenceType;
  'warmGreyA-+2': string | RefferenceType;
  'warmGreyA-+3': string | RefferenceType;
  'warmGreyA-+4': string | RefferenceType;
  'warmGreyA-+5': string | RefferenceType;
  'warmGreyA-+6': string | RefferenceType;
  'warmGreyA-+7': string | RefferenceType;
  'warmGreyA-+8': string | RefferenceType;
  'whiteA--12': string | RefferenceType;
  'whiteA--11': string | RefferenceType;
  'whiteA--10': string | RefferenceType;
  'whiteA--9': string | RefferenceType;
  'whiteA--8': string | RefferenceType;
  'whiteA--7': string | RefferenceType;
  'whiteA--6': string | RefferenceType;
  'whiteA--5': string | RefferenceType;
  'whiteA--4': string | RefferenceType;
  'whiteA--3': string | RefferenceType;
  'whiteA--2': string | RefferenceType;
  'whiteA--1': string | RefferenceType;
  'whiteA-0': string | RefferenceType;
  'red--4': string | RefferenceType;
  'red--3': string | RefferenceType;
  'red--2': string | RefferenceType;
  'red--1': string | RefferenceType;
  'red-0': string | RefferenceType;
  'red-+1': string | RefferenceType;
  'red-+2': string | RefferenceType;
  'red-+3': string | RefferenceType;
  'red-+4': string | RefferenceType;
  'red-+5': string | RefferenceType;
  'red-+6': string | RefferenceType;
  'red-+7': string | RefferenceType;
  'red-+8': string | RefferenceType;
  'raspberry--4': string | RefferenceType;
  'raspberry--3': string | RefferenceType;
  'raspberry--2': string | RefferenceType;
  'raspberry--1': string | RefferenceType;
  'raspberry-0': string | RefferenceType;
  'raspberry-+1': string | RefferenceType;
  'raspberry-+2': string | RefferenceType;
  'raspberry-+3': string | RefferenceType;
  'raspberry-+4': string | RefferenceType;
  'raspberry-+5': string | RefferenceType;
  'raspberry-+6': string | RefferenceType;
  'raspberry-+7': string | RefferenceType;
  'raspberry-+8': string | RefferenceType;
  'magenta--4': string | RefferenceType;
  'magenta--3': string | RefferenceType;
  'magenta--2': string | RefferenceType;
  'magenta--1': string | RefferenceType;
  'magenta-0': string | RefferenceType;
  'magenta-+1': string | RefferenceType;
  'magenta-+2': string | RefferenceType;
  'magenta-+3': string | RefferenceType;
  'magenta-+4': string | RefferenceType;
  'magenta-+5': string | RefferenceType;
  'magenta-+6': string | RefferenceType;
  'magenta-+7': string | RefferenceType;
  'magenta-+8': string | RefferenceType;
  'purple--4': string | RefferenceType;
  'purple--3': string | RefferenceType;
  'purple--2': string | RefferenceType;
  'purple--1': string | RefferenceType;
  'purple-0': string | RefferenceType;
  'purple-+1': string | RefferenceType;
  'purple-+2': string | RefferenceType;
  'purple-+3': string | RefferenceType;
  'purple-+4': string | RefferenceType;
  'purple-+5': string | RefferenceType;
  'purple-+6': string | RefferenceType;
  'purple-+7': string | RefferenceType;
  'purple-+8': string | RefferenceType;
  'grape--4': string | RefferenceType;
  'grape--3': string | RefferenceType;
  'grape--2': string | RefferenceType;
  'grape--1': string | RefferenceType;
  'grape-0': string | RefferenceType;
  'grape-+1': string | RefferenceType;
  'grape-+2': string | RefferenceType;
  'grape-+3': string | RefferenceType;
  'grape-+4': string | RefferenceType;
  'grape-+5': string | RefferenceType;
  'grape-+6': string | RefferenceType;
  'grape-+7': string | RefferenceType;
  'grape-+8': string | RefferenceType;
  'violet--4': string | RefferenceType;
  'violet--3': string | RefferenceType;
  'violet--2': string | RefferenceType;
  'violet--1': string | RefferenceType;
  'violet-0': string | RefferenceType;
  'violet-+1': string | RefferenceType;
  'violet-+2': string | RefferenceType;
  'violet-+3': string | RefferenceType;
  'violet-+4': string | RefferenceType;
  'violet-+5': string | RefferenceType;
  'violet-+6': string | RefferenceType;
  'violet-+7': string | RefferenceType;
  'violet-+8': string | RefferenceType;
  'blue--4': string | RefferenceType;
  'blue--3': string | RefferenceType;
  'blue--2': string | RefferenceType;
  'blue--1': string | RefferenceType;
  'blue-0': string | RefferenceType;
  'blue-+1': string | RefferenceType;
  'blue-+2': string | RefferenceType;
  'blue-+3': string | RefferenceType;
  'blue-+4': string | RefferenceType;
  'blue-+5': string | RefferenceType;
  'blue-+6': string | RefferenceType;
  'blue-+7': string | RefferenceType;
  'blue-+8': string | RefferenceType;
  'cyan--4': string | RefferenceType;
  'cyan--3': string | RefferenceType;
  'cyan--2': string | RefferenceType;
  'cyan--1': string | RefferenceType;
  'cyan-0': string | RefferenceType;
  'cyan-+1': string | RefferenceType;
  'cyan-+2': string | RefferenceType;
  'cyan-+3': string | RefferenceType;
  'cyan-+4': string | RefferenceType;
  'cyan-+5': string | RefferenceType;
  'cyan-+6': string | RefferenceType;
  'cyan-+7': string | RefferenceType;
  'cyan-+8': string | RefferenceType;
  'teal--4': string | RefferenceType;
  'teal--3': string | RefferenceType;
  'teal--2': string | RefferenceType;
  'teal--1': string | RefferenceType;
  'teal-0': string | RefferenceType;
  'teal-+1': string | RefferenceType;
  'teal-+2': string | RefferenceType;
  'teal-+3': string | RefferenceType;
  'teal-+4': string | RefferenceType;
  'teal-+5': string | RefferenceType;
  'teal-+6': string | RefferenceType;
  'teal-+7': string | RefferenceType;
  'teal-+8': string | RefferenceType;
  'aquamarine--4': string | RefferenceType;
  'aquamarine--3': string | RefferenceType;
  'aquamarine--2': string | RefferenceType;
  'aquamarine--1': string | RefferenceType;
  'aquamarine-0': string | RefferenceType;
  'aquamarine-+1': string | RefferenceType;
  'aquamarine-+2': string | RefferenceType;
  'aquamarine-+3': string | RefferenceType;
  'aquamarine-+4': string | RefferenceType;
  'aquamarine-+5': string | RefferenceType;
  'aquamarine-+6': string | RefferenceType;
  'aquamarine-+7': string | RefferenceType;
  'aquamarine-+8': string | RefferenceType;
  'green--4': string | RefferenceType;
  'green--3': string | RefferenceType;
  'green--2': string | RefferenceType;
  'green--1': string | RefferenceType;
  'green-0': string | RefferenceType;
  'green-+1': string | RefferenceType;
  'green-+2': string | RefferenceType;
  'green-+3': string | RefferenceType;
  'green-+4': string | RefferenceType;
  'green-+5': string | RefferenceType;
  'green-+6': string | RefferenceType;
  'green-+7': string | RefferenceType;
  'green-+8': string | RefferenceType;
  'emerald--4': string | RefferenceType;
  'emerald--3': string | RefferenceType;
  'emerald--2': string | RefferenceType;
  'emerald--1': string | RefferenceType;
  'emerald-0': string | RefferenceType;
  'emerald-+1': string | RefferenceType;
  'emerald-+2': string | RefferenceType;
  'emerald-+3': string | RefferenceType;
  'emerald-+4': string | RefferenceType;
  'emerald-+5': string | RefferenceType;
  'emerald-+6': string | RefferenceType;
  'emerald-+7': string | RefferenceType;
  'emerald-+8': string | RefferenceType;
  'orange--4': string | RefferenceType;
  'orange--3': string | RefferenceType;
  'orange--2': string | RefferenceType;
  'orange--1': string | RefferenceType;
  'orange-0': string | RefferenceType;
  'orange-+1': string | RefferenceType;
  'orange-+2': string | RefferenceType;
  'orange-+3': string | RefferenceType;
  'orange-+4': string | RefferenceType;
  'orange-+5': string | RefferenceType;
  'orange-+6': string | RefferenceType;
  'orange-+7': string | RefferenceType;
  'orange-+8': string | RefferenceType;
  transparent: string | RefferenceType;
  'semantic-brand--4': string | RefferenceType;
  'semantic-brand--3': string | RefferenceType;
  'semantic-brand--2': string | RefferenceType;
  'semantic-brand--1': string | RefferenceType;
  'semantic-brand-0': string | RefferenceType;
  'semantic-brand-+1': string | RefferenceType;
  'semantic-brand-+2': string | RefferenceType;
  'semantic-brand-+3': string | RefferenceType;
  'semantic-brand-+4': string | RefferenceType;
  'semantic-brand-+5': string | RefferenceType;
  'semantic-brand-+6': string | RefferenceType;
  'semantic-brand-+7': string | RefferenceType;
  'semantic-brand-+8': string | RefferenceType;
  'semantic-informative--4': string | RefferenceType;
  'semantic-informative--3': string | RefferenceType;
  'semantic-informative--2': string | RefferenceType;
  'semantic-informative--1': string | RefferenceType;
  'semantic-informative-0': string | RefferenceType;
  'semantic-informative-+1': string | RefferenceType;
  'semantic-informative-+2': string | RefferenceType;
  'semantic-informative-+3': string | RefferenceType;
  'semantic-informative-+4': string | RefferenceType;
  'semantic-informative-+5': string | RefferenceType;
  'semantic-informative-+6': string | RefferenceType;
  'semantic-informative-+7': string | RefferenceType;
  'semantic-informative-+8': string | RefferenceType;
  'semantic-neutral--4': string | RefferenceType;
  'semantic-neutral--3': string | RefferenceType;
  'semantic-neutral--2': string | RefferenceType;
  'semantic-neutral--1': string | RefferenceType;
  'semantic-neutral-0': string | RefferenceType;
  'semantic-neutral-+1': string | RefferenceType;
  'semantic-neutral-+2': string | RefferenceType;
  'semantic-neutral-+3': string | RefferenceType;
  'semantic-neutral-+4': string | RefferenceType;
  'semantic-neutral-+5': string | RefferenceType;
  'semantic-neutral-+6': string | RefferenceType;
  'semantic-neutral-+7': string | RefferenceType;
  'semantic-neutral-+8': string | RefferenceType;
  'semantic-neutralA--4': string | RefferenceType;
  'semantic-neutralA--3': string | RefferenceType;
  'semantic-neutralA--2': string | RefferenceType;
  'semantic-neutralA--1': string | RefferenceType;
  'semantic-neutralA-0': string | RefferenceType;
  'semantic-neutralA-+1': string | RefferenceType;
  'semantic-neutralA-+2': string | RefferenceType;
  'semantic-neutralA-+3': string | RefferenceType;
  'semantic-neutralA-+4': string | RefferenceType;
  'semantic-neutralA-+5': string | RefferenceType;
  'semantic-neutralA-+6': string | RefferenceType;
  'semantic-neutralA-+7': string | RefferenceType;
  'semantic-neutralA-+8': string | RefferenceType;
  'semantic-positive--4': string | RefferenceType;
  'semantic-positive--3': string | RefferenceType;
  'semantic-positive--2': string | RefferenceType;
  'semantic-positive--1': string | RefferenceType;
  'semantic-positive-0': string | RefferenceType;
  'semantic-positive-+1': string | RefferenceType;
  'semantic-positive-+2': string | RefferenceType;
  'semantic-positive-+3': string | RefferenceType;
  'semantic-positive-+4': string | RefferenceType;
  'semantic-positive-+5': string | RefferenceType;
  'semantic-positive-+6': string | RefferenceType;
  'semantic-positive-+7': string | RefferenceType;
  'semantic-positive-+8': string | RefferenceType;
  'semantic-warning--4': string | RefferenceType;
  'semantic-warning--3': string | RefferenceType;
  'semantic-warning--2': string | RefferenceType;
  'semantic-warning--1': string | RefferenceType;
  'semantic-warning-0': string | RefferenceType;
  'semantic-warning-+1': string | RefferenceType;
  'semantic-warning-+2': string | RefferenceType;
  'semantic-warning-+3': string | RefferenceType;
  'semantic-warning-+4': string | RefferenceType;
  'semantic-warning-+5': string | RefferenceType;
  'semantic-warning-+6': string | RefferenceType;
  'semantic-warning-+7': string | RefferenceType;
  'semantic-warning-+8': string | RefferenceType;
  'semantic-negative--4': string | RefferenceType;
  'semantic-negative--3': string | RefferenceType;
  'semantic-negative--2': string | RefferenceType;
  'semantic-negative--1': string | RefferenceType;
  'semantic-negative-0': string | RefferenceType;
  'semantic-negative-+1': string | RefferenceType;
  'semantic-negative-+2': string | RefferenceType;
  'semantic-negative-+3': string | RefferenceType;
  'semantic-negative-+4': string | RefferenceType;
  'semantic-negative-+5': string | RefferenceType;
  'semantic-negative-+6': string | RefferenceType;
  'semantic-negative-+7': string | RefferenceType;
  'semantic-negative-+8': string | RefferenceType;
  'content-primary': string | RefferenceType;
  'content-secondary': string | RefferenceType;
  'content-tertiary': string | RefferenceType;
  'content-disabled': string | RefferenceType;
  'content-primary-inverted': string | RefferenceType;
  'content-secondary-inverted': string | RefferenceType;
  'content-tertiary-inverted': string | RefferenceType;
  'content-disabled-inverted': string | RefferenceType;
  'content-informative': string | RefferenceType;
  'content-positive': string | RefferenceType;
  'content-warning': string | RefferenceType;
  'content-negative': string | RefferenceType;
  'content-brand': string | RefferenceType;
  'border-neutral': string | RefferenceType;
  'border-informative': string | RefferenceType;
  'border-positive': string | RefferenceType;
  'border-warning': string | RefferenceType;
  'border-negative': string | RefferenceType;
  'border-brand': string | RefferenceType;
  'border-neutral-subtle': string | RefferenceType;
  'border-informative-subtle': string | RefferenceType;
  'border-positive-subtle': string | RefferenceType;
  'border-warning-subtle': string | RefferenceType;
  'border-negative-subtle': string | RefferenceType;
  'border-brand-subtle': string | RefferenceType;
  'border-inverted': string | RefferenceType;
  'border-default': string | RefferenceType;
  'background-default': string | RefferenceType;
  'background-inverted': string | RefferenceType;
  'background-neutral': string | RefferenceType;
  'background-informative': string | RefferenceType;
  'background-positive': string | RefferenceType;
  'background-warning': string | RefferenceType;
  'background-negative': string | RefferenceType;
  'background-brand': string | RefferenceType;
  'background-neutral-subtle': string | RefferenceType;
  'background-informative-subtle': string | RefferenceType;
  'background-positive-subtle': string | RefferenceType;
  'background-warning-subtle': string | RefferenceType;
  'background-negative-subtle': string | RefferenceType;
  'background-brand-subtle': string | RefferenceType;
  'background-neutral-surface': string | RefferenceType;
  'background-informative-surface': string | RefferenceType;
  'background-positive-surface': string | RefferenceType;
  'background-warning-surface': string | RefferenceType;
  'background-negative-surface': string | RefferenceType;
  'background-brand-surface': string | RefferenceType;
  'background-dimmer': string | RefferenceType;
  'action-primary-normal': string | RefferenceType;
  'action-primary-hover': string | RefferenceType;
  'action-primary-active': string | RefferenceType;
  'action-primary-selected': string | RefferenceType;
  'action-primary-subtle-normal': string | RefferenceType;
  'action-primary-subtle-hover': string | RefferenceType;
  'action-primary-subtle-active': string | RefferenceType;
  'action-primary-subtle-selected': string | RefferenceType;
  'action-neutral-normal': string | RefferenceType;
  'action-neutral-hover': string | RefferenceType;
  'action-neutral-active': string | RefferenceType;
  'action-neutral-selected': string | RefferenceType;
  'action-neutral-subtle-normal': string | RefferenceType;
  'action-neutral-subtle-hover': string | RefferenceType;
  'action-neutral-subtle-active': string | RefferenceType;
  'action-neutral-subtle-selected': string | RefferenceType;
  'action-success-normal': string | RefferenceType;
  'action-success-hover': string | RefferenceType;
  'action-success-active': string | RefferenceType;
  'action-success-selected': string | RefferenceType;
  'action-success-subtle-normal': string | RefferenceType;
  'action-success-subtle-hover': string | RefferenceType;
  'action-success-subtle-active': string | RefferenceType;
  'action-success-subtle-selected': string | RefferenceType;
  'action-destructive-normal': string | RefferenceType;
  'action-destructive-hover': string | RefferenceType;
  'action-destructive-active': string | RefferenceType;
  'action-destructive-selected': string | RefferenceType;
  'action-destructive-subtle-normal': string | RefferenceType;
  'action-destructive-subtle-hover': string | RefferenceType;
  'action-destructive-subtle-active': string | RefferenceType;
  'action-destructive-subtle-selected': string | RefferenceType;
  'action-ghost-normal': string | RefferenceType;
  'action-ghost-hover': string | RefferenceType;
  'action-ghost-active': string | RefferenceType;
  'action-ghost-selected': string | RefferenceType;
  'action-ghost-inverted-hover': string | RefferenceType;
  'action-ghost-inverted-active': string | RefferenceType;
  'action-ghost-inverted-selected': string | RefferenceType;
  'action-ghost-destructive-hover': string | RefferenceType;
  'action-ghost-destructive-active': string | RefferenceType;
  'action-ghost-destructive-selected': string | RefferenceType;
  'action-outline-normal': string | RefferenceType;
  'action-outline-hover': string | RefferenceType;
  'action-outline-active': string | RefferenceType;
  'action-outline-selected': string | RefferenceType;
  'action-inverted-normal': string | RefferenceType;
  'action-inverted-hover': string | RefferenceType;
  'action-inverted-active': string | RefferenceType;
  'action-inverted-selected': string | RefferenceType;
  'action-reverseInverted-normal': string | RefferenceType;
  'action-reverseInverted-hover': string | RefferenceType;
  'action-reverseInverted-active': string | RefferenceType;
  'action-reverseInverted-selected': string | RefferenceType;
  'interaction-default-normal': string | RefferenceType;
  'interaction-default-hover': string | RefferenceType;
  'interaction-default-active': string | RefferenceType;
  'interaction-default-selected': string | RefferenceType;
  'interaction-default-subtle-normal': string | RefferenceType;
  'interaction-default-subtle-hover': string | RefferenceType;
  'interaction-default-subtle-active': string | RefferenceType;
  'interaction-default-subtle-selected': string | RefferenceType;
  'interaction-neutral-normal': string | RefferenceType;
  'interaction-neutral-hover': string | RefferenceType;
  'interaction-neutral-active': string | RefferenceType;
  'interaction-neutral-selected': string | RefferenceType;
  'interaction-neutral-subtle-normal': string | RefferenceType;
  'interaction-neutral-subtle-hover': string | RefferenceType;
  'interaction-neutral-subtle-active': string | RefferenceType;
  'interaction-neutral-subtle-selected': string | RefferenceType;
  'interaction-alert-normal': string | RefferenceType;
  'interaction-alert-hover': string | RefferenceType;
  'interaction-alert-active': string | RefferenceType;
  'interaction-alert-selected': string | RefferenceType;
  'interaction-alert-subtle-normal': string | RefferenceType;
  'interaction-alert-subtle-hover': string | RefferenceType;
  'interaction-alert-subtle-active': string | RefferenceType;
  'interaction-alert-subtle-selected': string | RefferenceType;
  'interaction-ghost-normal': string | RefferenceType;
  'interaction-ghost-hover': string | RefferenceType;
  'interaction-ghost-active': string | RefferenceType;
  'interaction-ghost-selected': string | RefferenceType;
  'interaction-ghost-inverted-hover': string | RefferenceType;
  'interaction-ghost-inverted-normal': string | RefferenceType;
  'interaction-ghost-inverted-selected': string | RefferenceType;
  'interaction-ghost-destructive-hover': string | RefferenceType;
  'interaction-ghost-destructive-normal': string | RefferenceType;
  'interaction-ghost-destructive-selected': string | RefferenceType;
  'interaction-disabled-normal': string | RefferenceType;
  'interaction-disabled-hover': string | RefferenceType;
  'interaction-disabled-active': string | RefferenceType;
  'interaction-disabled-subtle-normal': string | RefferenceType;
  'interaction-disabled-subtle-hover': string | RefferenceType;
  'interaction-disabled-subtle-active': string | RefferenceType;
  'interaction-border-normal': string | RefferenceType;
  'interaction-border-hover': string | RefferenceType;
  'interaction-border-active': string | RefferenceType;
  'interaction-border-selected': string | RefferenceType;
  'interaction-border-neutral-normal': string | RefferenceType;
  'interaction-border-neutral-hover': string | RefferenceType;
  'interaction-border-neutral-active': string | RefferenceType;
  'interaction-border-neutral-selected': string | RefferenceType;
  'interaction-border-alert': string | RefferenceType;
  'interaction-background-modal': string | RefferenceType;
  'interaction-background-modeless': string | RefferenceType;
  'interaction-background-modeless-inverted': string | RefferenceType;
  'interaction-background-sidepanel': string | RefferenceType;
  'interaction-background-formField': string | RefferenceType;
  'interaction-inverted-normal': string | RefferenceType;
  'interaction-inverted-hover': string | RefferenceType;
  'interaction-inverted-active': string | RefferenceType;
  'interaction-inverted-selected': string | RefferenceType;
  'interaction-focus-default': string | RefferenceType;
  'nonContextual-grey-onMuted': string | RefferenceType;
  'nonContextual-grey-default': string | RefferenceType;
  'nonContextual-grey-muted': string | RefferenceType;
  'nonContextual-grey-subtle': string | RefferenceType;
  'nonContextual-grey-surface': string | RefferenceType;
  'nonContextual-red-onMuted': string | RefferenceType;
  'nonContextual-red-default': string | RefferenceType;
  'nonContextual-red-muted': string | RefferenceType;
  'nonContextual-red-subtle': string | RefferenceType;
  'nonContextual-red-surface': string | RefferenceType;
  'nonContextual-raspberry-onMuted': string | RefferenceType;
  'nonContextual-raspberry-default': string | RefferenceType;
  'nonContextual-raspberry-muted': string | RefferenceType;
  'nonContextual-raspberry-subtle': string | RefferenceType;
  'nonContextual-raspberry-surface': string | RefferenceType;
  'nonContextual-magenta-onMuted': string | RefferenceType;
  'nonContextual-magenta-default': string | RefferenceType;
  'nonContextual-magenta-muted': string | RefferenceType;
  'nonContextual-magenta-subtle': string | RefferenceType;
  'nonContextual-magenta-surface': string | RefferenceType;
  'nonContextual-purple-onMuted': string | RefferenceType;
  'nonContextual-purple-default': string | RefferenceType;
  'nonContextual-purple-muted': string | RefferenceType;
  'nonContextual-purple-subtle': string | RefferenceType;
  'nonContextual-purple-surface': string | RefferenceType;
  'nonContextual-grape-onMuted': string | RefferenceType;
  'nonContextual-grape-default': string | RefferenceType;
  'nonContextual-grape-muted': string | RefferenceType;
  'nonContextual-grape-subtle': string | RefferenceType;
  'nonContextual-grape-surface': string | RefferenceType;
  'nonContextual-violet-onMuted': string | RefferenceType;
  'nonContextual-violet-default': string | RefferenceType;
  'nonContextual-violet-muted': string | RefferenceType;
  'nonContextual-violet-subtle': string | RefferenceType;
  'nonContextual-violet-surface': string | RefferenceType;
  'nonContextual-blue-onMuted': string | RefferenceType;
  'nonContextual-blue-default': string | RefferenceType;
  'nonContextual-blue-muted': string | RefferenceType;
  'nonContextual-blue-subtle': string | RefferenceType;
  'nonContextual-blue-surface': string | RefferenceType;
  'nonContextual-cyan-onMuted': string | RefferenceType;
  'nonContextual-cyan-default': string | RefferenceType;
  'nonContextual-cyan-muted': string | RefferenceType;
  'nonContextual-cyan-subtle': string | RefferenceType;
  'nonContextual-cyan-surface': string | RefferenceType;
  'nonContextual-teal-onMuted': string | RefferenceType;
  'nonContextual-teal-default': string | RefferenceType;
  'nonContextual-teal-muted': string | RefferenceType;
  'nonContextual-teal-subtle': string | RefferenceType;
  'nonContextual-teal-surface': string | RefferenceType;
  'nonContextual-aquamarine-onMuted': string | RefferenceType;
  'nonContextual-aquamarine-default': string | RefferenceType;
  'nonContextual-aquamarine-muted': string | RefferenceType;
  'nonContextual-aquamarine-subtle': string | RefferenceType;
  'nonContextual-aquamarine-surface': string | RefferenceType;
  'nonContextual-green-onMuted': string | RefferenceType;
  'nonContextual-green-default': string | RefferenceType;
  'nonContextual-green-muted': string | RefferenceType;
  'nonContextual-green-subtle': string | RefferenceType;
  'nonContextual-green-surface': string | RefferenceType;
  'nonContextual-emerald-onMuted': string | RefferenceType;
  'nonContextual-emerald-default': string | RefferenceType;
  'nonContextual-emerald-muted': string | RefferenceType;
  'nonContextual-emerald-subtle': string | RefferenceType;
  'nonContextual-emerald-surface': string | RefferenceType;
  'border-defaultA': string | RefferenceType;
  'nonContextual-orange-onMuted': string | RefferenceType;
  'nonContextual-orange-default': string | RefferenceType;
  'nonContextual-orange-muted': string | RefferenceType;
  'nonContextual-orange-subtle': string | RefferenceType;
  'nonContextual-orange-surface': string | RefferenceType;
};
export type Radii = {
  '0': string | RefferenceType;
  '100': string | RefferenceType;
  '200': string | RefferenceType;
  '300': string | RefferenceType;
  full: string | RefferenceType;
  small: string | RefferenceType;
  medium: string | RefferenceType;
  large: string | RefferenceType;
};
export type BorderWidths = {
  '0': string | RefferenceType;
  '100': string | RefferenceType;
  '200': string | RefferenceType;
  small: string | RefferenceType;
  focus: string | RefferenceType;
  medium: string | RefferenceType;
};
export type BorderStyles = {
  none: string | RefferenceType;
  solid: string | RefferenceType;
  dashed: string | RefferenceType;
};
export type Sizes = {
  '0': string | RefferenceType;
  '25': string | RefferenceType;
  '50': string | RefferenceType;
  '100': string | RefferenceType;
  '150': string | RefferenceType;
  '200': string | RefferenceType;
  '250': string | RefferenceType;
  '300': string | RefferenceType;
  '350': string | RefferenceType;
};
export type Space = {
  '0': string | RefferenceType;
  '25': string | RefferenceType;
  '50': string | RefferenceType;
  '75': string | RefferenceType;
  '100': string | RefferenceType;
  '150': string | RefferenceType;
  '200': string | RefferenceType;
  '300': string | RefferenceType;
  '400': string | RefferenceType;
  '500': string | RefferenceType;
  '125': string | RefferenceType;
  '175': string | RefferenceType;
  'component-gap-xSmall': string | RefferenceType;
  'component-gap-small': string | RefferenceType;
  'component-gap-medium': string | RefferenceType;
  'component-gap-large': string | RefferenceType;
  'component-gap-xLarge': string | RefferenceType;
  'component-gap-2xLarge': string | RefferenceType;
  'component-gap-3xLarge': string | RefferenceType;
  'component-padding-xSmall': string | RefferenceType;
  'component-padding-small': string | RefferenceType;
  'component-padding-medium': string | RefferenceType;
  'component-padding-large': string | RefferenceType;
  'component-padding-xLarge': string | RefferenceType;
  'component-padding-2xLarge': string | RefferenceType;
  'component-padding-3xLarge': string | RefferenceType;
  'component-padding-4xLarge': string | RefferenceType;
};
export type Fonts = {
  primary: string | RefferenceType;
};
export type FontSizes = {
  '25': string | RefferenceType;
  '50': string | RefferenceType;
  '75': string | RefferenceType;
  '100': string | RefferenceType;
  '200': string | RefferenceType;
  '300': string | RefferenceType;
  '400': string | RefferenceType;
  '500': string | RefferenceType;
  '600': string | RefferenceType;
};
export type FontWeights = {
  '400': string | RefferenceType;
  '450': string | RefferenceType;
  '600': string | RefferenceType;
};
export type LetterSpacings = {
  '0': string | RefferenceType;
  '100': string | RefferenceType;
  '200': string | RefferenceType;
};
export type LineHeights = {
  'scale-100': string | RefferenceType;
  'scale-150': string | RefferenceType;
  'scale-166': string | RefferenceType;
  'scale-200': string | RefferenceType;
  'value-100': string | RefferenceType;
  'value-150': string | RefferenceType;
  'value-200': string | RefferenceType;
  'value-250': string | RefferenceType;
  'value-300': string | RefferenceType;
  'value-350': string | RefferenceType;
  'value-450': string | RefferenceType;
  'value-600': string | RefferenceType;
  'value-700': string | RefferenceType;
};
export type Texts = {
  'normal-25': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-50': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-75': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-100': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-200': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-300': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-400': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-500': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'normal-600': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-25': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-50': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-75': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-100': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-200': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-300': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-400': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-500': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'medium-600': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-25': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-50': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-75': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-100': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-200': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-300': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-400': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-500': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'strong-600': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-large': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-medium': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-small': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-xSmall': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-strong-large': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-strong-medium': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-strong-small': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'body-strong-xSmall': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'hero-large': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'hero-medium': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-4xLarge': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-3xLarge': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-xLarge': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-large': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-medium': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
  'header-small': {
    fontFamily: string | RefferenceType;
    fontSize: string | RefferenceType;
    lineHeight: string | RefferenceType;
    fontWeight: string | RefferenceType;
    letterSpacing: string | RefferenceType;
  };
};
export type Shadows = {
  'bottom-100': string | RefferenceType;
  'bottom-200': string | RefferenceType;
  'bottom-300': string | RefferenceType;
  'bottom-400': string | RefferenceType;
  'top-100': string | RefferenceType;
  'top-200': string | RefferenceType;
  'top-300': string | RefferenceType;
  'top-400': string | RefferenceType;
};
export type Opacity = {
  '0': string | RefferenceType;
  '50': string | RefferenceType;
  '100': string | RefferenceType;
  disabled: string | RefferenceType;
};
