import { th } from '@xstyled/system';

import { Theme } from './Theme.interface';

const figmaTokens = {
  colors: {
    '$color-coolGrey--4': '#1b242c',
    '$color-coolGrey--3': '#272e35',
    '$color-coolGrey--2': '#3a424a',
    '$color-coolGrey--1': '#4a545e',
    '$color-coolGrey-0': '#555f6d',
    '$color-coolGrey-+1': '#7e8c9a',
    '$color-coolGrey-+2': '#9ea8b3',
    '$color-coolGrey-+3': '#cfd6dd',
    '$color-coolGrey-+4': '#dee3e7',
    '$color-coolGrey-+5': '#eaedf0',
    '$color-coolGrey-+6': '#f0f3f5',
    '$color-coolGrey-+7': '#f5f7f9',
    '$color-coolGrey-+8': '#fcfcfd',
    '$color-coolGreyA--4': '#0a141ced',
    '$color-coolGreyA--3': '#0a1219e0',
    '$color-coolGreyA--2': '#1a232ddb',
    '$color-coolGreyA--1': '#1d2936cc',
    '$color-coolGreyA-0': '#19273abd',
    '$color-coolGreyA-+1': '#1830488f',
    '$color-coolGreyA-+2': '#0d264066',
    '$color-coolGreyA-+3': '#10305433',
    '$color-coolGreyA-+4': '#04294421',
    '$color-coolGreyA-+5': '#10284817',
    '$color-coolGreyA-+6': '#022f520f',
    '$color-coolGreyA-+7': '#002b5e0a',
    '$color-coolGreyA-+8': '#1f529e05',
    '$color-neutralGrey--4': '#222222',
    '$color-neutralGrey--3': '#2d2d2d',
    '$color-neutralGrey--2': '#404040',
    '$color-neutralGrey--1': '#525252',
    '$color-neutralGrey-0': '#5e5e5e',
    '$color-neutralGrey-+1': '#898989',
    '$color-neutralGrey-+2': '#a6a6a6',
    '$color-neutralGrey-+3': '#d5d5d5',
    '$color-neutralGrey-+4': '#e2e2e2',
    '$color-neutralGrey-+5': '#ebebeb',
    '$color-neutralGrey-+6': '#f2f2f2',
    '$color-neutralGrey-+7': '#f7f7f7',
    '$color-neutralGrey-+8': '#fcfcfc',
    '$color-neutralGreyA--4': '#111111ed',
    '$color-neutralGreyA--3': '#101010e0',
    '$color-neutralGreyA--2': '#212121db',
    '$color-neutralGreyA--1': '#262626cc',
    '$color-neutralGreyA-0': '#252526bd',
    '$color-neutralGreyA-+1': '#2c2c2c8f',
    '$color-neutralGreyA-+2': '#20202066',
    '$color-neutralGreyA-+3': '#2e2e2e33',
    '$color-neutralGreyA-+4': '#1f1f1f21',
    '$color-neutralGreyA-+5': '#1c1c1c17',
    '$color-neutralGreyA-+6': '#2020200f',
    '$color-neutralGreyA-+7': '#2e2e2e0a',
    '$color-neutralGreyA-+8': '#52525205',
    '$color-warmGrey--4': '#232321',
    '$color-warmGrey--3': '#2f2f2b',
    '$color-warmGrey--2': '#40403a',
    '$color-warmGrey--1': '#52524c',
    '$color-warmGrey-0': '#5f5f58',
    '$color-warmGrey-+1': '#8b8b84',
    '$color-warmGrey-+2': '#a8a89f',
    '$color-warmGrey-+3': '#d8d8d2',
    '$color-warmGrey-+4': '#e4e4e0',
    '$color-warmGrey-+5': '#eaeae6',
    '$color-warmGrey-+6': '#f3f3f1',
    '$color-warmGrey-+7': '#f7f7f7',
    '$color-warmGrey-+8': '#fcfcfc',
    '$color-warmGreyA--4': '#121210ed',
    '$color-warmGreyA--3': '#13130ee0',
    '$color-warmGreyA--2': '#21211adb',
    '$color-warmGreyA--1': '#272720cc',
    '$color-warmGreyA-0': '#27271dbd',
    '$color-warmGreyA-+1': '#2f2f238f',
    '$color-warmGreyA-+2': '#26261066',
    '$color-warmGreyA-+3': '#3e3e1d33',
    '$color-warmGreyA-+4': '#32321421',
    '$color-warmGreyA-+5': '#22220217',
    '$color-warmGreyA-+6': '#2f2f0e0f',
    '$color-warmGreyA-+7': '#2f2f2c0a',
    '$color-warmGreyA-+8': '#52525205',
    '$color-whiteA--12': '#ffffff05',
    '$color-whiteA--11': '#ffffff08',
    '$color-whiteA--10': '#ffffff0d',
    '$color-whiteA--9': '#ffffff14',
    '$color-whiteA--8': '#ffffff1a',
    '$color-whiteA--7': '#ffffff1f',
    '$color-whiteA--6': '#ffffff3d',
    '$color-whiteA--5': '#ffffff66',
    '$color-whiteA--4': '#ffffffa3',
    '$color-whiteA--3': '#ffffffad',
    '$color-whiteA--2': '#ffffffb8',
    '$color-whiteA--1': '#ffffffd1',
    '$color-whiteA-0': '#ffffff',
    '$color-transparent': '#ffffff00',
    '$color-red--4': '#4a0d0d',
    '$color-red--3': '#6f2020',
    '$color-red--2': '#952d2d',
    '$color-red--1': '#a13636',
    '$color-red-0': '#c53434',
    '$color-red-+1': '#f26464',
    '$color-red-+2': '#f49090',
    '$color-red-+3': '#fccfcf',
    '$color-red-+4': '#fcd9d9',
    '$color-red-+5': '#fee6e6',
    '$color-red-+6': '#ffebeb',
    '$color-red-+7': '#fef5f5',
    '$color-red-+8': '#fffafa',
    '$color-raspberry--4': '#450c1f',
    '$color-raspberry--3': '#671e36',
    '$color-raspberry--2': '#912b4d',
    '$color-raspberry--1': '#9d3457',
    '$color-raspberry-0': '#c03060',
    '$color-raspberry-+1': '#e4628d',
    '$color-raspberry-+2': '#ec8dad',
    '$color-raspberry-+3': '#f8cedc',
    '$color-raspberry-+4': '#fbd5e2',
    '$color-raspberry-+5': '#fde3eb',
    '$color-raspberry-+6': '#fdedf2',
    '$color-raspberry-+7': '#fef5f8',
    '$color-raspberry-+8': '#fffafc',
    '$color-magenta--4': '#410b2f',
    '$color-magenta--3': '#671e4e',
    '$color-magenta--2': '#892969',
    '$color-magenta--1': '#953274',
    '$color-magenta-0': '#b12f86',
    '$color-magenta-+1': '#de5eb3',
    '$color-magenta-+2': '#ec89cb',
    '$color-magenta-+3': '#f7cae8',
    '$color-magenta-+4': '#fbd5ee',
    '$color-magenta-+5': '#fde3f4',
    '$color-magenta-+6': '#fdedf8',
    '$color-magenta-+7': '#fef5fb',
    '$color-magenta-+8': '#fffafd',
    '$color-purple--4': '#410b2f',
    '$color-purple--3': '#5b1e67',
    '$color-purple--2': '#792989',
    '$color-purple--1': '#853295',
    '$color-purple-0': '#9939ac',
    '$color-purple-+1': '#c466db',
    '$color-purple-+2': '#d98dec',
    '$color-purple-+3': '#f4caf7',
    '$color-purple-+4': '#f5d5fb',
    '$color-purple-+5': '#f8e3fd',
    '$color-purple-+6': '#faedfd',
    '$color-purple-+7': '#fdf5ff',
    '$color-purple-+8': '#fefaff',
    '$color-grape--4': '#2e0e4e',
    '$color-grape--3': '#4c2277',
    '$color-grape--2': '#662f9d',
    '$color-grape--1': '#7339ac',
    '$color-grape-0': '#8040bf',
    '$color-grape-+1': '#ad71ea',
    '$color-grape-+2': '#c494f4',
    '$color-grape-+3': '#e5d0fb',
    '$color-grape-+4': '#eddbff',
    '$color-grape-+5': '#f2e5ff',
    '$color-grape-+6': '#f6f0ff',
    '$color-grape-+7': '#faf5ff',
    '$color-grape-+8': '#fcfaff',
    '$color-violet--4': '#1f1264',
    '$color-violet--3': '#39288a',
    '$color-violet--2': '#4e38bc',
    '$color-violet--1': '#573fcf',
    '$color-violet-0': '#634eca',
    '$color-violet-+1': '#917ef1',
    '$color-violet-+2': '#aba2fb',
    '$color-violet-+3': '#dcd6ff',
    '$color-violet-+4': '#e3e0ff',
    '$color-violet-+5': '#eeebff',
    '$color-violet-+6': '#f3f0ff',
    '$color-violet-+7': '#f7f5ff',
    '$color-violet-+8': '#fbfaff',
    '$color-blue--4': '#05205e',
    '$color-blue--3': '#113997',
    '$color-blue--2': '#1e50c0',
    '$color-blue--1': '#2759cd',
    '$color-blue-0': '#3062d4',
    '$color-blue-+1': '#6792f4',
    '$color-blue-+2': '#8db0fb',
    '$color-blue-+3': '#cdddff',
    '$color-blue-+4': '#d7e4ff',
    '$color-blue-+5': '#e5eeff',
    '$color-blue-+6': '#edf2ff',
    '$color-blue-+7': '#f5f8ff',
    '$color-blue-+8': '#fafbff',
    '$color-cyan--4': '#002742',
    '$color-cyan--3': '#0c456e',
    '$color-cyan--2': '#165b8d',
    '$color-cyan--1': '#1b679d',
    '$color-cyan-0': '#0870ba',
    '$color-cyan-+1': '#5699dc',
    '$color-cyan-+2': '#79bcf6',
    '$color-cyan-+3': '#c2e3ff',
    '$color-cyan-+4': '#cce7ff',
    '$color-cyan-+5': '#e0f1ff',
    '$color-cyan-+6': '#ebf5ff',
    '$color-cyan-+7': '#f0f9ff',
    '$color-cyan-+8': '#fafdff',
    '$color-teal--4': '#012a37',
    '$color-teal--3': '#0a495c',
    '$color-teal--2': '#196076',
    '$color-teal--1': '#196c85',
    '$color-teal-0': '#077597',
    '$color-teal-+1': '#4f9eba',
    '$color-teal-+2': '#7ac0dc',
    '$color-teal-+3': '#b8e8f5',
    '$color-teal-+4': '#c5ecf7',
    '$color-teal-+5': '#e0f3fa',
    '$color-teal-+6': '#e8f7fc',
    '$color-teal-+7': '#f0fbff',
    '$color-teal-+8': '#fafeff',
    '$color-aquamarine--4': '#012d26',
    '$color-aquamarine--3': '#0d4a42',
    '$color-aquamarine--2': '#15655a',
    '$color-aquamarine--1': '#1a7061',
    '$color-aquamarine-0': '#097c69',
    '$color-aquamarine-+1': '#3da497',
    '$color-aquamarine-+2': '#6ec9bf',
    '$color-aquamarine-+3': '#bee9e4',
    '$color-aquamarine-+4': '#c5f2ec',
    '$color-aquamarine-+5': '#daf6f3',
    '$color-aquamarine-+6': '#e2f8f5',
    '$color-aquamarine-+7': '#f0faf9',
    '$color-aquamarine-+8': '#fbfefe',
    '$color-green--4': '#062d1b',
    '$color-green--3': '#0e4e30',
    '$color-green--2': '#196742',
    '$color-green--1': '#1e714a',
    '$color-green-0': '#1d7c4d',
    '$color-green-+1': '#4aa578',
    '$color-green-+2': '#75cc9e',
    '$color-green-+3': '#c2ebd5',
    '$color-green-+4': '#c6f1da',
    '$color-green-+5': '#d8f8e7',
    '$color-green-+6': '#e6f9ef',
    '$color-green-+7': '#f4fbf7',
    '$color-green-+8': '#fbfefc',
    '$color-emerald--4': '#0a2e0b',
    '$color-emerald--3': '#135315',
    '$color-emerald--2': '#246626',
    '$color-emerald--1': '#2f6f2f',
    '$color-emerald-0': '#347434',
    '$color-emerald-+1': '#55a555',
    '$color-emerald-+2': '#87c987',
    '$color-emerald-+3': '#c6ecc6',
    '$color-emerald-+4': '#cff2cf',
    '$color-emerald-+5': '#dff6df',
    '$color-emerald-+6': '#e6f9e6',
    '$color-emerald-+7': '#f4fbf4',
    '$color-emerald-+8': '#fbfefb',
    '$color-orange--4': '#482909',
    '$color-orange--3': '#7a4510',
    '$color-orange--2': '#a05c1c',
    '$color-orange--1': '#b4610e',
    '$color-orange-0': '#f59638',
    '$color-orange-+1': '#f6a351',
    '$color-orange-+2': '#feb872',
    '$color-orange-+3': '#ffd4a8',
    '$color-orange-+4': '#fcdec0',
    '$color-orange-+5': '#ffe8d1',
    '$color-orange-+6': '#fff0e0',
    '$color-orange-+7': '#fff5eb',
    '$color-orange-+8': '#fffcfa',
    '$color-semantic-brand--4': th.color('$color-blue--4'),
    '$color-semantic-brand--3': th.color('$color-blue--3'),
    '$color-semantic-brand--2': th.color('$color-blue--2'),
    '$color-semantic-brand--1': th.color('$color-blue--1'),
    '$color-semantic-brand-0': th.color('$color-blue-0'),
    '$color-semantic-brand-+1': th.color('$color-blue-+1'),
    '$color-semantic-brand-+2': th.color('$color-blue-+2'),
    '$color-semantic-brand-+3': th.color('$color-blue-+3'),
    '$color-semantic-brand-+4': th.color('$color-blue-+4'),
    '$color-semantic-brand-+5': th.color('$color-blue-+5'),
    '$color-semantic-brand-+6': th.color('$color-blue-+6'),
    '$color-semantic-brand-+7': th.color('$color-blue-+7'),
    '$color-semantic-brand-+8': th.color('$color-blue-+8'),
    '$color-semantic-neutral--4': th.color('$color-coolGrey--4'),
    '$color-semantic-neutral--3': th.color('$color-coolGrey--3'),
    '$color-semantic-neutral--2': th.color('$color-coolGrey--2'),
    '$color-semantic-neutral--1': th.color('$color-coolGrey--1'),
    '$color-semantic-neutral-0': th.color('$color-coolGrey-0'),
    '$color-semantic-neutral-+1': th.color('$color-coolGrey-+1'),
    '$color-semantic-neutral-+2': th.color('$color-coolGrey-+2'),
    '$color-semantic-neutral-+3': th.color('$color-coolGrey-+3'),
    '$color-semantic-neutral-+4': th.color('$color-coolGrey-+4'),
    '$color-semantic-neutral-+5': th.color('$color-coolGrey-+5'),
    '$color-semantic-neutral-+6': th.color('$color-coolGrey-+6'),
    '$color-semantic-neutral-+7': th.color('$color-coolGrey-+7'),
    '$color-semantic-neutral-+8': th.color('$color-coolGrey-+8'),
    '$color-semantic-neutralA--4': th.color('$color-coolGreyA--4'),
    '$color-semantic-neutralA--3': th.color('$color-coolGreyA--3'),
    '$color-semantic-neutralA--2': th.color('$color-coolGreyA--2'),
    '$color-semantic-neutralA--1': th.color('$color-coolGreyA--1'),
    '$color-semantic-neutralA-0': th.color('$color-coolGreyA-0'),
    '$color-semantic-neutralA-+1': th.color('$color-coolGreyA-+1'),
    '$color-semantic-neutralA-+2': th.color('$color-coolGreyA-+2'),
    '$color-semantic-neutralA-+3': th.color('$color-coolGreyA-+3'),
    '$color-semantic-neutralA-+4': th.color('$color-coolGreyA-+4'),
    '$color-semantic-neutralA-+5': th.color('$color-coolGreyA-+5'),
    '$color-semantic-neutralA-+6': th.color('$color-coolGreyA-+6'),
    '$color-semantic-neutralA-+7': th.color('$color-coolGreyA-+7'),
    '$color-semantic-neutralA-+8': th.color('$color-coolGreyA-+8'),
    '$color-semantic-informative--4': th.color('$color-blue--4'),
    '$color-semantic-informative--3': th.color('$color-blue--3'),
    '$color-semantic-informative--2': th.color('$color-blue--2'),
    '$color-semantic-informative--1': th.color('$color-blue--1'),
    '$color-semantic-informative-0': th.color('$color-blue-0'),
    '$color-semantic-informative-+1': th.color('$color-blue-+1'),
    '$color-semantic-informative-+2': th.color('$color-blue-+2'),
    '$color-semantic-informative-+3': th.color('$color-blue-+3'),
    '$color-semantic-informative-+4': th.color('$color-blue-+4'),
    '$color-semantic-informative-+5': th.color('$color-blue-+5'),
    '$color-semantic-informative-+6': th.color('$color-blue-+6'),
    '$color-semantic-informative-+7': th.color('$color-blue-+7'),
    '$color-semantic-informative-+8': th.color('$color-blue-+8'),
    '$color-semantic-positive--4': th.color('$color-green--4'),
    '$color-semantic-positive--3': th.color('$color-green--3'),
    '$color-semantic-positive--2': th.color('$color-green--2'),
    '$color-semantic-positive--1': th.color('$color-green--1'),
    '$color-semantic-positive-0': th.color('$color-green-0'),
    '$color-semantic-positive-+1': th.color('$color-green-+1'),
    '$color-semantic-positive-+2': th.color('$color-green-+2'),
    '$color-semantic-positive-+3': th.color('$color-green-+3'),
    '$color-semantic-positive-+4': th.color('$color-green-+4'),
    '$color-semantic-positive-+5': th.color('$color-green-+5'),
    '$color-semantic-positive-+6': th.color('$color-green-+6'),
    '$color-semantic-positive-+7': th.color('$color-green-+7'),
    '$color-semantic-positive-+8': th.color('$color-green-+8'),
    '$color-semantic-warning--4': th.color('$color-orange--4'),
    '$color-semantic-warning--3': th.color('$color-orange--3'),
    '$color-semantic-warning--2': th.color('$color-orange--2'),
    '$color-semantic-warning--1': th.color('$color-orange--1'),
    '$color-semantic-warning-0': th.color('$color-orange-0'),
    '$color-semantic-warning-+1': th.color('$color-orange-+1'),
    '$color-semantic-warning-+2': th.color('$color-orange-+2'),
    '$color-semantic-warning-+3': th.color('$color-orange-+3'),
    '$color-semantic-warning-+4': th.color('$color-orange-+4'),
    '$color-semantic-warning-+5': th.color('$color-orange-+5'),
    '$color-semantic-warning-+6': th.color('$color-orange-+6'),
    '$color-semantic-warning-+7': th.color('$color-orange-+7'),
    '$color-semantic-warning-+8': th.color('$color-orange-+8'),
    '$color-semantic-negative--4': th.color('$color-red--4'),
    '$color-semantic-negative--3': th.color('$color-red--3'),
    '$color-semantic-negative--2': th.color('$color-red--2'),
    '$color-semantic-negative--1': th.color('$color-red--1'),
    '$color-semantic-negative-0': th.color('$color-red-0'),
    '$color-semantic-negative-+1': th.color('$color-red-+1'),
    '$color-semantic-negative-+2': th.color('$color-red-+2'),
    '$color-semantic-negative-+3': th.color('$color-red-+3'),
    '$color-semantic-negative-+4': th.color('$color-red-+4'),
    '$color-semantic-negative-+5': th.color('$color-red-+5'),
    '$color-semantic-negative-+6': th.color('$color-red-+6'),
    '$color-semantic-negative-+7': th.color('$color-red-+7'),
    '$color-semantic-negative-+8': th.color('$color-red-+8'),
    '$color-content-primary': th.color('$color-semantic-neutral--3'),
    '$color-content-secondary': th.color('$color-semantic-neutral-0'),
    '$color-content-tertiary': th.color('$color-semantic-neutral-+1'),
    '$color-content-disabled': th.color('$color-semantic-neutral-+2'),
    '$color-content-primary-inverted': th.color('$color-whiteA-0'),
    '$color-content-secondary-inverted': th.color('$color-whiteA--4'),
    '$color-content-tertiary-inverted': th.color('$color-whiteA--5'),
    '$color-content-disabled-inverted': th.color('$color-whiteA--6'),
    '$color-content-informative-primary': th.color(
      '$color-semantic-informative--3',
    ),
    '$color-content-informative-secondary': th.color(
      '$color-semantic-informative-0',
    ),
    '$color-content-positive-primary': th.color('$color-semantic-positive--3'),
    '$color-content-positive-secondary': th.color('$color-semantic-positive-0'),
    '$color-content-warning-primary': th.color('$color-semantic-warning--3'),
    '$color-content-warning-secondary': th.color('$color-semantic-warning-0'),
    '$color-content-negative-primary': th.color('$color-semantic-negative--3'),
    '$color-content-negative-secondary': th.color('$color-semantic-negative-0'),
    '$color-content-brand-primary': th.color('$color-semantic-brand--3'),
    '$color-content-brand-secondary': th.color('$color-semantic-brand-0'),
    '$color-border-default': th.color('$color-semantic-neutral-+5'),
    '$color-border-defaultA': th.color('$color-semantic-neutralA-+5'),
    '$color-border-inverted': th.color('$color-whiteA-0'),
    '$color-border-neutral-strong': th.color('$color-semantic-neutral-0'),
    '$color-border-neutral-subtle': th.color('$color-semantic-neutral-+3'),
    '$color-border-informative-strong': th.color(
      '$color-semantic-informative-0',
    ),
    '$color-border-informative-subtle': th.color(
      '$color-semantic-informative-+3',
    ),
    '$color-border-positive-strong': th.color('$color-semantic-positive-0'),
    '$color-border-positive-subtle': th.color('$color-semantic-positive-+3'),
    '$color-border-warning-strong': th.color('$color-semantic-warning-0'),
    '$color-border-warning-subtle': th.color('$color-semantic-warning-+3'),
    '$color-border-negative-strong': th.color('$color-semantic-negative-0'),
    '$color-border-negative-subtle': th.color('$color-semantic-negative-+3'),
    '$color-border-brand-strong': th.color('$color-semantic-brand-0'),
    '$color-border-brand-subtle': th.color('$color-semantic-brand-+3'),
    '$color-background-default': th.color('$color-whiteA-0'),
    '$color-background-inverted': th.color('$color-semantic-neutral--3'),
    '$color-background-neutral-strong': th.color('$color-semantic-neutral-0'),
    '$color-background-neutral-muted': th.color('$color-semantic-neutral-+4'),
    '$color-background-neutral-onSubtle': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-background-neutral-subtle': th.color('$color-semantic-neutral-+7'),
    '$color-background-neutral-surface': th.color('$color-semantic-neutral-+8'),
    '$color-background-informative-strong': th.color(
      '$color-semantic-informative-0',
    ),
    '$color-background-informative-muted': th.color(
      '$color-semantic-informative-+4',
    ),
    '$color-background-informative-onSubtle': th.color(
      '$color-semantic-informative-+5',
    ),
    '$color-background-informative-subtle': th.color(
      '$color-semantic-informative-+7',
    ),
    '$color-background-informative-surface': th.color(
      '$color-semantic-informative-+8',
    ),
    '$color-background-positive-strong': th.color('$color-semantic-positive-0'),
    '$color-background-positive-muted': th.color('$color-semantic-positive-+4'),
    '$color-background-positive-onSubtle': th.color(
      '$color-semantic-positive-+5',
    ),
    '$color-background-positive-subtle': th.color(
      '$color-semantic-positive-+7',
    ),
    '$color-background-positive-surface': th.color(
      '$color-semantic-positive-+8',
    ),
    '$color-background-warning-strong': th.color('$color-semantic-warning-0'),
    '$color-background-warning-muted': th.color('$color-semantic-warning-+4'),
    '$color-background-warning-onSubtle': th.color(
      '$color-semantic-warning-+5',
    ),
    '$color-background-warning-subtle': th.color('$color-semantic-warning-+7'),
    '$color-background-warning-surface': th.color('$color-semantic-warning-+8'),
    '$color-background-negative-strong': th.color('$color-semantic-negative-0'),
    '$color-background-negative-muted': th.color('$color-semantic-negative-+4'),
    '$color-background-negative-onSubtle': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-background-negative-subtle': th.color(
      '$color-semantic-negative-+7',
    ),
    '$color-background-negative-surface': th.color(
      '$color-semantic-negative-+8',
    ),
    '$color-background-brand-strong': th.color('$color-semantic-brand-0'),
    '$color-background-brand-muted': th.color('$color-semantic-brand-+4'),
    '$color-background-brand-onSubtle': th.color('$color-semantic-brand-+5'),
    '$color-background-brand-subtle': th.color('$color-semantic-brand-+7'),
    '$color-background-brand-surface': th.color('$color-semantic-brand-+8'),
    '$color-action-primary-normal': th.color('$color-semantic-brand-0'),
    '$color-action-primary-hover': th.color('$color-semantic-brand--2'),
    '$color-action-primary-active': th.color('$color-semantic-brand--3'),
    '$color-action-primary-selected': th.color('$color-semantic-brand--2'),
    '$color-action-primary-subtle-normal': th.color('$color-semantic-brand-+6'),
    '$color-action-primary-subtle-hover': th.color('$color-semantic-brand-+5'),
    '$color-action-primary-subtle-active': th.color('$color-semantic-brand-+3'),
    '$color-action-primary-subtle-selected': th.color(
      '$color-semantic-brand-+5',
    ),
    '$color-action-neutral-normal': th.color('$color-semantic-neutral--1'),
    '$color-action-neutral-hover': th.color('$color-semantic-neutral--2'),
    '$color-action-neutral-active': th.color('$color-semantic-neutral--3'),
    '$color-action-neutral-selected': th.color('$color-semantic-neutral--2'),
    '$color-action-neutral-subtle-normal': th.color(
      '$color-semantic-neutral-+6',
    ),
    '$color-action-neutral-subtle-hover': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-action-neutral-subtle-active': th.color(
      '$color-semantic-neutral-+3',
    ),
    '$color-action-neutral-subtle-selected': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-action-success-normal': th.color('$color-semantic-positive-0'),
    '$color-action-success-hover': th.color('$color-semantic-positive--2'),
    '$color-action-success-active': th.color('$color-semantic-positive--3'),
    '$color-action-success-selected': th.color('$color-semantic-positive--2'),
    '$color-action-success-subtle-normal': th.color(
      '$color-semantic-positive-+6',
    ),
    '$color-action-success-subtle-hover': th.color(
      '$color-semantic-positive-+5',
    ),
    '$color-action-success-subtle-active': th.color(
      '$color-semantic-positive-+3',
    ),
    '$color-action-success-subtle-selected': th.color(
      '$color-semantic-positive-+5',
    ),
    '$color-action-destructive-normal': th.color('$color-semantic-negative-0'),
    '$color-action-destructive-hover': th.color('$color-semantic-negative--2'),
    '$color-action-destructive-active': th.color('$color-semantic-negative--3'),
    '$color-action-destructive-selected': th.color(
      '$color-semantic-negative--2',
    ),
    '$color-action-destructive-subtle-normal': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-action-destructive-subtle-hover': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-action-destructive-subtle-active': th.color(
      '$color-semantic-negative-+3',
    ),
    '$color-action-destructive-subtle-selected': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-action-ghost-normal': th.color('$color-transparent'),
    '$color-action-ghost-hover': th.color('$color-semantic-neutralA-+6'),
    '$color-action-ghost-active': th.color('$color-semantic-neutralA-+5'),
    '$color-action-ghost-selected': th.color('$color-semantic-neutralA-+6'),
    '$color-action-ghost-inverted-hover': th.color('$color-whiteA--8'),
    '$color-action-ghost-inverted-active': th.color('$color-whiteA--7'),
    '$color-action-ghost-inverted-selected': th.color('$color-whiteA--8'),
    '$color-action-ghost-destructive-hover': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-action-ghost-destructive-active': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-action-ghost-destructive-selected': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-action-outline-normal': th.color('$color-semantic-neutral-+3'),
    '$color-action-outline-hover': th.color('$color-semantic-neutral-+2'),
    '$color-action-outline-active': th.color('$color-semantic-neutral-+1'),
    '$color-action-outline-selected': th.color('$color-semantic-neutral-+2'),
    '$color-action-inverted-normal': th.color('$color-whiteA-0'),
    '$color-action-inverted-hover': th.color('$color-whiteA--1'),
    '$color-action-inverted-active': th.color('$color-whiteA--2'),
    '$color-action-inverted-selected': th.color('$color-whiteA--1'),
    '$color-action-reverseInverted-normal': th.color(
      '$color-semantic-neutralA--3',
    ),
    '$color-action-reverseInverted-hover': th.color(
      '$color-semantic-neutralA--1',
    ),
    '$color-action-reverseInverted-active': th.color(
      '$color-semantic-neutralA-0',
    ),
    '$color-action-reverseInverted-selected': th.color(
      '$color-semantic-neutralA--1',
    ),
    '$color-interaction-default-normal': th.color('$color-blue-0'),
    '$color-interaction-default-hover': th.color('$color-blue--2'),
    '$color-interaction-default-active': th.color('$color-blue--3'),
    '$color-interaction-default-selected': th.color('$color-blue--2'),
    '$color-interaction-default-subtle-normal': th.color('$color-blue-+6'),
    '$color-interaction-default-subtle-hover': th.color('$color-blue-+5'),
    '$color-interaction-default-subtle-active': th.color('$color-blue-+3'),
    '$color-interaction-default-subtle-selected': th.color('$color-blue-+5'),
    '$color-interaction-neutral-normal': th.color('$color-semantic-neutral--1'),
    '$color-interaction-neutral-hover': th.color('$color-semantic-neutral--2'),
    '$color-interaction-neutral-active': th.color('$color-semantic-neutral--3'),
    '$color-interaction-neutral-selected': th.color(
      '$color-semantic-neutral--2',
    ),
    '$color-interaction-neutral-subtle-normal': th.color(
      '$color-semantic-neutral-+6',
    ),
    '$color-interaction-neutral-subtle-hover': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-interaction-neutral-subtle-active': th.color(
      '$color-semantic-neutral-+3',
    ),
    '$color-interaction-neutral-subtle-selected': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-interaction-alert-normal': th.color('$color-semantic-negative-0'),
    '$color-interaction-alert-hover': th.color('$color-semantic-negative--2'),
    '$color-interaction-alert-active': th.color('$color-semantic-negative--3'),
    '$color-interaction-alert-selected': th.color(
      '$color-semantic-negative--2',
    ),
    '$color-interaction-alert-subtle-normal': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-interaction-alert-subtle-hover': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-interaction-alert-subtle-active': th.color(
      '$color-semantic-negative-+3',
    ),
    '$color-interaction-alert-subtle-selected': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-interaction-ghost-normal': th.color('$color-transparent'),
    '$color-interaction-ghost-hover': th.color('$color-semantic-neutralA-+6'),
    '$color-interaction-ghost-active': th.color('$color-semantic-neutralA-+5'),
    '$color-interaction-ghost-selected': th.color(
      '$color-semantic-neutralA-+6',
    ),
    '$color-interaction-ghost-inverted-hover': th.color('$color-whiteA--8'),
    '$color-interaction-ghost-inverted-normal': th.color('$color-whiteA--7'),
    '$color-interaction-ghost-inverted-selected': th.color('$color-whiteA--8'),
    '$color-interaction-ghost-destructive-selected': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-interaction-ghost-destructive-normal': th.color(
      '$color-semantic-negative-+5',
    ),
    '$color-interaction-ghost-destructive-hover': th.color(
      '$color-semantic-negative-+6',
    ),
    '$color-interaction-disabled-normal': th.color(
      '$color-semantic-neutral-+2',
    ),
    '$color-interaction-disabled-hover': th.color('$color-semantic-neutral-+1'),
    '$color-interaction-disabled-active': th.color('$color-semantic-neutral-0'),
    '$color-interaction-disabled-subtle-normal': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-interaction-disabled-subtle-hover': th.color(
      '$color-semantic-neutral-+4',
    ),
    '$color-interaction-disabled-subtle-active': th.color(
      '$color-semantic-neutral-+3',
    ),
    '$color-interaction-border-normal': th.color('$color-blue-+2'),
    '$color-interaction-border-hover': th.color('$color-blue-+1'),
    '$color-interaction-border-active': th.color('$color-blue--1'),
    '$color-interaction-border-selected': th.color('$color-blue-0'),
    '$color-interaction-border-neutral-normal': th.color(
      '$color-semantic-neutral-+3',
    ),
    '$color-interaction-border-neutral-hover': th.color(
      '$color-semantic-neutral-+2',
    ),
    '$color-interaction-border-neutral-active': th.color(
      '$color-semantic-neutral-+1',
    ),
    '$color-interaction-border-neutral-selected': th.color(
      '$color-semantic-neutral-+2',
    ),
    '$color-interaction-border-alert': th.color('$color-semantic-negative-+1'),
    '$color-interaction-background-modal': th.color(
      '$color-background-default',
    ),
    '$color-interaction-background-modeless': th.color(
      '$color-background-default',
    ),
    '$color-interaction-background-modeless-inverted': th.color(
      '$color-background-inverted',
    ),
    '$color-interaction-background-sidepanel': th.color(
      '$color-background-default',
    ),
    '$color-interaction-background-formField': th.color(
      '$color-background-default',
    ),
    '$color-interaction-background-dimmer': th.color(
      '$color-semantic-neutralA-0',
    ),
    '$color-interaction-inverted-normal': th.color('$color-whiteA-0'),
    '$color-interaction-inverted-hover': th.color('$color-whiteA--1'),
    '$color-interaction-inverted-active': th.color('$color-whiteA--2'),
    '$color-interaction-inverted-selected': th.color('$color-whiteA--1'),
    '$color-interaction-focus-default': th.color('$color-blue-+1'),
    '$color-nonSemantic-grey-content-primary': th.color(
      '$color-semantic-neutral--3',
    ),
    '$color-nonSemantic-grey-content-secondary': th.color(
      '$color-semantic-neutral-0',
    ),
    '$color-nonSemantic-grey-border-default': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-nonSemantic-grey-border-strong': th.color(
      '$color-semantic-neutral-0',
    ),
    '$color-nonSemantic-grey-border-subtle': th.color(
      '$color-semantic-neutral-+3',
    ),
    '$color-nonSemantic-grey-background-strong': th.color(
      '$color-semantic-neutral-0',
    ),
    '$color-nonSemantic-grey-background-muted': th.color(
      '$color-semantic-neutral-+4',
    ),
    '$color-nonSemantic-grey-background-onSubtle': th.color(
      '$color-semantic-neutral-+5',
    ),
    '$color-nonSemantic-grey-background-subtle': th.color(
      '$color-semantic-neutral-+7',
    ),
    '$color-nonSemantic-grey-background-surface': th.color(
      '$color-semantic-neutral-+8',
    ),
    '$color-nonSemantic-white-content-primary': th.color('$color-whiteA-0'),
    '$color-nonSemantic-white-content-secondary': th.color('$color-whiteA--4'),
    '$color-nonSemantic-white-border-default': th.color('$color-whiteA--5'),
    '$color-nonSemantic-white-border-strong': th.color('$color-whiteA-0'),
    '$color-nonSemantic-white-border-subtle': th.color('$color-whiteA--3'),
    '$color-nonSemantic-white-background-strong': th.color('$color-whiteA-0'),
    '$color-nonSemantic-white-background-muted': th.color('$color-whiteA--4'),
    '$color-nonSemantic-white-background-onSubtle':
      th.color('$color-whiteA--5'),
    '$color-nonSemantic-white-background-subtle': th.color('$color-whiteA--7'),
    '$color-nonSemantic-white-background-surface': th.color('$color-whiteA--8'),
    '$color-nonSemantic-red-content-primary': th.color('$color-red--3'),
    '$color-nonSemantic-red-content-secondary': th.color('$color-red-0'),
    '$color-nonSemantic-red-border-default': th.color('$color-red-+5'),
    '$color-nonSemantic-red-border-strong': th.color('$color-red-0'),
    '$color-nonSemantic-red-border-subtle': th.color('$color-red-+3'),
    '$color-nonSemantic-red-background-strong': th.color('$color-red-0'),
    '$color-nonSemantic-red-background-muted': th.color('$color-red-+4'),
    '$color-nonSemantic-red-background-onSubtle': th.color('$color-red-+5'),
    '$color-nonSemantic-red-background-subtle': th.color('$color-red-+7'),
    '$color-nonSemantic-red-background-surface': th.color('$color-red-+8'),
    '$color-nonSemantic-raspberry-content-primary': th.color(
      '$color-raspberry--3',
    ),
    '$color-nonSemantic-raspberry-content-secondary':
      th.color('$color-raspberry-0'),
    '$color-nonSemantic-raspberry-border-default': th.color(
      '$color-raspberry-+5',
    ),
    '$color-nonSemantic-raspberry-border-strong':
      th.color('$color-raspberry-0'),
    '$color-nonSemantic-raspberry-border-subtle': th.color(
      '$color-raspberry-+3',
    ),
    '$color-nonSemantic-raspberry-background-strong':
      th.color('$color-raspberry-0'),
    '$color-nonSemantic-raspberry-background-muted': th.color(
      '$color-raspberry-+4',
    ),
    '$color-nonSemantic-raspberry-background-onSubtle': th.color(
      '$color-raspberry-+5',
    ),
    '$color-nonSemantic-raspberry-background-subtle': th.color(
      '$color-raspberry-+7',
    ),
    '$color-nonSemantic-raspberry-background-surface': th.color(
      '$color-raspberry-+8',
    ),
    '$color-nonSemantic-magenta-content-primary': th.color('$color-magenta--3'),
    '$color-nonSemantic-magenta-content-secondary':
      th.color('$color-magenta-0'),
    '$color-nonSemantic-magenta-border-default': th.color('$color-magenta-+5'),
    '$color-nonSemantic-magenta-border-strong': th.color('$color-magenta-0'),
    '$color-nonSemantic-magenta-border-subtle': th.color('$color-magenta-+3'),
    '$color-nonSemantic-magenta-background-strong':
      th.color('$color-magenta-0'),
    '$color-nonSemantic-magenta-background-muted':
      th.color('$color-magenta-+4'),
    '$color-nonSemantic-magenta-background-onSubtle':
      th.color('$color-magenta-+5'),
    '$color-nonSemantic-magenta-background-subtle':
      th.color('$color-magenta-+7'),
    '$color-nonSemantic-magenta-background-surface':
      th.color('$color-magenta-+8'),
    '$color-nonSemantic-purple-content-primary': th.color('$color-purple--3'),
    '$color-nonSemantic-purple-content-secondary': th.color('$color-purple-0'),
    '$color-nonSemantic-purple-border-default': th.color('$color-purple-+5'),
    '$color-nonSemantic-purple-border-strong': th.color('$color-purple-0'),
    '$color-nonSemantic-purple-border-subtle': th.color('$color-purple-+3'),
    '$color-nonSemantic-purple-background-strong': th.color('$color-purple-0'),
    '$color-nonSemantic-purple-background-muted': th.color('$color-purple-+4'),
    '$color-nonSemantic-purple-background-onSubtle':
      th.color('$color-purple-+5'),
    '$color-nonSemantic-purple-background-subtle': th.color('$color-purple-+7'),
    '$color-nonSemantic-purple-background-surface':
      th.color('$color-purple-+8'),
    '$color-nonSemantic-grape-content-primary': th.color('$color-grape--3'),
    '$color-nonSemantic-grape-content-secondary': th.color('$color-grape-0'),
    '$color-nonSemantic-grape-border-default': th.color('$color-grape-+5'),
    '$color-nonSemantic-grape-border-strong': th.color('$color-grape-0'),
    '$color-nonSemantic-grape-border-subtle': th.color('$color-grape-+3'),
    '$color-nonSemantic-grape-background-strong': th.color('$color-grape-0'),
    '$color-nonSemantic-grape-background-muted': th.color('$color-grape-+4'),
    '$color-nonSemantic-grape-background-onSubtle': th.color('$color-grape-+5'),
    '$color-nonSemantic-grape-background-subtle': th.color('$color-grape-+7'),
    '$color-nonSemantic-grape-background-surface': th.color('$color-grape-+8'),
    '$color-nonSemantic-violet-content-primary': th.color('$color-violet--3'),
    '$color-nonSemantic-violet-content-secondary': th.color('$color-violet-0'),
    '$color-nonSemantic-violet-border-default': th.color('$color-violet-+5'),
    '$color-nonSemantic-violet-border-strong': th.color('$color-violet-0'),
    '$color-nonSemantic-violet-border-subtle': th.color('$color-violet-+3'),
    '$color-nonSemantic-violet-background-strong': th.color('$color-violet-0'),
    '$color-nonSemantic-violet-background-muted': th.color('$color-violet-+4'),
    '$color-nonSemantic-violet-background-onSubtle':
      th.color('$color-violet-+5'),
    '$color-nonSemantic-violet-background-subtle': th.color('$color-violet-+7'),
    '$color-nonSemantic-violet-background-surface':
      th.color('$color-violet-+8'),
    '$color-nonSemantic-blue-content-primary': th.color('$color-blue--3'),
    '$color-nonSemantic-blue-content-secondary': th.color('$color-blue-0'),
    '$color-nonSemantic-blue-border-default': th.color('$color-blue-+5'),
    '$color-nonSemantic-blue-border-strong': th.color('$color-blue-0'),
    '$color-nonSemantic-blue-border-subtle': th.color('$color-blue-+3'),
    '$color-nonSemantic-blue-background-strong': th.color('$color-blue-0'),
    '$color-nonSemantic-blue-background-muted': th.color('$color-blue-+4'),
    '$color-nonSemantic-blue-background-onSubtle': th.color('$color-blue-+5'),
    '$color-nonSemantic-blue-background-subtle': th.color('$color-blue-+7'),
    '$color-nonSemantic-blue-background-surface': th.color('$color-blue-+8'),
    '$color-nonSemantic-cyan-content-primary': th.color('$color-cyan--3'),
    '$color-nonSemantic-cyan-content-secondary': th.color('$color-cyan-0'),
    '$color-nonSemantic-cyan-border-default': th.color('$color-cyan-+5'),
    '$color-nonSemantic-cyan-border-strong': th.color('$color-cyan-0'),
    '$color-nonSemantic-cyan-border-subtle': th.color('$color-cyan-+3'),
    '$color-nonSemantic-cyan-background-strong': th.color('$color-cyan-0'),
    '$color-nonSemantic-cyan-background-muted': th.color('$color-cyan-+4'),
    '$color-nonSemantic-cyan-background-onSubtle': th.color('$color-cyan-+5'),
    '$color-nonSemantic-cyan-background-subtle': th.color('$color-cyan-+7'),
    '$color-nonSemantic-cyan-background-surface': th.color('$color-cyan-+8'),
    '$color-nonSemantic-teal-content-primary': th.color('$color-teal--3'),
    '$color-nonSemantic-teal-content-secondary': th.color('$color-teal-0'),
    '$color-nonSemantic-teal-border-default': th.color('$color-teal-+5'),
    '$color-nonSemantic-teal-border-strong': th.color('$color-teal-0'),
    '$color-nonSemantic-teal-border-subtle': th.color('$color-teal-+3'),
    '$color-nonSemantic-teal-background-strong': th.color('$color-teal-0'),
    '$color-nonSemantic-teal-background-muted': th.color('$color-teal-+4'),
    '$color-nonSemantic-teal-background-onSubtle': th.color('$color-teal-+5'),
    '$color-nonSemantic-teal-background-subtle': th.color('$color-teal-+7'),
    '$color-nonSemantic-teal-background-surface': th.color('$color-teal-+8'),
    '$color-nonSemantic-aquamarine-content-primary': th.color(
      '$color-aquamarine--3',
    ),
    '$color-nonSemantic-aquamarine-content-secondary': th.color(
      '$color-aquamarine-0',
    ),
    '$color-nonSemantic-aquamarine-border-default': th.color(
      '$color-aquamarine-+5',
    ),
    '$color-nonSemantic-aquamarine-border-strong': th.color(
      '$color-aquamarine-0',
    ),
    '$color-nonSemantic-aquamarine-border-subtle': th.color(
      '$color-aquamarine-+3',
    ),
    '$color-nonSemantic-aquamarine-background-strong': th.color(
      '$color-aquamarine-0',
    ),
    '$color-nonSemantic-aquamarine-background-muted': th.color(
      '$color-aquamarine-+4',
    ),
    '$color-nonSemantic-aquamarine-background-onSubtle': th.color(
      '$color-aquamarine-+5',
    ),
    '$color-nonSemantic-aquamarine-background-subtle': th.color(
      '$color-aquamarine-+7',
    ),
    '$color-nonSemantic-aquamarine-background-surface': th.color(
      '$color-aquamarine-+8',
    ),
    '$color-nonSemantic-green-content-primary': th.color('$color-green--3'),
    '$color-nonSemantic-green-content-secondary': th.color('$color-green-0'),
    '$color-nonSemantic-green-border-default': th.color('$color-green-+5'),
    '$color-nonSemantic-green-border-strong': th.color('$color-green-0'),
    '$color-nonSemantic-green-border-subtle': th.color('$color-green-+3'),
    '$color-nonSemantic-green-background-strong': th.color('$color-green-0'),
    '$color-nonSemantic-green-background-muted': th.color('$color-green-+4'),
    '$color-nonSemantic-green-background-onSubtle': th.color('$color-green-+5'),
    '$color-nonSemantic-green-background-subtle': th.color('$color-green-+7'),
    '$color-nonSemantic-green-background-surface': th.color('$color-green-+8'),
    '$color-nonSemantic-emerald-content-primary': th.color('$color-emerald--3'),
    '$color-nonSemantic-emerald-content-secondary':
      th.color('$color-emerald-0'),
    '$color-nonSemantic-emerald-border-default': th.color('$color-emerald-+5'),
    '$color-nonSemantic-emerald-border-strong': th.color('$color-emerald-0'),
    '$color-nonSemantic-emerald-border-subtle': th.color('$color-emerald-+3'),
    '$color-nonSemantic-emerald-background-strong':
      th.color('$color-emerald-0'),
    '$color-nonSemantic-emerald-background-muted':
      th.color('$color-emerald-+4'),
    '$color-nonSemantic-emerald-background-onSubtle':
      th.color('$color-emerald-+5'),
    '$color-nonSemantic-emerald-background-subtle':
      th.color('$color-emerald-+7'),
    '$color-nonSemantic-emerald-background-surface':
      th.color('$color-emerald-+8'),
    '$color-nonSemantic-orange-content-primary': th.color('$color-orange--3'),
    '$color-nonSemantic-orange-content-secondary': th.color('$color-orange-0'),
    '$color-nonSemantic-orange-border-default': th.color('$color-orange-+5'),
    '$color-nonSemantic-orange-border-strong': th.color('$color-orange-0'),
    '$color-nonSemantic-orange-border-subtle': th.color('$color-orange-+3'),
    '$color-nonSemantic-orange-background-strong': th.color('$color-orange-0'),
    '$color-nonSemantic-orange-background-muted': th.color('$color-orange-+4'),
    '$color-nonSemantic-orange-background-onSubtle':
      th.color('$color-orange-+5'),
    '$color-nonSemantic-orange-background-subtle': th.color('$color-orange-+7'),
    '$color-nonSemantic-orange-background-surface':
      th.color('$color-orange-+8'),
  },
  radii: {
    '$border-radius-25': 2,
    '$border-radius-50': 4,
    '$border-radius-100': 8,
    '$border-radius-999': 9999,
    '$border-radius-small': th.radius('$border-radius-25'),
    '$border-radius-medium': th.radius('$border-radius-50'),
    '$border-radius-large': th.radius('$border-radius-100'),
    '$border-radius-full': th.radius('$border-radius-999'),
    '$border-radius-150': 12,
    '$border-radius-xLarge': th.radius('$border-radius-150'),
  },
  space: {
    '$space-component-padding-null': th.space('$dimension-0'),
    '$space-component-padding-xSmall': th.space('$dimension-50'),
    '$space-component-padding-small': th.space('$dimension-100'),
    '$space-component-padding-medium': th.space('$dimension-150'),
    '$space-component-padding-large': th.space('$dimension-200'),
    '$space-component-padding-2xLarge': th.space('$dimension-300'),
    '$space-component-gap-null': th.space('$dimension-0'),
    '$space-component-gap-2xSmall': th.space('$dimension-25'),
    '$space-component-gap-xSmall': th.space('$dimension-50'),
    '$space-component-gap-small': th.space('$dimension-100'),
    '$space-component-gap-medium': th.space('$dimension-150'),
    '$space-component-gap-large': th.space('$dimension-200'),
    '$space-component-gap-2xLarge': th.space('$dimension-400'),
    '$space-component-gap-xLarge': th.space('$dimension-300'),
    '$space-component-padding-3xLarge': th.space('$dimension-400'),
    '$space-component-padding-4xLarge': th.space('$dimension-500'),
    '$space-component-padding-6xLarge': th.space('$dimension-800'),
    '$space-component-padding-2xSmall': th.space('$dimension-25'),
    '$space-component-padding-xLarge': th.space('$dimension-250'),
    '$dimension-0': 0,
    '$dimension-25': 2,
    '$dimension-50': 4,
    '$dimension-100': 8,
    '$dimension-150': 12,
    '$dimension-200': 16,
    '$dimension-250': 20,
    '$dimension-300': 24,
    '$dimension-400': 32,
    '$dimension-500': 40,
    '$dimension-600': 48,
    '$dimension-700': 56,
    '$dimension-800': 64,
    '$dimension-1000': 80,
    '$dimension-1200': 96,
    '$dimension-1500': 120,
    '$dimension-1600': 128,
    '$dimension-550': 44,
    '$space-component-padding-5xLarge': th.space('$dimension-550'),
    '$space-component-gap-3xLarge': th.space('$dimension-550'),
    '$dimension-900': 72,
  },
  sizes: {
    '$size-2xLarge': th.space('$dimension-800'),
    '$size-large': th.space('$dimension-600'),
    '$size-medium': th.space('$dimension-500'),
    '$size-small': th.space('$dimension-400'),
    '$size-xSmall': th.space('$dimension-300'),
    '$size-2xSmall': th.space('$dimension-250'),
    '$size-3xSmall': th.space('$dimension-200'),
    '$size-xLarge': th.space('$dimension-700'),
    '$size-3xLarge': th.space('$dimension-900'),
  },
};

const fixedTokens = {
  borderWidths: {
    '$border-width-0': '0px',
    '$border-width-100': '1px',
    '$border-width-200': '2px',
    '$border-width-small': th.borderWidth('$border-width-100'),
    '$border-width-focus': th.borderWidth('$border-width-200'),
    '$border-width-medium': th.borderWidth('$border-width-200'),
  },
  borderStyles: {
    '$border-style-none': 'none',
    '$border-style-solid': 'solid',
    '$border-style-dashed': 'dashed solid',
  },
  fonts: { '$font-family-primary': 'Inter' },
  fontSizes: {
    '$font-size-125': '10px',
    '$font-size-150': '12px',
    '$font-size-175': '14px',
    '$font-size-200': '16px',
    '$font-size-225': '18px',
    '$font-size-300': '24px',
    '$font-size-400': '32px',
    '$font-size-500': '40px',
    '$font-size-600': '48px',
  },
  fontWeights: {
    '$font-weight-400': '400',
    '$font-weight-450': '450',
    '$font-weight-600': '600',
  },
  letterSpacings: {
    '$font-letterSpacing-0': '0px',
    '$font-letterSpacing-100': '0.1px',
    '$font-letterSpacing-200': '0.2px',
  },
  lineHeights: {
    '$font-lineHeight-scale-100': '1',
    '$font-lineHeight-scale-150': '1.5',
    '$font-lineHeight-scale-166': '1.66',
    '$font-lineHeight-scale-200': '2',
    '$font-lineHeight-value-200': '16px',
    '$font-lineHeight-value-250': '20px',
    '$font-lineHeight-value-300': '24px',
    '$font-lineHeight-value-350': '28px',
    '$font-lineHeight-value-400': '32px',
    '$font-lineHeight-value-450': '36px',
    '$font-lineHeight-value-550': '44px',
    '$font-lineHeight-value-700': '56px',
    '$font-lineHeight-value-800': '64px',
  },
  texts: {
    '$typo-normal-125': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-125',
      lineHeight: '$font-lineHeight-value-200',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-150': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-175': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-200': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-225': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-225',
      lineHeight: '$font-lineHeight-value-400',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-300': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-300',
      lineHeight: '$font-lineHeight-value-450',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-400': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-400',
      lineHeight: '$font-lineHeight-value-550',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-500': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-500',
      lineHeight: '$font-lineHeight-value-700',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-normal-600': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-600',
      lineHeight: '$font-lineHeight-value-800',
      fontWeight: '$font-weight-400',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-125': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-125',
      lineHeight: '$font-lineHeight-value-200',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-150': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-175': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-200': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-225': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-225',
      lineHeight: '$font-lineHeight-value-400',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-300': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-300',
      lineHeight: '$font-lineHeight-value-450',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-400': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-400',
      lineHeight: '$font-lineHeight-value-550',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-500': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-500',
      lineHeight: '$font-lineHeight-value-700',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-medium-600': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-600',
      lineHeight: '$font-lineHeight-value-800',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-strong-125': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-125',
      lineHeight: '$font-lineHeight-value-200',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-150': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-175': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-200': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-225': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-225',
      lineHeight: '$font-lineHeight-value-400',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-300': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-300',
      lineHeight: '$font-lineHeight-value-450',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-400': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-400',
      lineHeight: '$font-lineHeight-value-550',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-500': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-500',
      lineHeight: '$font-lineHeight-value-700',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-strong-600': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-600',
      lineHeight: '$font-lineHeight-value-800',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-body-large': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-body-medium': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-body-small': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-body-xSmall': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-125',
      lineHeight: '$font-lineHeight-value-200',
      fontWeight: '$font-weight-450',
      letterSpacing: '$font-letterSpacing-200',
    },
    '$typo-body-strong-large': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-body-strong-medium': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-body-strong-small': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-body-strong-xSmall': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-125',
      lineHeight: '$font-lineHeight-value-200',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-hero-large': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-500',
      lineHeight: '$font-lineHeight-value-700',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-hero-medium': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-600',
      lineHeight: '$font-lineHeight-value-800',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-4xLarge': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-400',
      lineHeight: '$font-lineHeight-value-550',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-3xLarge': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-300',
      lineHeight: '$font-lineHeight-value-450',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-xLarge': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-225',
      lineHeight: '$font-lineHeight-value-400',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-large': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-200',
      lineHeight: '$font-lineHeight-value-350',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-medium': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-175',
      lineHeight: '$font-lineHeight-value-300',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
    '$typo-header-small': {
      fontFamily: '$font-family-primary',
      fontSize: '$font-size-150',
      lineHeight: '$font-lineHeight-value-250',
      fontWeight: '$font-weight-600',
      letterSpacing: '$font-letterSpacing-100',
    },
  },
  opacity: {
    '$opacity-0': '0',
    '$opacity-50': '0.5',
    '$opacity-100': '1',
    '$opacity-disabled': '0.5',
  },
  screens: {
    _: 0,
    xs: 0,
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
    '2xl': 1536,
  },
  states: {
    _: null,
    motionSafe: '@media (prefers-reduced-motion: no-preference)',
    motionReduce: '@media (prefers-reduced-motion: reduce)',
    first: '&:first-child',
    last: '&:last-child',
    odd: '&:odd',
    even: '&:even',
    visited: '&:visited',
    checked: '&:checked',
    focusWithin: '&:focus-within',
    hover: '&:hover',
    focus: '&:focus',
    focusVisible: '&:focus-visible',
    active: '&:active',
    placeholder: '&::placeholder',
    disabled: '&:disabled, &[aria-disabled=true], &[data-state="disabled"]',
    selected: '&[data-state="selected"], &[aria-selected=true]',
    loading: '&[data-state="loading"]',
    hoverWithoutButton:
      '&:hover:not(:has(button:hover), &:invalid, &[data-state="alert"])',
    alert: '&:invalid, &[data-state="alert"]',
    indeterminate: '&:indeterminate, &[data-state="indeterminate"]',
  },
  // TO DO: utility for xstyled to gather color of shadow and generate rgba based on opacity
  shadows: {
    '$elevation-bottom-100': '0px 1px 2px 0px rgba(27, 36, 44, 0.12)',
    '$elevation-bottom-200':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 2px 8px -1px rgba(27, 36, 44, 0.08)',
    '$elevation-bottom-300':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 8px 16px -2px rgba(27, 36, 44, 0.12)',
    '$elevation-bottom-400':
      '0px 2px 2px -1px rgba(27, 36, 44, 0.04), 0px 16px 24px -6px rgba(27, 36, 44, 0.16)',
    '$elevation-top-100': '0px -1px 2px 0px rgba(27, 36, 44, 0.12)',
    '$elevation-top-200':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -2px 8px -1px rgba(27, 36, 44, 0.08)',
    '$elevation-top-300':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -8px 16px -2px rgba(27, 36, 44, 0.12)',
    '$elevation-top-400':
      '0px -2px 2px -1px rgba(27, 36, 44, 0.04), 0px -16px 24px -6px rgba(27, 36, 44, 0.16)',
  },
};

export const theme: Theme = {
  ...figmaTokens,
  ...fixedTokens,
  ringWidths: fixedTokens.borderWidths,
};
