# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      HELLO: ${{ secrets.HELLO }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build-storybook
      - run: yarn test
      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_TOKEN }}
