on:
  push:
    branches:
      - "main"
  workflow_dispatch:

name: Release Latest [Automatic]

permissions:
  contents: write
  pull-requests: write

jobs:
 release-latest:
   name: Release Latest
   runs-on: ubuntu-latest
   environment: 
    name: production
   if: contains(github.event.head_commit.message, 'chore(main)')
   steps:
    - name: Create Tag and Release
      uses: google-github-actions/release-please-action@v3.7.12
      id: release-latest
      with:
        release-type: node
        package-name: "@virtuslab/tetrisly-react"
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Change from RC to Latest
      run: npm dist-tag add $(npm dist-tag rm @virtuslab/tetrisly-react@rc rc | cut -c 6-) latest
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
